/** Practical Communication (Giao tiếp thực tế) — extra topic lesson bank */
export const COMMUNICATION_LESSONS = {
  a1: [
    {
      title: 'Morning greetings',
      sentences: [
        'Good morning!',
        'How are you today?',
        'I am fine, thank you.',
        'Nice to see you.',
        'Have a good day!',
      ],
      vi: [
        'Chào buổi sáng!',
        'Hôm nay bạn khỏe không?',
        'Tôi khỏe, cảm ơn bạn.',
        'Rất vui được gặp bạn.',
        'Chúc bạn một ngày tốt lành!',
      ],
    },
    {
      title: 'Evening greetings',
      sentences: [
        'Good evening.',
        'Hello, how was your day?',
        'It was good, thanks.',
        'See you tomorrow.',
        'Good night!',
      ],
      vi: [
        'Chào buổi tối.',
        'Xin chào, hôm nay của bạn thế nào?',
        'Rất tốt, cảm ơn.',
        'Hẹn gặp lại ngày mai.',
        'Chúc ngủ ngon!',
      ],
    },
    {
      title: 'Please and thank you at the shop',
      sentences: [
        'One bottle of water, please.',
        'Here you are.',
        'Thank you very much.',
        'You are welcome.',
        'Have a nice day!',
      ],
      vi: [
        'Cho tôi một chai nước, làm ơn.',
        'Đây ạ.',
        'Cảm ơn bạn rất nhiều.',
        'Không có gì.',
        'Chúc bạn một ngày vui vẻ!',
      ],
    },
    {
      title: 'Please and thank you with friends',
      sentences: [
        'Can you help me, please?',
        'Yes, of course.',
        'Thank you for your help.',
        'No problem.',
        'You are very kind.',
      ],
      vi: [
        'Bạn có thể giúp tôi được không?',
        'Vâng, tất nhiên rồi.',
        'Cảm ơn bạn đã giúp.',
        'Không sao đâu.',
        'Bạn rất tốt bụng.',
      ],
    },
    {
      title: 'Asking someone\'s name',
      sentences: [
        'What is your name?',
        'My name is Lan.',
        'Nice to meet you, Lan.',
        'Nice to meet you too.',
        'Where are you from?',
      ],
      vi: [
        'Bạn tên là gì?',
        'Tôi tên là Lan.',
        'Rất vui được gặp bạn, Lan.',
        'Tôi cũng rất vui được gặp bạn.',
        'Bạn đến từ đâu?',
      ],
    },
    {
      title: 'Introducing yourself in class',
      sentences: [
        'Hello, I am Minh.',
        'I am a new student.',
        'I am from Hanoi.',
        'I like English.',
        'It is nice to be here.',
      ],
      vi: [
        'Xin chào, tôi là Minh.',
        'Tôi là học sinh mới.',
        'Tôi đến từ Hà Nội.',
        'Tôi thích tiếng Anh.',
        'Rất vui được ở đây.',
      ],
    },
    {
      title: 'Answering the phone',
      sentences: [
        'Hello?',
        'May I speak to Hoa, please?',
        'One moment, please.',
        'She is not here right now.',
        'Can I take a message?',
      ],
      vi: [
        'A lô?',
        'Cho tôi nói chuyện với Hoa được không?',
        'Xin đợi một chút.',
        'Cô ấy hiện không có ở đây.',
        'Tôi có thể nhận lời nhắn không?',
      ],
    },
    {
      title: 'Making a simple phone call',
      sentences: [
        'Hi, this is Nam.',
        'Is this the bakery?',
        'What time do you close?',
        'You close at eight o\'clock.',
        'Thank you. Goodbye!',
      ],
      vi: [
        'Chào bạn, tôi là Nam.',
        'Đây có phải tiệm bánh không?',
        'Tiệm đóng cửa lúc mấy giờ?',
        'Tiệm đóng cửa lúc tám giờ.',
        'Cảm ơn bạn. Tạm biệt!',
      ],
    },
    {
      title: 'Saying sorry',
      sentences: [
        'I am sorry.',
        'I am late.',
        'That is okay.',
        'It does not matter.',
        'Please do not worry.',
      ],
      vi: [
        'Tôi xin lỗi.',
        'Tôi đến muộn.',
        'Không sao đâu.',
        'Không có vấn đề gì.',
        'Đừng lo lắng nhé.',
      ],
    },
    {
      title: 'Excuse me politely',
      sentences: [
        'Excuse me.',
        'Is this seat free?',
        'Yes, it is.',
        'Thank you.',
        'Sorry to bother you.',
      ],
      vi: [
        'Xin lỗi.',
        'Ghế này còn trống không?',
        'Vâng, còn trống.',
        'Cảm ơn bạn.',
        'Xin lỗi vì làm phiền bạn.',
      ],
    },
  ],

  a2: [
    {
      title: 'Making a doctor appointment',
      sentences: [
        'I would like to make an appointment, please.',
        'What day is good for you?',
        'Is Tuesday morning available?',
        'Yes, ten o\'clock works.',
        'Thank you. I will be there on time.',
      ],
      vi: [
        'Tôi muốn đặt lịch hẹn, làm ơn.',
        'Ngày nào thuận tiện cho bạn?',
        'Sáng thứ Ba còn trống không?',
        'Vâng, mười giờ được.',
        'Cảm ơn. Tôi sẽ đến đúng giờ.',
      ],
    },
    {
      title: 'Booking a haircut',
      sentences: [
        'Can I book a haircut for Friday?',
        'What time would you like?',
        'Around three in the afternoon, please.',
        'We have a slot at three thirty.',
        'Perfect. See you then.',
      ],
      vi: [
        'Tôi có thể đặt lịch cắt tóc vào thứ Sáu không?',
        'Bạn muốn lúc mấy giờ?',
        'Khoảng ba giờ chiều, làm ơn.',
        'Chúng tôi còn chỗ lúc ba giờ ba mươi.',
        'Tuyệt vời. Hẹn gặp lại.',
      ],
    },
    {
      title: 'Leaving a voicemail',
      sentences: [
        'Hi, this is Trang calling.',
        'I tried to reach you this morning.',
        'Please call me back when you can.',
        'My number is zero nine one two three four five.',
        'Thanks. Bye for now.',
      ],
      vi: [
        'Chào bạn, Trang đây.',
        'Sáng nay tôi đã gọi cho bạn.',
        'Hãy gọi lại khi bạn rảnh nhé.',
        'Số của tôi là không chín một hai ba bốn năm.',
        'Cảm ơn. Tạm biệt.',
      ],
    },
    {
      title: 'Leaving a message for a colleague',
      sentences: [
        'Could you tell Mr. Phong I called?',
        'I need to discuss the report with him.',
        'I will be available after lunch.',
        'He can email me if that is easier.',
        'Thank you for passing on the message.',
      ],
      vi: [
        'Bạn có thể báo anh Phong là tôi đã gọi không?',
        'Tôi cần trao đổi với anh ấy về báo cáo.',
        'Tôi rảnh sau giờ trưa.',
        'Anh ấy có thể gửi email nếu tiện hơn.',
        'Cảm ơn bạn đã chuyển lời.',
      ],
    },
    {
      title: 'Asking for help in a store',
      sentences: [
        'Excuse me, could you help me?',
        'I am looking for a blue shirt.',
        'What size do you need?',
        'Medium, please.',
        'The changing room is over there.',
      ],
      vi: [
        'Xin lỗi, bạn có thể giúp tôi không?',
        'Tôi đang tìm áo sơ mi màu xanh.',
        'Bạn cần cỡ nào?',
        'Cỡ vừa, làm ơn.',
        'Phòng thử đồ ở đằng kia.',
      ],
    },
    {
      title: 'Asking for directions',
      sentences: [
        'Sorry to bother you.',
        'How do I get to the train station?',
        'Go straight and turn left.',
        'Is it far from here?',
        'It is about ten minutes on foot.',
      ],
      vi: [
        'Xin lỗi vì làm phiền bạn.',
        'Làm sao để đến ga tàu?',
        'Đi thẳng rồi rẽ trái.',
        'Có xa đây không?',
        'Khoảng mười phút đi bộ.',
      ],
    },
    {
      title: 'Inviting someone to dinner',
      sentences: [
        'Would you like to have dinner with us?',
        'That sounds lovely.',
        'We are meeting at seven on Saturday.',
        'Should I bring anything?',
        'Just yourself. We look forward to seeing you.',
      ],
      vi: [
        'Bạn có muốn ăn tối cùng chúng tôi không?',
        'Nghe hay đấy.',
        'Chúng tôi gặp lúc bảy giờ thứ Bảy.',
        'Tôi có cần mang gì không?',
        'Chỉ cần bạn đến thôi. Rất mong được gặp bạn.',
      ],
    },
    {
      title: 'Inviting friends to a party',
      sentences: [
        'We are having a small party next week.',
        'You are very welcome to come.',
        'It starts at six on Friday evening.',
        'Great! Can I bring a friend?',
        'Of course. The more the merrier.',
      ],
      vi: [
        'Tuần sau chúng tôi có một bữa tiệc nhỏ.',
        'Rất mong bạn đến.',
        'Bắt đầu lúc sáu giờ tối thứ Sáu.',
        'Tuyệt! Tôi có thể mang theo bạn không?',
        'Tất nhiên rồi. Càng đông càng vui.',
      ],
    },
    {
      title: 'Small talk about the weather',
      sentences: [
        'It is really hot today, isn\'t it?',
        'Yes, I hope it rains soon.',
        'The forecast says it will cool down tomorrow.',
        'That would be nice.',
        'At least the evenings are pleasant.',
      ],
      vi: [
        'Hôm nay nóng thật, phải không?',
        'Vâng, tôi hy vọng sẽ mưa sớm.',
        'Dự báo nói ngày mai sẽ mát hơn.',
        'Thế thì tốt quá.',
        'Ít nhất buổi tối cũng dễ chịu.',
      ],
    },
    {
      title: 'Small talk about the weekend',
      sentences: [
        'Do you have any plans for the weekend?',
        'I might visit my grandparents.',
        'That sounds nice.',
        'What about you?',
        'I am thinking of going hiking.',
      ],
      vi: [
        'Cuối tuần bạn có kế hoạch gì không?',
        'Có lẽ tôi sẽ thăm ông bà.',
        'Nghe hay đấy.',
        'Còn bạn thì sao?',
        'Tôi đang nghĩ đi leo núi.',
      ],
    },
  ],

  b1: [
    {
      title: 'Polite requests at work',
      sentences: [
        'Would you mind sending me the file by noon?',
        'I am afraid I am quite busy this morning.',
        'Could we possibly move the deadline to tomorrow?',
        'That should be fine if you let me know today.',
        'I really appreciate your flexibility.',
      ],
      vi: [
        'Bạn có phiền gửi file cho tôi trước trưa không?',
        'Sáng nay tôi e là khá bận.',
        'Chúng ta có thể dời hạn sang ngày mai không?',
        'Được nếu bạn báo cho tôi biết hôm nay.',
        'Tôi rất trân trọng sự linh hoạt của bạn.',
      ],
    },
    {
      title: 'Polite requests with neighbours',
      sentences: [
        'I wonder if you could keep the music down after ten.',
        'Oh, I am sorry. I did not realise it was loud.',
        'No worries. I just have an early meeting.',
        'Thanks for understanding.',
        'I will make sure it stays quiet.',
      ],
      vi: [
        'Không biết sau mười giờ bạn có thể hạ nhạc xuống không?',
        'Ồ, xin lỗi. Tôi không biết là to thế.',
        'Không sao. Tôi chỉ có cuộc họp sớm thôi.',
        'Cảm ơn bạn đã thông cảm.',
        'Tôi sẽ để yên lặng.',
      ],
    },
    {
      title: 'Making a complaint at a restaurant',
      sentences: [
        'Excuse me, I ordered the grilled fish, not chicken.',
        'I am so sorry about that.',
        'Could you bring the correct dish, please?',
        'Of course. It will be ready in a few minutes.',
        'Thank you. These things happen.',
      ],
      vi: [
        'Xin lỗi, tôi gọi cá nướng chứ không phải gà.',
        'Tôi rất xin lỗi về việc đó.',
        'Bạn có thể mang món đúng được không?',
        'Tất nhiên. Món sẽ sẵn sau vài phút.',
        'Cảm ơn. Đôi khi cũng xảy ra thôi.',
      ],
    },
    {
      title: 'Complaining about a hotel room',
      sentences: [
        'I am afraid the air conditioning is not working.',
        'I apologise for the inconvenience.',
        'Could someone come and fix it this evening?',
        'A technician will be there within thirty minutes.',
        'That would be very helpful. Thank you.',
      ],
      vi: [
        'Tôi e là điều hòa không hoạt động.',
        'Tôi xin lỗi vì sự bất tiện này.',
        'Có ai đến sửa tối nay được không?',
        'Kỹ thuật viên sẽ đến trong ba mươi phút.',
        'Vậy thì rất tốt. Cảm ơn bạn.',
      ],
    },
    {
      title: 'Giving opinions about a film',
      sentences: [
        'In my opinion, the story was a bit slow.',
        'I see your point, but I liked the acting.',
        'The ending surprised me, to be honest.',
        'Fair enough. Everyone has different tastes.',
        'Still, it was worth watching together.',
      ],
      vi: [
        'Theo tôi, câu chuyện hơi chậm.',
        'Tôi hiểu ý bạn, nhưng tôi thích diễn xuất.',
        'Thật lòng mà nói, kết thúc làm tôi bất ngờ.',
        'Cũng hợp lý. Mỗi người một gu.',
        'Dù sao xem cùng nhau cũng đáng.',
      ],
    },
    {
      title: 'Sharing opinions in a meeting',
      sentences: [
        'From my perspective, we should focus on quality first.',
        'That is a valid concern.',
        'However, I believe speed matters in this market.',
        'Perhaps we can balance both priorities.',
        'Let us discuss the trade-offs openly.',
      ],
      vi: [
        'Theo quan điểm của tôi, ta nên ưu tiên chất lượng trước.',
        'Đó là mối lo hợp lý.',
        'Tuy nhiên, tôi cho rằng tốc độ quan trọng trong thị trường này.',
        'Có lẽ ta có thể cân bằng cả hai.',
        'Hãy thảo luận thẳng thắn về đánh đổi.',
      ],
    },
    {
      title: 'Networking at a conference',
      sentences: [
        'Hi, I do not think we have met. I am Linh from GreenTech.',
        'Nice to meet you. I work in product design.',
        'What brings you to this event?',
        'I am interested in sustainable packaging.',
        'Let us exchange contact details.',
      ],
      vi: [
        'Chào bạn, hình như chúng ta chưa gặp. Tôi là Linh từ GreenTech.',
        'Rất vui được gặp. Tôi làm thiết kế sản phẩm.',
        'Bạn đến sự kiện này vì điều gì?',
        'Tôi quan tâm đến bao bì bền vững.',
        'Trao đổi thông tin liên lạc nhé.',
      ],
    },
    {
      title: 'Connecting on professional networks',
      sentences: [
        'I enjoyed our conversation earlier.',
        'Would you like to connect on LinkedIn?',
        'Sure. I will send you a request.',
        'I look forward to staying in touch.',
        'Maybe we can collaborate in the future.',
      ],
      vi: [
        'Tôi rất thích cuộc trò chuyện lúc nãy.',
        'Bạn có muốn kết nối trên LinkedIn không?',
        'Được. Tôi sẽ gửi lời mời.',
        'Mong được giữ liên lạc.',
        'Biết đâu sau này ta có thể hợp tác.',
      ],
    },
    {
      title: 'Joining a video call',
      sentences: [
        'Good morning, everyone. Can you hear me clearly?',
        'Yes, we can hear you fine.',
        'I will share my screen in a moment.',
        'Please mute your microphone when you are not speaking.',
        'Let us start with the agenda.',
      ],
      vi: [
        'Chào buổi sáng mọi người. Nghe rõ tôi không?',
        'Vâng, nghe rõ.',
        'Tôi sẽ chia sẻ màn hình ngay.',
        'Hãy tắt mic khi không nói.',
        'Bắt đầu với chương trình nghị sự nhé.',
      ],
    },
    {
      title: 'Handling video call problems',
      sentences: [
        'Sorry, my connection seems unstable.',
        'Your video is freezing a little.',
        'I will turn off my camera to save bandwidth.',
        'That is better. We can hear you now.',
        'Thanks for your patience.',
      ],
      vi: [
        'Xin lỗi, kết nối của tôi có vẻ không ổn định.',
        'Hình của bạn hơi đứng.',
        'Tôi sẽ tắt camera để tiết kiệm băng thông.',
        'Tốt hơn rồi. Giờ nghe rõ bạn.',
        'Cảm ơn mọi người đã kiên nhẫn.',
      ],
    },
  ],

  b2: [
    {
      title: 'Negotiating salary',
      sentences: [
        'Based on my experience, I was hoping for a higher offer.',
        'What range did you have in mind?',
        'I was thinking of something closer to forty-five thousand.',
        'We may be able to meet you in the middle.',
        'Could we revisit benefits as part of the package?',
      ],
      vi: [
        'Dựa trên kinh nghiệm, tôi mong mức đề nghị cao hơn.',
        'Bạn đang nghĩ đến khoảng nào?',
        'Tôi nghĩ gần bốn mươi lăm nghìn.',
        'Chúng tôi có thể thỏa hiệp.',
        'Ta có thể xem lại phúc lợi trong gói đãi ngộ không?',
      ],
    },
    {
      title: 'Negotiating contract terms',
      sentences: [
        'We would prefer a twelve-month contract with a review clause.',
        'That is reasonable, provided payment terms stay the same.',
        'Could delivery dates be flexible during peak season?',
        'We can agree to two weeks\' notice for schedule changes.',
        'Let us put that in writing before we sign.',
      ],
      vi: [
        'Chúng tôi muốn hợp đồng mười hai tháng có điều khoản xem xét.',
        'Hợp lý, nếu điều khoản thanh toán giữ nguyên.',
        'Ngày giao hàng có linh hoạt mùa cao điểm không?',
        'Chúng tôi đồng ý báo trước hai tuần khi đổi lịch.',
        'Hãy ghi vào văn bản trước khi ký.',
      ],
    },
    {
      title: 'Writing a formal request email',
      sentences: [
        'Dear Ms. Nguyen, I am writing to request further information.',
        'Specifically, I would appreciate details on the project timeline.',
        'Please let me know if any documents are required from our side.',
        'I would be grateful for a response by the end of the week.',
        'Thank you for your time and assistance.',
      ],
      vi: [
        'Kính gửi cô Nguyễn, tôi viết để xin thêm thông tin.',
        'Cụ thể, tôi mong biết chi tiết về tiến độ dự án.',
        'Xin cho biết bên chúng tôi cần nộp tài liệu gì.',
        'Rất mong nhận phản hồi trước cuối tuần.',
        'Cảm ơn thời gian và sự hỗ trợ của cô.',
      ],
    },
    {
      title: 'Following up on a formal email',
      sentences: [
        'I am following up on my email sent last Tuesday.',
        'I understand you may be busy with other priorities.',
        'Could you confirm whether you received the attached proposal?',
        'I am happy to clarify any points at your convenience.',
        'I look forward to hearing from you soon.',
      ],
      vi: [
        'Tôi theo dõi email đã gửi thứ Ba tuần trước.',
        'Tôi hiểu bạn có thể bận việc khác.',
        'Bạn có nhận được đề xuất đính kèm không?',
        'Tôi sẵn sàng làm rõ khi bạn thuận tiện.',
        'Mong sớm nhận được hồi âm.',
      ],
    },
    {
      title: 'Opening a presentation',
      sentences: [
        'Good afternoon. Thank you for joining us today.',
        'My name is Duc, and I lead the marketing team.',
        'Over the next twenty minutes, I will outline our strategy.',
        'Please feel free to ask questions at the end.',
        'Let us begin with the current market situation.',
      ],
      vi: [
        'Chào buổi chiều. Cảm ơn mọi người đã tham dự.',
        'Tôi là Đức, trưởng nhóm marketing.',
        'Trong hai mươi phút tới, tôi trình bày chiến lược.',
        'Mời đặt câu hỏi ở cuối.',
        'Bắt đầu với tình hình thị trường hiện tại.',
      ],
    },
    {
      title: 'Handling questions after a presentation',
      sentences: [
        'That is an excellent question.',
        'If I understand correctly, you are asking about costs.',
        'Our projections suggest a modest increase in year two.',
        'I do not have that figure with me, but I will follow up.',
        'Does that address your concern?',
      ],
      vi: [
        'Đó là câu hỏi rất hay.',
        'Nếu tôi hiểu đúng, bạn hỏi về chi phí.',
        'Dự báo cho thấy tăng nhẹ ở năm hai.',
        'Tôi không mang số liệu đó, nhưng sẽ bổ sung sau.',
        'Như vậy đã trả lời được thắc mắc của bạn chưa?',
      ],
    },
    {
      title: 'Resolving a workplace conflict',
      sentences: [
        'I think we are talking past each other.',
        'Could we summarise what we both agree on?',
        'We both want the project to succeed on time.',
        'Perhaps we can split the tasks more clearly.',
        'Let us check in again on Friday.',
      ],
      vi: [
        'Tôi nghĩ ta đang nói lệch nhau.',
        'Ta tóm lại điểm đồng thuận được không?',
        'Cả hai đều muốn dự án đúng hạn.',
        'Có lẽ ta chia việc rõ ràng hơn.',
        'Thứ Sáu ta kiểm tra lại tiến độ.',
      ],
    },
    {
      title: 'De-escalating a customer dispute',
      sentences: [
        'I completely understand why you are frustrated.',
        'Let me review exactly what happened.',
        'We take responsibility for the delay in shipping.',
        'I can offer a partial refund or a replacement.',
        'Which option would work best for you?',
      ],
      vi: [
        'Tôi hiểu vì sao bạn bực bội.',
        'Để tôi xem lại chính xác chuyện gì đã xảy ra.',
        'Chúng tôi chịu trách nhiệm về chậm giao hàng.',
        'Tôi có thể hoàn một phần hoặc đổi hàng.',
        'Phương án nào phù hợp với bạn?',
      ],
    },
    {
      title: 'Communicating across cultures in business',
      sentences: [
        'In our culture, direct disagreement can sound rude.',
        'Thank you for explaining that context.',
        'How would you prefer we give feedback in meetings?',
        'A brief email before big decisions helps us prepare.',
        'I appreciate you adapting to our working style.',
      ],
      vi: [
        'Trong văn hóa chúng tôi, phản đối thẳng có thể nghe thô.',
        'Cảm ơn bạn giải thích bối cảnh đó.',
        'Bạn muốn chúng tôi phản hồi trong họp thế nào?',
        'Email ngắn trước quyết định lớn giúp chúng tôi chuẩn bị.',
        'Tôi trân trọng bạn điều chỉnh theo cách làm việc của chúng tôi.',
      ],
    },
    {
      title: 'Gift-giving across cultures',
      sentences: [
        'Is it customary to bring a gift to a first business dinner?',
        'A modest gift is appreciated, but nothing too expensive.',
        'We usually open gifts in private, not at the table.',
        'That is helpful to know. I will choose something appropriate.',
        'Your thoughtfulness matters more than the price.',
      ],
      vi: [
        'Có phong tục mang quà đến bữa tối công việc đầu tiên không?',
        'Quà nhỏ được trân trọng, nhưng đừng quá đắt.',
        'Thường mở quà riêng, không phải tại bàn.',
        'Biết vậy hữu ích. Tôi sẽ chọn quà phù hợp.',
        'Sự chu đáo quan trọng hơn giá tiền.',
      ],
    },
  ],

  c1: [
    {
      title: 'Building a rhetorical argument',
      sentences: [
        'To persuade a sceptical audience, begin with shared values.',
        'Evidence alone rarely shifts opinion without emotional resonance.',
        'A well-placed anecdote can make abstract data memorable.',
        'Anticipate counterarguments before your listeners raise them.',
        'Close by linking your proposal to a vision they already trust.',
      ],
      vi: [
        'Để thuyết phục khán giả hoài nghi, hãy bắt đầu từ giá trị chung.',
        'Bằng chứng đơn thuần hiếm khi đổi ý nếu thiếu cảm xúc.',
        'Một giai thoại đúng lúc giúp số liệu trừu tượng dễ nhớ.',
        'Hãy dự đoán phản biện trước khi người nghe nêu ra.',
        'Kết thúc bằng cách gắn đề xuất với tầm nhìn họ đã tin.',
      ],
    },
    {
      title: 'Responding to counterarguments',
      sentences: [
        'Your objection highlights a genuine tension in the policy.',
        'Rather than dismiss it, I would reframe the trade-off.',
        'The cost of inaction may exceed the cost of reform.',
        'Historical precedents suggest cautious optimism is warranted.',
        'I invite scrutiny, but not at the expense of urgency.',
      ],
      vi: [
        'Phản đối của bạn chỉ ra mâu thuẫn thực sự trong chính sách.',
        'Thay vì bác bỏ, tôi muốn định khung lại sự đánh đổi.',
        'Chi phí không hành động có thể lớn hơn cải cách.',
        'Tiền lệ lịch sử cho thấy nên lạc quan thận trọng.',
        'Tôi hoan nghênh giám sát, nhưng không được chậm trễ.',
      ],
    },
    {
      title: 'Diplomatic language in criticism',
      sentences: [
        'I wonder whether an alternative approach might yield better results.',
        'With respect, the timeline appears ambitious given current constraints.',
        'I would not characterise the effort as insufficient, merely misaligned.',
        'Perhaps we could revisit assumptions before escalating the issue.',
        'My intention is to strengthen the proposal, not undermine it.',
      ],
      vi: [
        'Tôi tự hỏi liệu cách khác có cho kết quả tốt hơn không.',
        'Thưa ý kiến, tiến độ có vẻ tham vọng với ràng buộc hiện tại.',
        'Tôi không gọi là thiếu nỗ lực, mà là chưa phù hợp.',
        'Có lẽ ta nên xem lại giả định trước khi leo thang.',
        'Ý tôi là củng cố đề xuất, không phải phá hoại.',
      ],
    },
    {
      title: 'Declining gracefully',
      sentences: [
        'I am honoured by the invitation, though I must decline.',
        'Prior commitments leave me unable to participate fully.',
        'I would gladly support the initiative in an advisory capacity.',
        'Please do not interpret my refusal as a lack of enthusiasm.',
        'I hope we can collaborate on a future occasion.',
      ],
      vi: [
        'Tôi vinh dự được mời, dù phải từ chối.',
        'Cam kết trước khiến tôi không tham gia đầy đủ được.',
        'Tôi sẵn sàng hỗ trợ với vai trò cố vấn.',
        'Xin đừng hiểu từ chối là thiếu nhiệt tình.',
        'Hy vọng lần sau ta có thể hợp tác.',
      ],
    },
    {
      title: 'Opening a media interview',
      sentences: [
        'Thank you for having me. I am happy to discuss the report.',
        'Our findings are based on two years of peer-reviewed research.',
        'I will be direct, but I may need to clarify complex terms.',
        'If a question falls outside my expertise, I will say so plainly.',
        'Let us focus on what communities can do starting today.',
      ],
      vi: [
        'Cảm ơn đã mời tôi. Tôi sẵn sàng thảo luận báo cáo.',
        'Kết quả dựa trên hai năm nghiên cứu được phản biện.',
        'Tôi sẽ thẳng thắn, nhưng có thể cần giải thích thuật ngữ.',
        'Câu hỏi ngoài chuyên môn, tôi sẽ nói rõ.',
        'Hãy tập trung vào việc cộng đồng có thể làm từ hôm nay.',
      ],
    },
    {
      title: 'Handling tough interview questions',
      sentences: [
        'That is a fair question, and the public deserves a clear answer.',
        'The data do not support a simple yes or no conclusion.',
        'Critics are right to demand transparency on this point.',
        'We are implementing safeguards that were absent two years ago.',
        'I will not speculate beyond what the evidence allows.',
      ],
      vi: [
        'Đó là câu hỏi hợp lý, và công chúng xứng đáng có câu trả lời rõ.',
        'Dữ liệu không hỗ trợ kết luận đơn giản có hoặc không.',
        'Người phê bình đúng khi đòi minh bạch ở điểm này.',
        'Chúng tôi đang áp dụng biện pháp chưa có hai năm trước.',
        'Tôi sẽ không suy đoán vượt quá bằng chứng cho phép.',
      ],
    },
    {
      title: 'Crafting a persuasive call to action',
      sentences: [
        'If we act now, we can still shape the outcome.',
        'Delay converts a manageable challenge into a crisis.',
        'Each of you has influence within your own network.',
        'Sign the pledge, share the briefing, and attend the hearing.',
        'History will judge us by what we chose to do this year.',
      ],
      vi: [
        'Nếu hành động ngay, ta vẫn định hình được kết quả.',
        'Trì hoãn biến thách thức có thể kiểm soát thành khủng hoảng.',
        'Mỗi người đều có ảnh hưởng trong mạng lưới của mình.',
        'Ký cam kết, chia sẻ bản tóm tắt, và tham dự phiên điều trần.',
        'Lịch sử sẽ phán xét ta qua việc ta chọn làm năm nay.',
      ],
    },
    {
      title: 'Balancing logic and emotional appeal',
      sentences: [
        'Statistics establish credibility, but stories sustain commitment.',
        'Fear can motivate briefly; hope sustains long-term change.',
        'Avoid manipulating grief for applause.',
        'Pair every alarming figure with a concrete path forward.',
        'Authentic emotion, grounded in fact, moves people to act.',
      ],
      vi: [
        'Thống kê tạo uy tín, nhưng câu chuyện duy trì cam kết.',
        'Sợ hãi chỉ thúc đẩy tạm thời; hy vọng nuôi dưỡng thay đổi lâu dài.',
        'Tránh lợi dụng nỗi đau để được hoan hô.',
        'Mỗi con số đáng lo hãy đi kèm lộ trình cụ thể.',
        'Cảm xúc chân thật, dựa trên sự thật, thúc đẩy hành động.',
      ],
    },
    {
      title: 'Ethics of transparent communication',
      sentences: [
        'Leaders owe stakeholders accuracy, even when the news is unwelcome.',
        'Selective disclosure erodes trust faster than bad results.',
        'Acknowledge uncertainty rather than feign absolute confidence.',
        'Correct errors publicly and without delay.',
        'Transparency is not cruelty; it is respect.',
      ],
      vi: [
        'Lãnh đạo phải cung cấp thông tin chính xác, kể cả khi không vui.',
        'Tiết lộ chọn lọc phá niềm tin nhanh hơn kết quả xấu.',
        'Hãy thừa nhận không chắc chắn thay vì giả vờ tự tin tuyệt đối.',
        'Sửa sai công khai và không chần chừ.',
        'Minh bạch không phải tàn nhẫn; đó là sự tôn trọng.',
      ],
    },
    {
      title: 'Responding to misinformation',
      sentences: [
        'The viral claim misrepresents a single outdated study.',
        'Repeating falsehoods verbatim can unintentionally amplify them.',
        'State the facts clearly, then explain why the myth persists.',
        'Direct audiences to primary sources they can verify themselves.',
        'Our duty is to inform, not to humiliate those who were misled.',
      ],
      vi: [
        'Tuyên bố lan truyền bóp méo một nghiên cứu cũ đơn lẻ.',
        'Lặp lại nguyên văn điều sai có thể vô tình khuếch đại.',
        'Nêu sự thật rõ ràng, rồi giải thích vì sao tin đồn tồn tại.',
        'Hướng khán giả đến nguồn gốc họ tự kiểm chứng được.',
        'Nhiệm vụ của ta là thông tin, không phải làm nhục người bị lừa.',
      ],
    },
  ],
};
