export const FOOD_LESSONS = {
  a1: [
    {
      title: 'Ordering at a café',
      sentences: [
        'I would like a coffee, please.',
        'Can I have a glass of water?',
        'How much is the sandwich?',
        'I will pay with cash.',
        'Thank you, the coffee is good.',
      ],
      vi: [
        'Cho tôi một ly cà phê.',
        'Cho tôi một ly nước được không?',
        'Bánh mì kẹp giá bao nhiêu?',
        'Tôi sẽ trả bằng tiền mặt.',
        'Cảm ơn, cà phê ngon.',
      ],
    },
    {
      title: 'My favourite food',
      sentences: [
        'My favourite food is pho.',
        'I like chicken and rice.',
        'I do not like very spicy food.',
        'Pizza is delicious.',
        'I eat noodles every week.',
      ],
      vi: [
        'Món tôi thích nhất là phở.',
        'Tôi thích cơm gà.',
        'Tôi không thích đồ ăn quá cay.',
        'Pizza rất ngon.',
        'Tôi ăn mì mỗi tuần.',
      ],
    },
    {
      title: 'Breakfast time',
      sentences: [
        'I eat breakfast at seven.',
        'I have bread and butter.',
        'My mother makes eggs for me.',
        'I drink milk every morning.',
        'Breakfast is important.',
      ],
      vi: [
        'Tôi ăn sáng lúc bảy giờ.',
        'Tôi ăn bánh mì và bơ.',
        'Mẹ nấu trứng cho tôi.',
        'Tôi uống sữa mỗi sáng.',
        'Bữa sáng rất quan trọng.',
      ],
    },
    {
      title: 'Fresh fruit',
      sentences: [
        'I like apples and bananas.',
        'The mango is sweet.',
        'Oranges have a lot of vitamin C.',
        'We buy fruit at the market.',
        'Fruit is good for you.',
      ],
      vi: [
        'Tôi thích táo và chuối.',
        'Xoài rất ngọt.',
        'Cam có nhiều vitamin C.',
        'Chúng tôi mua trái cây ở chợ.',
        'Trái cây tốt cho sức khỏe.',
      ],
    },
    {
      title: 'Drinks I like',
      sentences: [
        'I drink tea in the afternoon.',
        'Orange juice is my favourite drink.',
        'Water is cold and fresh.',
        'I do not drink coffee at night.',
        'A cold drink is nice in summer.',
      ],
      vi: [
        'Tôi uống trà vào buổi chiều.',
        'Nước cam là thức uống tôi thích nhất.',
        'Nước lạnh và trong lành.',
        'Tôi không uống cà phê vào buổi tối.',
        'Đồ uống lạnh rất thích vào mùa hè.',
      ],
    },
    {
      title: 'Lunch at school',
      sentences: [
        'I eat lunch at school.',
        'My lunch box has rice and vegetables.',
        'I sit with my friends.',
        'The food is warm.',
        'I am hungry at noon.',
      ],
      vi: [
        'Tôi ăn trưa ở trường.',
        'Hộp cơm của tôi có cơm và rau.',
        'Tôi ngồi cùng bạn bè.',
        'Đồ ăn còn ấm.',
        'Tôi đói vào buổi trưa.',
      ],
    },
    {
      title: 'Sweet treats',
      sentences: [
        'I like cake and ice cream.',
        'Chocolate is very sweet.',
        'My grandmother bakes cookies.',
        'We eat dessert after dinner.',
        'Too much candy is not good.',
      ],
      vi: [
        'Tôi thích bánh và kem.',
        'Sô-cô-la rất ngọt.',
        'Bà nướng bánh quy.',
        'Chúng tôi ăn tráng miệng sau bữa tối.',
        'Ăn quá nhiều kẹo không tốt.',
      ],
    },
    {
      title: 'At the bakery',
      sentences: [
        'The bakery smells very good.',
        'I buy two loaves of bread.',
        'The croissant is warm and soft.',
        'How much are the buns?',
        'Fresh bread is the best.',
      ],
      vi: [
        'Tiệm bánh mùi rất thơm.',
        'Tôi mua hai ổ bánh mì.',
        'Bánh sừng bò còn ấm và mềm.',
        'Bánh bao giá bao nhiêu?',
        'Bánh mì tươi là ngon nhất.',
      ],
    },
    {
      title: 'Hungry and thirsty',
      sentences: [
        'I am very hungry now.',
        'Can we eat soon?',
        'I am thirsty after sport.',
        'Please give me some food.',
        'A big meal makes me happy.',
      ],
      vi: [
        'Bây giờ tôi rất đói.',
        'Chúng ta ăn sớm được không?',
        'Tôi khát sau khi tập thể thao.',
        'Xin cho tôi chút đồ ăn.',
        'Bữa ăn no làm tôi vui.',
      ],
    },
    {
      title: 'Dinner with family',
      sentences: [
        'We eat dinner together every evening.',
        'My father cooks fish tonight.',
        'We have soup and rice.',
        'Please pass the salt.',
        'Dinner time is my favourite time.',
      ],
      vi: [
        'Chúng tôi ăn tối cùng nhau mỗi tối.',
        'Tối nay bố nấu cá.',
        'Chúng tôi có canh và cơm.',
        'Xin chuyền muối giúp.',
        'Giờ ăn tối là lúc tôi thích nhất.',
      ],
    },
  ],
  a2: [
    {
      title: 'Cooking a simple meal',
      sentences: [
        'I am cooking pasta for dinner tonight.',
        'First I boil water in a large pot.',
        'Then I add the pasta and wait ten minutes.',
        'I also make a tomato sauce with garlic.',
        'Cooking at home is cheaper than eating out.',
      ],
      vi: [
        'Tối nay tôi nấu mì Ý cho bữa tối.',
        'Đầu tiên tôi đun sôi nước trong nồi lớn.',
        'Sau đó tôi cho mì vào và đợi mười phút.',
        'Tôi cũng làm sốt cà chua với tỏi.',
        'Nấu ăn ở nhà rẻ hơn ăn ngoài.',
      ],
    },
    {
      title: 'At the restaurant',
      sentences: [
        'We booked a table for four people.',
        'The waiter brought us the menu.',
        'I ordered grilled chicken with salad.',
        'The dessert was chocolate cake.',
        'We asked for the bill and left a tip.',
      ],
      vi: [
        'Chúng tôi đặt bàn cho bốn người.',
        'Nhân viên phục vụ mang thực đơn cho chúng tôi.',
        'Tôi gọi gà nướng kèm salad.',
        'Món tráng miệng là bánh sô-cô-la.',
        'Chúng tôi xin hóa đơn và để tiền boa.',
      ],
    },
    {
      title: 'A family recipe',
      sentences: [
        'My grandmother taught me her soup recipe.',
        'She uses chicken, ginger, and fresh herbs.',
        'You need to simmer it for two hours.',
        'The smell fills the whole kitchen.',
        'This dish reminds me of my childhood.',
      ],
      vi: [
        'Bà dạy tôi công thức nấu canh của bà.',
        'Bà dùng gà, gừng và rau thơm tươi.',
        'Bạn cần ninh khoảng hai giờ.',
        'Mùi thơm lan khắp cả bếp.',
        'Món này nhắc tôi về tuổi thơ.',
      ],
    },
    {
      title: 'Street food adventure',
      sentences: [
        'We tried street food in the old quarter.',
        'The banh mi stall had a long queue.',
        'Everything was fresh and very tasty.',
        'Street food is cheap and full of flavour.',
        'I took photos of every dish we ate.',
      ],
      vi: [
        'Chúng tôi thử đồ ăn đường phố ở phố cổ.',
        'Quầy bánh mì có hàng dài.',
        'Mọi thứ đều tươi và rất ngon.',
        'Đồ ăn đường phố rẻ và đậm đà hương vị.',
        'Tôi chụp ảnh từng món chúng tôi ăn.',
      ],
    },
    {
      title: 'Grocery shopping',
      sentences: [
        'I made a shopping list before I left home.',
        'I bought rice, eggs, milk, and vegetables.',
        'The tomatoes were on sale this week.',
        'I compared prices at two supermarkets.',
        'Carrying heavy bags home was tiring.',
      ],
      vi: [
        'Tôi lập danh sách mua sắm trước khi ra ngoài.',
        'Tôi mua gạo, trứng, sữa và rau củ.',
        'Cà chua đang giảm giá tuần này.',
        'Tôi so sánh giá ở hai siêu thị.',
        'Xách túi nặng về nhà khá mệt.',
      ],
    },
    {
      title: 'Making a sandwich',
      sentences: [
        'I spread butter on two slices of bread.',
        'I added ham, cheese, and lettuce.',
        'A little mustard gives it more flavour.',
        'I cut the sandwich in half.',
        'It was ready in less than five minutes.',
      ],
      vi: [
        'Tôi phết bơ lên hai lát bánh mì.',
        'Tôi thêm giăm bông, phô mai và rau xà lách.',
        'Chút mù tạt làm món ngon hơn.',
        'Tôi cắt bánh mì kẹp làm đôi.',
        'Món xong trong chưa đầy năm phút.',
      ],
    },
    {
      title: 'Tea and snacks',
      sentences: [
        'We had green tea with small cakes.',
        'My aunt brought homemade biscuits.',
        'We chatted for an hour in the garden.',
        'Afternoon tea is a nice tradition.',
        'I prefer tea without too much sugar.',
      ],
      vi: [
        'Chúng tôi uống trà xanh kèm bánh nhỏ.',
        'Cô mang bánh quy tự làm đến.',
        'Chúng tôi trò chuyện một giờ trong vườn.',
        'Trà chiều là một nếp đẹp.',
        'Tôi thích trà không quá ngọt.',
      ],
    },
    {
      title: 'Picnic lunch',
      sentences: [
        'We packed sandwiches and fruit for the picnic.',
        'The park was sunny and full of families.',
        'We sat on a blanket under a big tree.',
        'Ants came near our food, so we moved.',
        'Picnics are a fun way to enjoy a meal outdoors.',
      ],
      vi: [
        'Chúng tôi chuẩn bị bánh mì kẹp và trái cây cho buổi dã ngoại.',
        'Công viên nắng đẹp và đông gia đình.',
        'Chúng tôi ngồi trên tấm thảm dưới cây to.',
        'Kiến đến gần đồ ăn nên chúng tôi chuyển chỗ.',
        'Dã ngoại là cách vui để thưởng thức bữa ăn ngoài trời.',
      ],
    },
    {
      title: 'Kitchen tools',
      sentences: [
        'A sharp knife makes cutting vegetables easier.',
        'I use a wooden spoon to stir the soup.',
        'The frying pan is too small for four steaks.',
        'We bought a new blender last month.',
        'Good tools help you cook more safely.',
      ],
      vi: [
        'Dao sắc giúp thái rau dễ hơn.',
        'Tôi dùng thìa gỗ để khuấy canh.',
        'Chảo rán hơi nhỏ cho bốn miếng bít tết.',
        'Tháng trước chúng tôi mua máy xay mới.',
        'Dụng cụ tốt giúp nấu ăn an toàn hơn.',
      ],
    },
    {
      title: 'Food from other countries',
      sentences: [
        'Last week I tried Japanese sushi for the first time.',
        'The flavours were different but very interesting.',
        'My friend recommended a Korean restaurant nearby.',
        'I want to learn how to cook Thai curry.',
        'Trying foreign food broadens your tastes.',
      ],
      vi: [
        'Tuần trước tôi lần đầu thử sushi Nhật.',
        'Hương vị khác lạ nhưng rất thú vị.',
        'Bạn tôi giới thiệu nhà hàng Hàn gần đây.',
        'Tôi muốn học nấu cà ri Thái.',
        'Thử món nước ngoài giúp mở rộng khẩu vị.',
      ],
    },
  ],
  b1: [
    {
      title: 'Eating more healthily',
      sentences: [
        'I have been trying to eat less sugar and salt.',
        'Instead of fried food, I choose grilled or steamed dishes.',
        'I read nutrition labels before I buy packaged food.',
        'Planning meals in advance stops me from snacking badly.',
        'Small changes to my diet make me feel more energetic.',
      ],
      vi: [
        'Tôi đang cố ăn ít đường và muối hơn.',
        'Thay vì đồ chiên, tôi chọn món nướng hoặc hấp.',
        'Tôi đọc bảng dinh dưỡng trước khi mua đồ đóng gói.',
        'Lên thực đơn trước giúp tôi không ăn vặt tệ.',
        'Thay đổi nhỏ trong chế độ ăn khiến tôi tràn đầy năng lượng.',
      ],
    },
    {
      title: 'Food traditions in my country',
      sentences: [
        'In Vietnam, families often share dishes from a common tray.',
        'Rice is the centre of almost every meal.',
        'During Tet, we prepare special cakes and sweets.',
        'Elders usually serve food to younger members first.',
        'These customs show respect and bring people together.',
      ],
      vi: [
        'Ở Việt Nam, gia đình thường ăn chung trên mâm.',
        'Cơm là trung tâm của hầu hết bữa ăn.',
        'Dịp Tết, chúng tôi làm bánh và mứt đặc biệt.',
        'Người lớn thường gắp mồi cho người trẻ trước.',
        'Những nếp này thể hiện sự tôn trọng và gắn kết mọi người.',
      ],
    },
    {
      title: 'Dining out opinions',
      sentences: [
        'I enjoy eating out, but restaurant prices have risen sharply.',
        'Some places serve beautiful food that tastes disappointing.',
        'I prefer small local restaurants to large chains.',
        'Good service matters as much as the quality of the food.',
        'I usually check online reviews before booking a table.',
      ],
      vi: [
        'Tôi thích ăn ngoài, nhưng giá nhà hàng đã tăng mạnh.',
        'Một số nơi bày biện đẹp nhưng vị không như mong đợi.',
        'Tôi thích quán địa phương nhỏ hơn chuỗi lớn.',
        'Phục vụ tốt quan trọng không kém chất lượng món ăn.',
        'Tôi thường xem đánh giá trực tuyến trước khi đặt bàn.',
      ],
    },
    {
      title: 'Vegetarian choices',
      sentences: [
        'My sister became vegetarian for health and environmental reasons.',
        'She cooks with tofu, lentils, and plenty of vegetables.',
        'Not every restaurant offers good meat-free options.',
        'Plant-based meals can be filling if they include protein.',
        'I respect her choice and often try her recipes.',
      ],
      vi: [
        'Chị tôi ăn chay vì lý do sức khỏe và môi trường.',
        'Chị nấu với đậu phụ, đậu lăng và nhiều rau.',
        'Không phải nhà hàng nào cũng có lựa chọn chay ngon.',
        'Bữa chay vẫn no nếu có đủ protein.',
        'Tôi tôn trọng lựa chọn của chị và hay thử món chị nấu.',
      ],
    },
    {
      title: 'Local markets',
      sentences: [
        'I visit the morning market to buy fresh produce.',
        'Vendors shout prices and invite customers to their stalls.',
        'Seasonal fruit is cheaper and tastes better at the market.',
        'I like talking to sellers about how to cook unfamiliar items.',
        'Markets reflect the daily rhythm of food culture in a city.',
      ],
      vi: [
        'Tôi ra chợ sáng mua nông sản tươi.',
        'Người bán hàng rao giá và mời khách vào quầy.',
        'Trái theo mùa ở chợ rẻ và ngon hơn.',
        'Tôi thích hỏi người bán cách nấu những thứ lạ.',
        'Chợ phản ánh nhịp sống ẩm thực hằng ngày của thành phố.',
      ],
    },
    {
      title: 'Cooking for friends',
      sentences: [
        'I invited six friends over for a home-cooked dinner.',
        'I prepared a starter, main course, and dessert.',
        'Everyone brought wine or a side dish to share.',
        'We spent the evening talking around the dining table.',
        'Hosting a meal is more personal than meeting at a café.',
      ],
      vi: [
        'Tôi mời sáu người bạn đến ăn tối tại nhà.',
        'Tôi chuẩn bị khai vị, món chính và tráng miệng.',
        'Mỗi người mang rượu hoặc món phụ để chia sẻ.',
        'Chúng tôi trò chuyện suốt buổi tối quanh bàn ăn.',
        'Mời ăn ở nhà gần gũi hơn gặp ở quán cà phê.',
      ],
    },
    {
      title: 'Fast food habits',
      sentences: [
        'Many students eat fast food when they are short on time.',
        'Burgers and fries are convenient but often high in fat.',
        'I limit fast food to once or twice a month.',
        'Some chains now offer salads and smaller portions.',
        'Convenience should not replace balanced home cooking.',
      ],
      vi: [
        'Nhiều sinh viên ăn đồ ăn nhanh khi thiếu thời gian.',
        'Burger và khoai tây chiên tiện nhưng thường nhiều chất béo.',
        'Tôi chỉ ăn đồ ăn nhanh một hoặc hai lần mỗi tháng.',
        'Một số chuỗi giờ có salad và khẩu phần nhỏ hơn.',
        'Tiện lợi không nên thay thế nấu ăn cân bằng ở nhà.',
      ],
    },
    {
      title: 'Seasonal ingredients',
      sentences: [
        'Cooking with seasonal ingredients improves flavour and value.',
        'In summer I use tomatoes, herbs, and tropical fruit.',
        'Winter soups taste better with root vegetables.',
        'Chefs often change their menus every few months.',
        'Eating seasonally connects us to the local environment.',
      ],
      vi: [
        'Nấu theo mùa giúp món ngon hơn và tiết kiệm hơn.',
        'Mùa hè tôi dùng cà chua, rau thơm và trái nhiệt đới.',
        'Canh mùa đông ngon hơn với củ quả.',
        'Đầu bếp thường đổi thực đơn vài tháng một lần.',
        'Ăn theo mùa gắn chúng ta với môi trường địa phương.',
      ],
    },
    {
      title: 'Food memories',
      sentences: [
        'The smell of grilled fish reminds me of beach holidays.',
        'My mother\'s soup tasted different every time but always comforting.',
        'Certain dishes bring back memories of family celebrations.',
        'I still try to recreate flavours from my childhood.',
        'Food memory is powerful because it links taste and emotion.',
      ],
      vi: [
        'Mùi cá nướng nhắc tôi về kỳ nghỉ biển.',
        'Canh của mẹ mỗi lần một vị nhưng luôn ấm lòng.',
        'Một số món gợi nhớ những buổi sum họp gia đình.',
        'Tôi vẫn cố tái tạo hương vị thuở nhỏ.',
        'Ký ức ẩm thực mạnh vì gắn vị giác với cảm xúc.',
      ],
    },
    {
      title: 'Sharing a meal',
      sentences: [
        'Sharing food is a simple way to build friendship.',
        'In many cultures, refusing a dish can seem impolite.',
        'I learned to try a little of everything at group dinners.',
        'Conversation flows more easily when people eat together.',
        'A shared meal turns strangers into acquaintances.',
      ],
      vi: [
        'Chia sẻ đồ ăn là cách đơn giản để kết bạn.',
        'Ở nhiều nền văn hóa, từ chối món có thể bị coi là thô lỗ.',
        'Tôi học thử chút ít mọi món trong bữa ăn chung.',
        'Trò chuyện dễ chảy hơn khi mọi người ăn cùng nhau.',
        'Bữa ăn chung biến người lạ thành người quen.',
      ],
    },
  ],
  b2: [
    {
      title: 'The food industry today',
      sentences: [
        'The global food industry is dominated by a handful of large corporations.',
        'Mass production keeps prices low but can reduce product diversity.',
        'Consumers increasingly demand transparency about ingredients and sourcing.',
        'Small producers struggle to compete with industrial supply chains.',
        'Reforming the industry requires cooperation between governments and businesses.',
      ],
      vi: [
        'Ngành thực phẩm toàn cầu do một số tập đoàn lớn chi phối.',
        'Sản xuất hàng loạt giữ giá thấp nhưng có thể làm giảm đa dạng sản phẩm.',
        'Người tiêu dùng ngày càng đòi hỏi minh bạch về nguyên liệu và nguồn gốc.',
        'Nhà sản xuất nhỏ khó cạnh tranh với chuỗi cung ứng công nghiệp.',
        'Cải cách ngành cần sự hợp tác giữa chính phủ và doanh nghiệp.',
      ],
    },
    {
      title: 'Fusion cuisine',
      sentences: [
        'Fusion cuisine blends techniques and flavours from different culinary traditions.',
        'Some critics argue that fusion dishes lack authenticity.',
        'When done well, fusion can create exciting new combinations.',
        'Chefs must understand both cultures before mixing them creatively.',
        'Popular fusion trends often spread quickly through social media.',
      ],
      vi: [
        'Ẩm thực fusion kết hợp kỹ thuật và hương vị từ nhiều truyền thống.',
        'Một số nhà phê bình cho rằng món fusion thiếu tính chân thực.',
        'Khi làm tốt, fusion có thể tạo ra sự kết hợp mới lạ.',
        'Đầu bếp cần hiểu cả hai nền văn hóa trước khi sáng tạo.',
        'Xu hướng fusion phổ biến lan nhanh qua mạng xã hội.',
      ],
    },
    {
      title: 'Reducing food waste',
      sentences: [
        'Roughly one third of food produced worldwide is wasted each year.',
        'Supermarkets sometimes discard produce that fails cosmetic standards.',
        'Households can plan portions and store leftovers more carefully.',
        'Apps now connect restaurants with charities to redistribute surplus meals.',
        'Cutting waste would ease pressure on land, water, and energy resources.',
      ],
      vi: [
        'Khoảng một phần ba lượng thực phẩm sản xuất ra bị lãng phí mỗi năm.',
        'Siêu thị đôi khi bỏ sản phẩm không đạt tiêu chuẩn thẩm mỹ.',
        'Gia đình có thể lên khẩu phần và bảo quản thức ăn thừa cẩn thận hơn.',
        'Ứng dụng giờ kết nối nhà hàng với tổ chức từ thiện để chia sẻ bữa thừa.',
        'Giảm lãng phí sẽ giảm áp lực lên đất, nước và năng lượng.',
      ],
    },
    {
      title: 'Organic farming',
      sentences: [
        'Organic farming avoids synthetic pesticides and chemical fertilisers.',
        'Products labelled organic usually command higher retail prices.',
        'Critics question whether organic methods can feed a growing population.',
        'Supporters highlight benefits for soil health and biodiversity.',
        'Certification systems help consumers trust organic claims.',
      ],
      vi: [
        'Nông nghiệp hữu cơ tránh thuốc trừ sâu và phân hóa học tổng hợp.',
        'Sản phẩm hữu cơ thường có giá bán lẻ cao hơn.',
        'Người phê bình đặt câu hỏi liệu hữu cơ có nuôi sống dân số tăng.',
        'Người ủng hộ nhấn mạnh lợi ích cho đất và đa dạng sinh học.',
        'Hệ thống chứng nhận giúp người tiêu dùng tin tưởng nhãn hữu cơ.',
      ],
    },
    {
      title: 'Food advertising',
      sentences: [
        'Food companies spend billions on advertising aimed at children.',
        'Bright packaging and cartoon characters influence young consumers.',
        'Some countries restrict junk food ads during children\'s television hours.',
        'Health campaigners call for clearer labelling of sugar and fat content.',
        'Advertising shapes not only what we buy but how we think about food.',
      ],
      vi: [
        'Công ty thực phẩm chi hàng tỷ cho quảng cáo nhắm vào trẻ em.',
        'Bao bì sặc sỡ và nhân vật hoạt hình ảnh hưởng người tiêu dùng nhỏ.',
        'Một số nước hạn chế quảng cáo đồ ăn vặt trong giờ phát sóng trẻ em.',
        'Chiến dịch sức khỏe kêu gọi ghi rõ hàm lượng đường và chất béo.',
        'Quảng cáo định hình không chỉ thứ ta mua mà cả cách ta nghĩ về thức ăn.',
      ],
    },
    {
      title: 'Michelin-star dining',
      sentences: [
        'A Michelin star signals exceptional quality in the restaurant world.',
        'Fine dining emphasises technique, presentation, and rare ingredients.',
        'Some chefs reject the pressure and cost of pursuing stars.',
        'Tasting menus can last three hours and cost hundreds of dollars.',
        'Michelin recognition can transform a small restaurant\'s reputation overnight.',
      ],
      vi: [
        'Sao Michelin là dấu hiệu chất lượng xuất sắc trong giới nhà hàng.',
        'Ẩm thực cao cấp nhấn mạnh kỹ thuật, trình bày và nguyên liệu quý.',
        'Một số đầu bếp từ chối áp lực và chi phí săn sao.',
        'Thực đơn degustation có thể kéo dài ba giờ và hàng trăm đô la.',
        'Được Michelin công nhận có thể đổi vận nhà hàng nhỏ chỉ trong một đêm.',
      ],
    },
    {
      title: 'Supply chains and shortages',
      sentences: [
        'Global supply chains connect farms, factories, and supermarkets across continents.',
        'A disruption in one region can cause shortages and price spikes elsewhere.',
        'The pandemic exposed how fragile just-in-time food logistics can be.',
        'Governments stockpile essential goods to reduce vulnerability.',
        'Building resilient supply chains may require more local sourcing.',
      ],
      vi: [
        'Chuỗi cung ứng toàn cầu nối nông trại, nhà máy và siêu thị khắp lục địa.',
        'Gián đoạn ở một vùng có thể gây thiếu hụt và tăng giá nơi khác.',
        'Đại dịch cho thấy hậu cần thực phẩm just-in-time có thể mong manh.',
        'Chính phủ dự trữ hàng thiết yếu để giảm rủi ro.',
        'Xây chuỗi cung ứng bền vững có thể cần nguồn cung địa phương hơn.',
      ],
    },
    {
      title: 'Plant-based alternatives',
      sentences: [
        'Plant-based meat substitutes have entered mainstream supermarkets.',
        'Companies use pea protein and other ingredients to mimic texture.',
        'Environmental studies suggest plant proteins often have a lower carbon footprint.',
        'Taste and price still determine whether consumers switch permanently.',
        'The rise of alternatives is reshaping menus in fast food chains.',
      ],
      vi: [
        'Thịt thực vật đã xuất hiện trên kệ siêu thị phổ biến.',
        'Các công ty dùng protein đậu Hà Lan và nguyên liệu khác để bắt chước kết cấu.',
        'Nghiên cứu môi trường cho thấy protein thực vật thường ít carbon hơn.',
        'Vị và giá vẫn quyết định người tiêu dùng có chuyển đổi lâu dài.',
        'Sự trỗi dậy của thay thế đang đổi thực đơn chuỗi đồ ăn nhanh.',
      ],
    },
    {
      title: 'Culinary tourism',
      sentences: [
        'Travellers increasingly choose destinations for their food experiences.',
        'Food tours introduce visitors to local markets, street vendors, and chefs.',
        'Culinary tourism supports small businesses and preserves traditions.',
        'Overtourism can strain popular food districts and raise prices.',
        'Authenticity becomes a selling point when cities market their cuisine.',
      ],
      vi: [
        'Du khách ngày càng chọn điểm đến vì trải nghiệm ẩm thực.',
        'Tour ẩm thực giới thiệu chợ địa phương, hàng rong và đầu bếp.',
        'Du lịch ẩm thực hỗ trợ hộ kinh doanh nhỏ và bảo tồn truyền thống.',
        'Du lịch quá tải có thể làm căng khu ẩm thực nổi tiếng và đẩy giá.',
        'Tính chân thực trở thành điểm bán khi thành phố quảng bá ẩm thực.',
      ],
    },
    {
      title: 'Food and identity',
      sentences: [
        'The dishes we grow up with often shape our sense of cultural identity.',
        'Immigrant communities maintain heritage through recipes and rituals.',
        'Food can become a battlefield in debates about assimilation and belonging.',
        'Fusion restaurants sometimes reflect hybrid identities in multicultural cities.',
        'Sharing traditional food is a way to pass history from one generation to the next.',
      ],
      vi: [
        'Món ăn thuở nhỏ thường định hình bản sắc văn hóa của ta.',
        'Cộng đồng nhập cư giữ di sản qua công thức và nghi lễ.',
        'Thức ăn đôi khi thành chiến trường trong tranh luận hòa nhập và thuộc về.',
        'Nhà hàng fusion đôi khi phản ánh bản sắc lai ở thành phố đa văn hóa.',
        'Chia sẻ món truyền thống là cách truyền lịch sử qua các thế hệ.',
      ],
    },
  ],
  c1: [
    {
      title: 'The art of gastronomy',
      sentences: [
        'Gastronomy treats cooking as a form of cultural expression rather than mere sustenance.',
        'Renowned chefs draw on history, science, and aesthetics to craft memorable experiences.',
        'The discipline examines how terroir, technique, and narrative converge on the plate.',
        'Critics debate whether avant-garde presentations enhance or obscure flavour.',
        'Ultimately, gastronomy invites diners to reflect on the meaning behind what they consume.',
      ],
      vi: [
        'Ẩm thực học coi nấu ăn là biểu hiện văn hóa, không chỉ để nuôi sống.',
        'Đầu bếp danh tiếng kết hợp lịch sử, khoa học và thẩm mỹ để tạo trải nghiệm khó quên.',
        'Ngành này xem xét cách terroir, kỹ thuật và câu chuyện hội tụ trên đĩa ăn.',
        'Nhà phê bình tranh luận liệu trình bày tiên phong làm tăng hay che lấp hương vị.',
        'Cuối cùng, ẩm thực học mời thực khách suy ngẫm ý nghĩa đằng sau thứ họ ăn.',
      ],
    },
    {
      title: 'Food ethics in practice',
      sentences: [
        'Ethical eating requires weighing animal welfare, labour conditions, and environmental impact.',
        'Fair-trade certification aims to ensure producers receive a living wage.',
        'Consumers face dilemmas when affordable food depends on exploitative supply chains.',
        'Philosophers argue that moral responsibility extends beyond individual choice to systemic reform.',
        'Transparent sourcing has become a benchmark for restaurants claiming ethical credentials.',
      ],
      vi: [
        'Ăn uống có đạo đức đòi hỏi cân nhắc phúc lợi động vật, lao động và môi trường.',
        'Chứng nhận fair-trade nhằm đảm bảo người sản xuất được mức sống đủ sống.',
        'Người tiêu dùng bối rối khi thực phẩm rẻ phụ thuộc chuỗi cung khai thác.',
        'Triết gia cho rằng trách nhiệm đạo đức vượt ra ngoài lựa chọn cá nhân.',
        'Minh bạch nguồn gốc trở thành chuẩn mực cho nhà hàng tuyên bố đạo đức.',
      ],
    },
    {
      title: 'Global food systems',
      sentences: [
        'Contemporary food systems integrate agriculture, processing, distribution, and retail on a planetary scale.',
        'Concentration of market power among agribusiness firms raises concerns about equity and resilience.',
        'Climate change threatens crop yields in regions already facing food insecurity.',
        'Policy analysts advocate diversified production to reduce dependence on monocultures.',
        'Transforming food systems demands coordinated action across borders and sectors.',
      ],
      vi: [
        'Hệ thống thực phẩm hiện đại tích hợp nông nghiệp, chế biến, phân phối và bán lẻ toàn cầu.',
        'Tập trung quyền lực ở các tập đoàn nông nghiệp gây lo ngại về công bằng và bền vững.',
        'Biến đổi khí hậu đe dọa năng suất ở vùng đã thiếu an ninh lương thực.',
        'Nhà phân tích chính sách ủng hộ sản xuất đa dạng, giảm phụ thuộc monoculture.',
        'Chuyển đổi hệ thống thực phẩm cần hành động phối hợp xuyên biên giới và ngành.',
      ],
    },
    {
      title: 'Molecular cuisine',
      sentences: [
        'Molecular gastronomy applies scientific principles to deconstruct and reimagine familiar dishes.',
        'Techniques such as spherification and foam creation challenge conventional textures.',
        'Proponents view the movement as an intellectual extension of culinary craft.',
        'Detractors dismiss it as gimmickry that prioritises spectacle over nourishment.',
        'Regardless of opinion, molecular cuisine has influenced how chefs experiment in kitchens worldwide.',
      ],
      vi: [
        'Ẩm thực phân tử áp dụng nguyên lý khoa học để phân tích và tái hiện món quen thuộc.',
        'Kỹ thuật như spherification và tạo bọt thách thức kết cấu truyền thống.',
        'Người ủng hộ coi đây là mở rộng trí tuệ của nghề đầu bếp.',
        'Người phản đối cho là mẹo vặt ưu tiên hình thức hơn dinh dưỡng.',
        'Dù ý kiến ra sao, ẩm thực phân tử đã ảnh hưởng cách đầu bếp thử nghiệm toàn cầu.',
      ],
    },
    {
      title: 'Terroir and tradition',
      sentences: [
        'The concept of terroir links flavour to soil, climate, and regional farming practices.',
        'Protected designations safeguard products such as wine, cheese, and olive oil from imitation.',
        'Globalisation has both threatened and revitalised artisanal food traditions.',
        'Anthropologists study how communities defend culinary heritage against homogenisation.',
        'Terroir remains a contested idea when ingredients travel far from their place of origin.',
      ],
      vi: [
        'Khái niệm terroir gắn hương vị với đất, khí hậu và cách canh tác địa phương.',
        'Chỉ dẫn địa lý bảo vệ rượu, phô mai, dầu ô liu khỏi bị bắt chước.',
        'Toàn cầu hóa vừa đe dọa vừa hồi sinh truyền thống thủ công.',
        'Nhà nhân học nghiên cứu cách cộng đồng bảo vệ di sản ẩm thực khỏi đồng nhất hóa.',
        'Terroir vẫn gây tranh cãi khi nguyên liệu đi xa nơi xuất xứ.',
      ],
    },
    {
      title: 'Food sovereignty',
      sentences: [
        'Food sovereignty asserts the right of peoples to define their own agricultural policies.',
        'The movement challenges the dominance of export-oriented industrial agriculture.',
        'Smallholder farmers argue that seed patents undermine local autonomy.',
        'International forums have increasingly recognised food sovereignty in policy debates.',
        'Achieving it requires land reform, market access, and respect for indigenous knowledge.',
      ],
      vi: [
        'Chủ quyền lương thực khẳng định quyền của nhân dân tự định chính sách nông nghiệp.',
        'Phong trào thách thức thống trị của nông nghiệp công nghiệp hướng xuất khẩu.',
        'Nông dân nhỏ cho rằng bằng sáng chế hạt giống làm suy yếu tự chủ địa phương.',
        'Diễn đàn quốc tế ngày càng công nhận chủ quyền lương thực trong tranh luận chính sách.',
        'Đạt được điều đó cần cải cách đất đai, tiếp cận thị trường và tôn trọng tri thức bản địa.',
      ],
    },
    {
      title: 'The politics of hunger',
      sentences: [
        'Hunger persists not because of global food scarcity but because of unequal distribution.',
        'Conflict, corruption, and infrastructure deficits exacerbate famine in vulnerable regions.',
        'Food aid can save lives yet sometimes disrupt local markets and farming incentives.',
        'Scholars analyse hunger as a political failure rather than a purely technical problem.',
        'Sustainable solutions must address power structures that exclude marginalised populations.',
      ],
      vi: [
        'Đói kém tồn tại không vì thiếu lương thực toàn cầu mà vì phân phối bất bình đẳng.',
        'Xung đột, tham nhũng và hạ tầng yếu làm trầm trọng nạn đói ở vùng dễ tổn thương.',
        'Viện trợ lương thực cứu mạng nhưng đôi khi phá thị trường và động lực sản xuất địa phương.',
        'Học giả phân tích đói như thất bại chính trị, không chỉ vấn đề kỹ thuật.',
        'Giải pháp bền vững phải đối diện cấu trúc quyền lực loại trừ nhóm yếu thế.',
      ],
    },
    {
      title: 'Sustainable aquaculture',
      sentences: [
        'Aquaculture now supplies more than half of the seafood consumed globally.',
        'Intensive fish farming raises concerns about pollution, disease, and feed sustainability.',
        'Innovations in recirculating systems and alternative feeds aim to reduce environmental harm.',
        'Certification schemes help consumers identify responsibly farmed seafood.',
        'Balancing nutritional demand with ecological limits remains a central challenge.',
      ],
      vi: [
        'Nuôi trồng thủy sản giờ cung cấp hơn một nửa hải sản tiêu thụ toàn cầu.',
        'Nuôi cá quy mô lớn gây lo ngại ô nhiễm, dịch bệnh và thức ăn bền vững.',
        'Đổi mới hệ thống tuần hoàn và thức ăn thay thế nhằm giảm tác hại môi trường.',
        'Chứng nhận giúp người tiêu dùng nhận diện hải sản nuôi có trách nhiệm.',
        'Cân bằng nhu cầu dinh dưỡng với giới hạn sinh thái vẫn là thách thức trung tâm.',
      ],
    },
    {
      title: 'Gastronomic heritage',
      sentences: [
        'UNESCO recognition of intangible gastronomic heritage elevates cooking to cultural patrimony.',
        'Communities submit nominations that document rituals, recipes, and communal meals.',
        'Heritage status can boost tourism but risks commodifying traditions.',
        'Younger generations may abandon labour-intensive practices unless incentives exist.',
        'Preserving gastronomic heritage requires balancing authenticity with adaptation.',
      ],
      vi: [
        'UNESCO công nhận di sản ẩm thực phi vật thể nâng nấu ăn thành di sản văn hóa.',
        'Cộng đồng nộp hồ sơ ghi lại nghi lễ, công thức và bữa ăn chung.',
        'Di sản có thể thúc đẩy du lịch nhưng nguy cơ thương mại hóa truyền thống.',
        'Thế hệ trẻ có thể bỏ tập quán lao động nặng nếu thiếu động lực.',
        'Bảo tồn di sản ẩm thực cần cân bằng chân thực với thích ứng.',
      ],
    },
    {
      title: 'Future of food technology',
      sentences: [
        'Cell-cultured meat and precision fermentation promise protein without conventional livestock.',
        'Vertical farms use controlled environments to grow crops in urban spaces year-round.',
        'Proponents claim technology can decouple food production from land degradation.',
        'Sceptics warn that corporate control of novel foods could replicate existing inequalities.',
        'The trajectory of food technology will shape diets, economies, and ecosystems for decades.',
      ],
      vi: [
        'Thịt nuôi cấy và lên men chính xác hứa hẹn protein không cần chăn nuôi truyền thống.',
        'Nông trại thẳng đứng dùng môi trường kiểm soát để trồng quanh năm trong đô thị.',
        'Người ủng hộ cho rằng công nghệ có thể tách sản xuất thực phẩm khỏi suy thoái đất.',
        'Người hoài nghi cảnh báo tập đoàn kiểm soát thực phẩm mới có thể tái hiện bất bình đẳng.',
        'Hướng đi công nghệ thực phẩm sẽ định hình chế độ ăn, kinh tế và hệ sinh thái trong nhiều thập kỷ.',
      ],
    },
  ],
};
