/** Sports & Fitness (Thể thao) — extra topic lessons */
export const SPORTS_LESSONS = {
  a1: [
    {
      title: 'Playing football at school',
      sentences: [
        'We play football in PE class.',
        'The ball is round and white.',
        'I kick the ball to my friend.',
        'Our team scores one goal.',
        'Football is fun and exciting.',
      ],
      vi: [
        'Chúng tôi chơi bóng đá trong giờ thể dục.',
        'Quả bóng tròn và màu trắng.',
        'Tôi đá bóng cho bạn tôi.',
        'Đội chúng tôi ghi được một bàn.',
        'Bóng đá vui và hấp dẫn.',
      ],
    },
    {
      title: 'Football with friends',
      sentences: [
        'My friends and I play football after school.',
        'We wear sports shoes and shorts.',
        'The goalkeeper stops the ball.',
        'We run fast on the grass field.',
        'Everyone is happy when we play.',
      ],
      vi: [
        'Tôi và bạn bè chơi bóng đá sau giờ học.',
        'Chúng tôi mang giày thể thao và quần đùi.',
        'Thủ môn cản bóng.',
        'Chúng tôi chạy nhanh trên sân cỏ.',
        'Mọi người đều vui khi chơi.',
      ],
    },
    {
      title: 'Learning to swim',
      sentences: [
        'I go to swimming class on Saturday.',
        'The teacher shows me how to float.',
        'I hold my breath under the water.',
        'I move my arms and kick my legs.',
        'Swimming makes me feel strong.',
      ],
      vi: [
        'Tôi đi học bơi vào thứ Bảy.',
        'Giáo viên chỉ tôi cách nổi trên nước.',
        'Tôi nín thở dưới nước.',
        'Tôi vẫy tay và đạp chân.',
        'Bơi lội giúp tôi cảm thấy khỏe mạnh.',
      ],
    },
    {
      title: 'At the swimming pool',
      sentences: [
        'The swimming pool is big and clean.',
        'I wear a swimsuit and a cap.',
        'The water is cool and blue.',
        'I swim five laps every day.',
        'I dry myself with a towel after swimming.',
      ],
      vi: [
        'Hồ bơi rộng và sạch sẽ.',
        'Tôi mặc đồ bơi và đội mũ bơi.',
        'Nước mát và màu xanh.',
        'Tôi bơi năm vòng mỗi ngày.',
        'Tôi lau khô người bằng khăn sau khi bơi.',
      ],
    },
    {
      title: 'My favourite sport',
      sentences: [
        'My favourite sport is badminton.',
        'I play it with my sister every weekend.',
        'We use a racket and a shuttlecock.',
        'Badminton is fast and easy to learn.',
        'I want to play in a competition one day.',
      ],
      vi: [
        'Môn thể thao yêu thích của tôi là cầu lông.',
        'Tôi chơi cùng chị gái mỗi cuối tuần.',
        'Chúng tôi dùng vợt và quả cầu lông.',
        'Cầu lông nhanh và dễ học.',
        'Một ngày nào đó tôi muốn thi đấu.',
      ],
    },
    {
      title: 'Talking about sports',
      sentences: [
        'What sport do you like?',
        'I like running because it is simple.',
        'My brother likes table tennis.',
        'We watch sports on TV together.',
        'Sports help us stay healthy.',
      ],
      vi: [
        'Bạn thích môn thể thao nào?',
        'Tôi thích chạy bộ vì nó đơn giản.',
        'Anh trai tôi thích bóng bàn.',
        'Chúng tôi cùng xem thể thao trên TV.',
        'Thể thao giúp chúng ta khỏe mạnh.',
      ],
    },
    {
      title: 'Playing in the playground',
      sentences: [
        'Children play in the school playground.',
        'There is a slide and a swing.',
        'We run and jump on the soft ground.',
        'The playground is safe for young kids.',
        'We have fun during break time.',
      ],
      vi: [
        'Trẻ em chơi ở sân chơi trường học.',
        'Có cầu trượt và xích đu.',
        'Chúng tôi chạy và nhảy trên mặt đất mềm.',
        'Sân chơi an toàn cho trẻ nhỏ.',
        'Chúng tôi vui vẻ trong giờ ra chơi.',
      ],
    },
    {
      title: 'Games at the playground',
      sentences: [
        'We play tag in the playground.',
        'One person runs and others chase.',
        'We also play hopscotch on the ground.',
        'The teacher watches us carefully.',
        'Everyone laughs and enjoys the games.',
      ],
      vi: [
        'Chúng tôi chơi trò đuổi bắt ở sân chơi.',
        'Một người chạy và những người khác đuổi theo.',
        'Chúng tôi cũng chơi nhảy ô ở mặt đất.',
        'Giáo viên quan sát chúng tôi cẩn thận.',
        'Mọi người cười và thích các trò chơi.',
      ],
    },
    {
      title: 'Morning exercise',
      sentences: [
        'I do exercise every morning.',
        'I stretch my arms and legs first.',
        'Then I jog for ten minutes.',
        'Exercise wakes up my body.',
        'I feel ready for school after exercise.',
      ],
      vi: [
        'Tôi tập thể dục mỗi sáng.',
        'Tôi duỗi tay và chân trước.',
        'Sau đó tôi chạy bộ mười phút.',
        'Tập thể dục đánh thức cơ thể tôi.',
        'Sau khi tập tôi cảm thấy sẵn sàng đi học.',
      ],
    },
    {
      title: 'Staying active',
      sentences: [
        'It is important to move your body every day.',
        'Walking is good exercise for everyone.',
        'I ride my bike to the park.',
        'Playing sports is better than sitting all day.',
        'A healthy body needs regular activity.',
      ],
      vi: [
        'Vận động cơ thể mỗi ngày rất quan trọng.',
        'Đi bộ là bài tập tốt cho mọi người.',
        'Tôi đạp xe đến công viên.',
        'Chơi thể thao tốt hơn ngồi cả ngày.',
        'Cơ thể khỏe mạnh cần hoạt động thường xuyên.',
      ],
    },
  ],

  a2: [
    {
      title: 'First day at the gym',
      sentences: [
        'I joined a gym near my house last week.',
        'A trainer showed me how to use the machines.',
        'I started with light weights and warm-up exercises.',
        'The gym has treadmills, bikes, and free weights.',
        'I felt tired but proud after my first workout.',
      ],
      vi: [
        'Tuần trước tôi gia nhập phòng gym gần nhà.',
        'Huấn luyện viên chỉ tôi cách dùng máy tập.',
        'Tôi bắt đầu với tạ nhẹ và bài khởi động.',
        'Phòng gym có máy chạy bộ, xe đạp và tạ tự do.',
        'Sau buổi tập đầu tiên tôi mệt nhưng tự hào.',
      ],
    },
    {
      title: 'Gym routine',
      sentences: [
        'I go to the gym three times a week.',
        'On Monday I work on my arms and chest.',
        'I always stretch before and after training.',
        'Drinking water during exercise is very important.',
        'My muscles ache the day after a hard session.',
      ],
      vi: [
        'Tôi đi gym ba lần một tuần.',
        'Thứ Hai tôi tập tay và ngực.',
        'Tôi luôn giãn cơ trước và sau khi tập.',
        'Uống nước khi tập rất quan trọng.',
        'Cơ nhức vào ngày sau buổi tập nặng.',
      ],
    },
    {
      title: 'Joining a basketball team',
      sentences: [
        'Our school has a basketball team for students.',
        'I tried out and got a place on the team.',
        'We practice twice a week after classes.',
        'The coach teaches us passing and shooting skills.',
        'Playing on a team teaches me to cooperate with others.',
      ],
      vi: [
        'Trường chúng tôi có đội bóng rổ cho học sinh.',
        'Tôi thi tuyển và được vào đội.',
        'Chúng tôi tập hai lần một tuần sau giờ học.',
        'Huấn luyện viên dạy kỹ năng chuyền và ném bóng.',
        'Chơi trong đội dạy tôi hợp tác với người khác.',
      ],
    },
    {
      title: 'Team practice',
      sentences: [
        'At practice we run drills across the court.',
        'The captain leads the warm-up at the start.',
        'We review our strategy before each match.',
        'Everyone must arrive on time for practice.',
        'Team spirit grows stronger when we train together.',
      ],
      vi: [
        'Khi tập chúng tôi chạy các bài trên sân.',
        'Đội trưởng dẫn bài khởi động lúc đầu.',
        'Chúng tôi xem lại chiến thuật trước mỗi trận.',
        'Mọi người phải đến đúng giờ tập.',
        'Tinh thần đồng đội mạnh hơn khi tập cùng nhau.',
      ],
    },
    {
      title: 'Watching the Olympics',
      sentences: [
        'The Olympic Games happen every four years.',
        'Athletes from many countries compete for medals.',
        'My family watches the opening ceremony on TV.',
        'I cheered for our national swimming team.',
        'The Olympics inspire people to try new sports.',
      ],
      vi: [
        'Thế vận hội Olympic diễn ra bốn năm một lần.',
        'Vận động viên nhiều nước tranh huy chương.',
        'Gia đình tôi xem lễ khai mạc trên TV.',
        'Tôi cổ vũ cho đội bơi quốc gia của chúng tôi.',
        'Olympic truyền cảm hứng cho mọi người thử môn mới.',
      ],
    },
    {
      title: 'Olympic sports',
      sentences: [
        'There are summer and winter Olympic Games.',
        'Popular sports include athletics, gymnastics, and diving.',
        'Each athlete trains for years to reach the Olympics.',
        'Winning a gold medal is a dream for many.',
        'The Olympic flag has five coloured rings.',
      ],
      vi: [
        'Có Thế vận hội mùa hè và mùa đông.',
        'Các môn phổ biến gồm điền kinh, thể dục và nhảy cầu.',
        'Mỗi vận động viên tập nhiều năm để tới Olympic.',
        'Giành huy chương vàng là ước mơ của nhiều người.',
        'Cờ Olympic có năm vòng tròn nhiều màu.',
      ],
    },
    {
      title: 'Watching football on TV',
      sentences: [
        'I watch live football matches on weekends.',
        'My friends and I support the same team.',
        'We shout when our team scores a goal.',
        'The commentator explains what is happening on the field.',
        'Watching sports on TV is exciting even at home.',
      ],
      vi: [
        'Cuối tuần tôi xem bóng đá trực tiếp.',
        'Tôi và bạn bè cùng ủng hộ một đội.',
        'Chúng tôi hò hét khi đội mình ghi bàn.',
        'Bình luận viên giải thích diễn biến trên sân.',
        'Xem thể thao trên TV vẫn rất hấp dẫn ở nhà.',
      ],
    },
    {
      title: 'At the stadium',
      sentences: [
        'Last month I went to a stadium for the first time.',
        'Thousands of fans wore team colours and sang songs.',
        'The atmosphere was loud and full of energy.',
        'I bought a snack and a drink at half time.',
        'Seeing a match in person was an amazing experience.',
      ],
      vi: [
        'Tháng trước tôi lần đầu đến sân vận động.',
        'Hàng nghìn cổ động viên mặc màu đội và hát.',
        'Không khí ồn ào và tràn đầy năng lượng.',
        'Tôi mua đồ ăn nhẹ và nước trong giờ nghỉ.',
        'Xem trận đấu trực tiếp là trải nghiệm tuyệt vời.',
      ],
    },
    {
      title: 'A twisted ankle',
      sentences: [
        'I twisted my ankle during a football match.',
        'It hurt a lot and I could not walk properly.',
        'My coach told me to sit down and rest.',
        'I put ice on my ankle to reduce the swelling.',
        'The doctor said I should not play for two weeks.',
      ],
      vi: [
        'Tôi bị bong gân mắt cá chân khi đá bóng.',
        'Đau nhiều và tôi không đi bình thường được.',
        'Huấn luyện viên bảo tôi ngồi xuống nghỉ.',
        'Tôi chườm đá lên mắt cá chân để giảm sưng.',
        'Bác sĩ bảo tôi không nên chơi trong hai tuần.',
      ],
    },
    {
      title: 'Rest and recovery',
      sentences: [
        'Rest is important when you have a sports injury.',
        'I used a bandage to support my sore knee.',
        'Physiotherapy helped me regain strength in my leg.',
        'I started with gentle exercises before returning to sport.',
        'Ignoring an injury can make the problem much worse.',
      ],
      vi: [
        'Nghỉ ngơi quan trọng khi bị chấn thương thể thao.',
        'Tôi băng đầu gối đau để hỗ trợ.',
        'Vật lý trị liệu giúp tôi lấy lại sức chân.',
        'Tôi bắt đầu với bài tập nhẹ trước khi quay lại thi đấu.',
        'Bỏ qua chấn thương có thể khiến vấn đề tệ hơn nhiều.',
      ],
    },
  ],

  b1: [
    {
      title: 'Setting fitness goals',
      sentences: [
        'I decided to set clear fitness goals for this year.',
        'My main goal is to run five kilometres without stopping.',
        'I wrote my goals down and put them on my wall.',
        'Realistic goals are easier to achieve than impossible ones.',
        'Having a target keeps me focused during difficult weeks.',
      ],
      vi: [
        'Tôi quyết định đặt mục tiêu thể lực rõ ràng cho năm nay.',
        'Mục tiêu chính là chạy năm cây số không dừng.',
        'Tôi viết mục tiêu ra giấy và dán lên tường.',
        'Mục tiêu thực tế dễ đạt hơn mục tiêu không thể.',
        'Có mục tiêu giúp tôi tập trung trong những tuần khó.',
      ],
    },
    {
      title: 'Training plan',
      sentences: [
        'I follow a training plan that increases distance slowly.',
        'On rest days I do light stretching or yoga.',
        'My plan includes strength training twice a week.',
        'I adjust the plan when I feel pain or fatigue.',
        'A structured plan prevents overtraining and burnout.',
      ],
      vi: [
        'Tôi theo kế hoạch tập tăng quãng đường từ từ.',
        'Ngày nghỉ tôi giãn cơ nhẹ hoặc tập yoga.',
        'Kế hoạch có tập sức mạnh hai lần một tuần.',
        'Tôi điều chỉnh kế hoạch khi đau hoặc mệt.',
        'Kế hoạch có cấu trúc tránh tập quá sức và kiệt sức.',
      ],
    },
    {
      title: 'Tracking progress',
      sentences: [
        'I use a fitness app to track my daily steps and workouts.',
        'Seeing my progress on a chart motivates me to continue.',
        'I take measurements of my weight and body every month.',
        'Sometimes progress is slow, but small improvements still count.',
        'Celebrating milestones helps me stay committed to my goals.',
      ],
      vi: [
        'Tôi dùng ứng dụng thể dục theo dõi bước chân và buổi tập.',
        'Nhìn tiến bộ trên biểu đồ thúc đẩy tôi tiếp tục.',
        'Tôi đo cân nặng và cơ thể mỗi tháng.',
        'Đôi khi tiến bộ chậm, nhưng cải thiện nhỏ vẫn có giá trị.',
        'Ăn mừng cột mốc giúp tôi gắn bó với mục tiêu.',
      ],
    },
    {
      title: 'Joining a sports club',
      sentences: [
        'I joined a local tennis club to meet people who share my interest.',
        'The club offers lessons for beginners and advanced players.',
        'Members can book courts online through the club website.',
        'There are social events where members play friendly matches.',
        'Being part of a club makes sport more enjoyable and regular.',
      ],
      vi: [
        'Tôi gia nhập câu lạc bộ tennis địa phương để gặp người cùng sở thích.',
        'Câu lạc bộ có lớp cho người mới và người chơi nâng cao.',
        'Hội viên đặt sân trực tuyến qua trang web câu lạc bộ.',
        'Có sự kiện giao lưu để hội viên đấu giao hữu.',
        'Là thành viên câu lạc bộ giúp thể thao vui và đều đặn hơn.',
      ],
    },
    {
      title: 'Club membership',
      sentences: [
        'The annual membership fee covers access to all facilities.',
        'Students receive a discount on club registration.',
        'Members must follow the club rules and dress code on court.',
        'I renewed my membership because the facilities are excellent.',
        'Sports clubs create a sense of community among active people.',
      ],
      vi: [
        'Phí hội viên hàng năm bao gồm dùng mọi cơ sở.',
        'Sinh viên được giảm giá khi đăng ký câu lạc bộ.',
        'Hội viên phải tuân thủ nội quy và trang phục trên sân.',
        'Tôi gia hạn hội viên vì cơ sở rất tốt.',
        'Câu lạc bộ thể thao tạo cộng đồng cho người năng động.',
      ],
    },
    {
      title: 'Hiking on weekends',
      sentences: [
        'Every weekend my friends and I go hiking in the mountains.',
        'We pack water, snacks, and a first-aid kit in our backpacks.',
        'Hiking gives us fresh air and beautiful views of nature.',
        'We choose trails that match our fitness level.',
        'Outdoor activities like hiking reduce stress and improve mood.',
      ],
      vi: [
        'Mỗi cuối tuần tôi và bạn đi leo núi.',
        'Chúng tôi mang nước, đồ ăn nhẹ và túi sơ cứu trong ba lô.',
        'Leo núi cho không khí trong lành và cảnh thiên nhiên đẹp.',
        'Chúng tôi chọn đường mòn phù hợp thể lực.',
        'Hoạt động ngoài trời như leo núi giảm căng thẳng và cải thiện tâm trạng.',
      ],
    },
    {
      title: 'Cycling in the park',
      sentences: [
        'Cycling is my favourite way to explore the city.',
        'I ride along the river path through the large city park.',
        'Wearing a helmet protects me in case of an accident.',
        'I check my brakes and tyres before every long ride.',
        'Cycling is eco-friendly and good for cardiovascular health.',
      ],
      vi: [
        'Đạp xe là cách yêu thích để khám phá thành phố.',
        'Tôi đi dọc lối ven sông qua công viên lớn.',
        'Đội mũ bảo hiểm bảo vệ tôi khi tai nạn.',
        'Tôi kiểm tra phanh và lốp trước mỗi chuyến đi dài.',
        'Đạp xe thân thiện môi trường và tốt cho tim mạch.',
      ],
    },
    {
      title: 'Outdoor adventure',
      sentences: [
        'Last summer we tried rock climbing for the first time.',
        'A professional guide taught us safety techniques on the cliff.',
        'Outdoor sports challenge both the body and the mind.',
        'We learned to trust our equipment and our partners.',
        'Trying new outdoor activities builds confidence and resilience.',
      ],
      vi: [
        'Hè ngoái chúng tôi lần đầu thử leo núi đá.',
        'Hướng dẫn viên chuyên nghiệp dạy kỹ thuật an toàn trên vách.',
        'Thể thao ngoài trời thử thách cả thể chất và tinh thần.',
        'Chúng tôi học tin tưởng thiết bị và đồng đội.',
        'Thử hoạt động ngoài trời mới xây dựng tự tin và sức bền.',
      ],
    },
    {
      title: 'Staying motivated',
      sentences: [
        'It is normal to lose motivation when results come slowly.',
        'I remind myself why I started exercising in the first place.',
        'Working out with a partner makes me less likely to skip sessions.',
        'I reward myself with a healthy treat after reaching a goal.',
        'Variety in my routine prevents boredom and keeps me engaged.',
      ],
      vi: [
        'Mất động lực khi kết quả chậm là điều bình thường.',
        'Tôi nhắc mình vì sao ban đầu bắt đầu tập luyện.',
        'Tập cùng bạn khiến tôi ít bỏ buổi tập hơn.',
        'Tôi tự thưởng món lành mạnh khi đạt mục tiêu.',
        'Đa dạng lịch tập tránh nhàm chán và giữ hứng thú.',
      ],
    },
    {
      title: 'Overcoming setbacks',
      sentences: [
        'I missed two weeks of training because of a busy work schedule.',
        'Instead of giving up, I restarted with shorter, easier sessions.',
        'Setbacks are part of any fitness journey, not a reason to quit.',
        'I talked to my coach about adjusting my expectations.',
        'Persistence matters more than perfection in long-term fitness.',
      ],
      vi: [
        'Tôi bỏ lỡ hai tuần tập vì lịch làm việc bận.',
        'Thay vì bỏ cuộc, tôi bắt đầu lại với buổi tập ngắn và nhẹ hơn.',
        'Thất bại là phần của hành trình thể lực, không phải lý do bỏ cuộc.',
        'Tôi trao đổi với huấn luyện viên về điều chỉnh kỳ vọng.',
        'Kiên trì quan trọng hơn hoàn hảo trong thể lực dài hạn.',
      ],
    },
  ],

  b2: [
    {
      title: 'Life of a pro athlete',
      sentences: [
        'Professional athletes follow strict daily schedules year round.',
        'Their diet, sleep, and training are carefully monitored by coaches.',
        'Media attention and public expectations add pressure beyond competition.',
        'Many athletes sacrifice personal time and education for their careers.',
        'The lifestyle demands extraordinary discipline and mental toughness.',
      ],
      vi: [
        'Vận động viên chuyên nghiệp theo lịch sinh hoạt nghiêm ngặt quanh năm.',
        'Chế độ ăn, giấc ngủ và tập luyện được huấn luyện viên theo dõi kỹ.',
        'Sự chú ý của truyền thông và kỳ vọng công chúng tạo áp lực ngoài thi đấu.',
        'Nhiều vận động viên hy sinh thời gian cá nhân và học vấn vì sự nghiệp.',
        'Lối sống đòi hỏi kỷ luật và sức mạnh tinh thần phi thường.',
      ],
    },
    {
      title: 'Athlete contracts',
      sentences: [
        'Top players sign multi-million-dollar contracts with their clubs.',
        'Contracts often include performance bonuses and image rights clauses.',
        'Injuries can affect both playing time and future earning potential.',
        'Agents negotiate deals on behalf of athletes with teams and sponsors.',
        'Contract disputes sometimes end up in court or arbitration.',
      ],
      vi: [
        'Cầu thủ hàng đầu ký hợp đồng hàng triệu đô với câu lạc bộ.',
        'Hợp đồng thường có thưởng thành tích và điều khoản quyền hình ảnh.',
        'Chấn thương ảnh hưởng thời gian thi đấu và thu nhập tương lai.',
        'Đại diện đàm phán thay vận động viên với đội và nhà tài trợ.',
        'Tranh chấp hợp đồng đôi khi ra tòa hoặc trọng tài.',
      ],
    },
    {
      title: 'Retirement from sport',
      sentences: [
        'Most athletes retire in their thirties due to physical decline.',
        'Planning for life after sport is a challenge many fail to address early.',
        'Some transition into coaching, commentary, or business ventures.',
        'Mental health issues can arise when identity is tied to athletic success.',
        'Retirement programmes offered by federations help athletes adapt.',
      ],
      vi: [
        'Hầu hết vận động viên giải nghệ ở tuổi ba mươi do suy giảm thể lực.',
        'Lập kế hoạch sau sự nghiệp là thách thức nhiều người không chuẩn bị sớm.',
        'Một số chuyển sang huấn luyện, bình luận hoặc kinh doanh.',
        'Vấn đề sức khỏe tinh thần có thể xuất hiện khi bản sắc gắn với thành công thể thao.',
        'Chương trình hỗ trợ giải nghệ của liên đoàn giúp vận động viên thích nghi.',
      ],
    },
    {
      title: 'Doping in sport',
      sentences: [
        'Doping refers to the use of banned substances to enhance performance.',
        'Scandals have damaged the reputations of entire sports and nations.',
        'Some athletes claim they were unaware that supplements contained banned drugs.',
        'The pressure to win at elite level can tempt competitors to cheat.',
        'Public trust in fair competition depends on effective anti-doping measures.',
      ],
      vi: [
        'Doping là dùng chất cấm để nâng cao thành tích.',
        'Bê bối đã làm tổn hại danh tiếng cả môn thể thao và quốc gia.',
        'Một số vận động viên cho rằng họ không biết thực phẩm bổ sung có chất cấm.',
        'Áp lực thắng ở đỉnh cao có thể khiến vận động viên gian lận.',
        'Niềm tin công chúng vào thi đấu công bằng phụ thuộc biện pháp chống doping hiệu quả.',
      ],
    },
    {
      title: 'Anti-doping rules',
      sentences: [
        'Athletes must submit to random drug testing during and between competitions.',
        'The World Anti-Doping Agency maintains a list of prohibited substances.',
        'A positive test can result in suspensions, fines, and stripped medals.',
        'Therapeutic use exemptions allow certain medications under strict conditions.',
        'Education programmes aim to prevent accidental violations among young athletes.',
      ],
      vi: [
        'Vận động viên phải xét nghiệm ma túy ngẫu nhiên trong và ngoài giải.',
        'Cơ quan chống doping thế giới duy trì danh sách chất cấm.',
        'Kết quả dương tính có thể dẫn đến treo giò, phạt tiền và thu hồi huy chương.',
        'Miễn trừ sử dụng trị liệu cho phép một số thuốc trong điều kiện nghiêm ngặt.',
        'Chương trình giáo dục nhằm ngăn vi phạm vô ý ở vận động viên trẻ.',
      ],
    },
    {
      title: 'Sponsorship deals',
      sentences: [
        'Major brands invest billions in athlete and team sponsorships annually.',
        'Sponsors expect athletes to promote products and maintain a positive image.',
        'A scandal involving a sponsored athlete can cost a brand millions overnight.',
        'Social media has created new opportunities for individual athlete endorsements.',
        'Sponsorship revenue often exceeds prize money in individual sports.',
      ],
      vi: [
        'Thương hiệu lớn đầu tư hàng tỷ vào tài trợ vận động viên và đội mỗi năm.',
        'Nhà tài trợ kỳ vọng vận động viên quảng bá sản phẩm và giữ hình ảnh tích cực.',
        'Bê bối liên quan vận động viên được tài trợ có thể khiến thương hiệu mất hàng triệu chỉ trong một đêm.',
        'Mạng xã hội tạo cơ hội mới cho hợp đồng quảng cáo cá nhân.',
        'Doanh thu tài trợ thường vượt tiền thưởng ở môn thi đấu cá nhân.',
      ],
    },
    {
      title: 'Sports marketing',
      sentences: [
        'Sports marketing uses emotional storytelling to connect fans with brands.',
        'Television rights for major leagues generate enormous global revenue.',
        'Clubs expand into international markets through pre-season tours.',
        'Merchandise sales contribute significantly to a team\'s overall income.',
        'Digital platforms allow clubs to engage directly with supporters worldwide.',
      ],
      vi: [
        'Marketing thể thao dùng kể chuyện cảm xúc để kết nối cổ động viên với thương hiệu.',
        'Bản quyền truyền hình giải đấu lớn tạo doanh thu toàn cầu khổng lồ.',
        'Câu lạc bộ mở rộng thị trường quốc tế qua tour mùa hè.',
        'Bán hàng hóa đóng góp đáng kể vào tổng thu nhập đội.',
        'Nền tảng số cho phép câu lạc bộ tương tác trực tiếp với cổ động viên toàn cầu.',
      ],
    },
    {
      title: 'Ticket sales and revenue',
      sentences: [
        'Stadium attendance remains a vital income stream for many sports clubs.',
        'Dynamic pricing adjusts ticket costs based on demand and opponent popularity.',
        'Season ticket holders provide financial stability throughout the year.',
        'Empty seats during losing seasons highlight the link between results and revenue.',
        'Some clubs offset ticket income with hospitality packages and VIP experiences.',
      ],
      vi: [
        'Khán giả đến sân vẫn là nguồn thu quan trọng của nhiều câu lạc bộ.',
        'Định giá linh hoạt điều chỉnh giá vé theo nhu cầu và độ nổi tiếng đối thủ.',
        'Vé mùa mang lại ổn định tài chính quanh năm.',
        'Ghế trống khi thua liên tiếp cho thấy mối liên hệ giữa kết quả và doanh thu.',
        'Một số câu lạc bộ bù thu nhập vé bằng gói tiếp đãi và trải nghiệm VIP.',
      ],
    },
    {
      title: 'Women in professional sport',
      sentences: [
        'Women\'s professional leagues have grown rapidly in football and cricket.',
        'Media coverage of women\'s sport has increased but still lags behind men\'s.',
        'Female athletes continue to break records and inspire the next generation.',
        'Investment in women\'s facilities and coaching remains uneven across countries.',
        'Visibility at major events helps challenge outdated stereotypes about gender.',
      ],
      vi: [
        'Giải chuyên nghiệp nữ phát triển nhanh ở bóng đá và cricket.',
        'Truyền thông về thể thao nữ tăng nhưng vẫn kém nam.',
        'Vận động viên nữ tiếp tục phá kỷ lục và truyền cảm hứng thế hệ sau.',
        'Đầu tư cơ sở và huấn luyện cho nữ vẫn chênh lệch giữa các nước.',
        'Sự hiện diện ở sự kiện lớn giúp thách thức định kiến lỗi thời về giới.',
      ],
    },
    {
      title: 'Equal pay debate',
      sentences: [
        'The equal pay debate centres on prize money and salaries in sport.',
        'Tennis Grand Slams now offer equal prize money for men and women.',
        'Critics argue that revenue generation should determine compensation levels.',
        'Advocates point out that equal effort deserves equal financial recognition.',
        'Progress has been made, but significant gaps persist in many sports.',
      ],
      vi: [
        'Tranh luận bình đẳng lương tập trung vào tiền thưởng và lương trong thể thao.',
        'Grand Slam quần vợt hiện trao tiền thưởng bình đẳng cho nam và nữ.',
        'Người phản đối cho rằng doanh thu nên quyết định mức thù lao.',
        'Người ủng hộ nhấn mạnh nỗ lực ngang nhau xứng đáng công nhận tài chính ngang nhau.',
        'Đã có tiến bộ, nhưng khoảng cách đáng kể vẫn tồn tại ở nhiều môn.',
      ],
    },
  ],

  c1: [
    {
      title: 'Mental toughness',
      sentences: [
        'Mental toughness enables athletes to perform under extreme competitive pressure.',
        'Sports psychologists distinguish between confidence, focus, and emotional control.',
        'Elite performers develop routines that anchor them before critical moments.',
        'Resilience after failure separates champions from those who plateau early.',
        'Cognitive training is now integrated alongside physical preparation programmes.',
      ],
      vi: [
        'Sức mạnh tinh thần giúp vận động viên thi đấu dưới áp lực cạnh tranh cực độ.',
        'Nhà tâm lý thể thao phân biệt tự tin, tập trung và kiểm soát cảm xúc.',
        'Vận động viên đỉnh cao xây thói quen neo mình trước khoảnh khắc then chốt.',
        'Khả năng phục hồi sau thất bại tách nhà vô địch khỏi người dừng sớm.',
        'Huấn luyện nhận thức hiện được tích hợp cùng chương trình chuẩn bị thể chất.',
      ],
    },
    {
      title: 'Performance anxiety',
      sentences: [
        'Performance anxiety manifests as physical symptoms before high-stakes events.',
        'Breathing techniques and mindfulness can reduce pre-competition nervousness.',
        'Perfectionism, while motivating, may exacerbate anxiety in vulnerable athletes.',
        'Coaches must recognise when psychological support is needed, not just tactical advice.',
        'Normalising conversations about anxiety has reduced stigma in professional sport.',
      ],
      vi: [
        'Lo âu thành tích biểu hiện triệu chứng thể chất trước sự kiện quan trọng.',
        'Kỹ thuật thở và chánh niệm có thể giảm hồi hộp trước thi đấu.',
        'Chủ nghĩa cầu toàn vừa thúc đẩy vừa có thể làm trầm trọng lo âu ở vận động viên dễ tổn thương.',
        'Huấn luyện viên phải nhận ra khi cần hỗ trợ tâm lý, không chỉ chiến thuật.',
        'Chuẩn hóa trò chuyện về lo âu đã giảm kỳ thị trong thể thao chuyên nghiệp.',
      ],
    },
    {
      title: 'Visualization techniques',
      sentences: [
        'Visualization involves mentally rehearsing successful performance scenarios.',
        'Neuroscience research suggests imagined practice activates similar brain pathways.',
        'Athletes use guided imagery to prepare for unfamiliar venues and conditions.',
        'Combining visualization with physical rehearsal yields superior outcomes.',
        'Sports psychology programmes increasingly teach these skills from junior levels.',
      ],
      vi: [
        'Hình dung tinh thần là diễn tập kịch bản thành công trong đầu.',
        'Nghiên cứu thần kinh cho thấy tập tưởng tượng kích hoạt đường não tương tự.',
        'Vận động viên dùng hình ảnh hướng dẫn chuẩn bị địa điểm và điều kiện lạ.',
        'Kết hợp hình dung với diễn tập thực tế cho kết quả vượt trội.',
        'Chương trình tâm lý thể thao ngày càng dạy kỹ năng này từ cấp trẻ.',
      ],
    },
    {
      title: 'Hosting the World Cup',
      sentences: [
        'Hosting a World Cup requires massive infrastructure investment and planning.',
        'Governments justify expenditure by citing tourism, jobs, and global prestige.',
        'Independent economists often question whether projected economic benefits materialise.',
        'White elephant stadiums left unused after tournaments burden host nations financially.',
        'The bidding process itself has faced corruption allegations in recent decades.',
      ],
      vi: [
        'Đăng cai World Cup đòi hỏi đầu tư hạ tầng và kế hoạch khổng lồ.',
        'Chính phủ biện minh chi tiêu bằng du lịch, việc làm và uy tín toàn cầu.',
        'Nhà kinh tế độc lập thường nghi ngờ lợi ích kinh tế dự kiến có thành hiện thực.',
        'Sân vận động bỏ hoang sau giải gây gánh nặng tài chính cho nước chủ nhà.',
        'Quy trình đấu thầu bản thân đã vướng cáo buộc tham nhũng trong vài thập kỷ qua.',
      ],
    },
    {
      title: 'Economic impact of mega-events',
      sentences: [
        'Mega-events generate short-term spending but long-term returns are debated.',
        'The multiplier effect of construction and hospitality employment is often overstated.',
        'Displacement occurs when local communities are relocated for venue development.',
        'Legacy planning must address how facilities serve citizens after athletes depart.',
        'Cost-benefit analyses should include opportunity costs of alternative public spending.',
      ],
      vi: [
        'Sự kiện lớn tạo chi tiêu ngắn hạn nhưng lợi ích dài hạn còn tranh cãi.',
        'Hiệu ứng nhân chi tiêu xây dựng và dịch vụ lưu trú thường bị phóng đại.',
        'Giải tỏa xảy ra khi cộng đồng địa phương phải di dời để xây địa điểm.',
        'Kế hoạch di sản phải giải quyết cơ sở phục vụ công dân sau khi vận động viên rời đi.',
        'Phân tích chi phí-lợi ích nên gồm chi phí cơ hội của chi tiêu công thay thế.',
      ],
    },
    {
      title: 'Rise of e-sports',
      sentences: [
        'E-sports has evolved from niche hobby into a billion-dollar global industry.',
        'Professional gamers train with the same intensity as traditional athletes.',
        'Major tournaments fill arenas and attract viewership rivalling conventional sports.',
        'Debate continues over whether competitive gaming qualifies as a legitimate sport.',
        'Educational institutions now offer scholarships and degrees in e-sports management.',
      ],
      vi: [
        'E-sports phát triển từ sở thích nhỏ thành ngành tỷ đô toàn cầu.',
        'Game thủ chuyên nghiệp tập với cường độ như vận động viên truyền thống.',
        'Giải lớn lấp đầy nhà thi đấu và thu hút lượt xem ngang thể thao thông thường.',
        'Tranh luận tiếp tục về việc thi đấu game có được coi là thể thao hợp lệ.',
        'Cơ sở giáo dục hiện cấp học bổng và bằng quản lý e-sports.',
      ],
    },
    {
      title: 'E-sports tournaments',
      sentences: [
        'International e-sports tournaments feature prize pools exceeding traditional events.',
        'Teams employ coaches, analysts, and sports psychologists for competitive advantage.',
        'Streaming platforms have democratised access but concentrated revenue among top creators.',
        'Player burnout from gruelling schedules raises concerns about long-term wellbeing.',
        'Governing bodies are establishing regulations around doping and match integrity.',
      ],
      vi: [
        'Giải e-sports quốc tế có giải thưởng vượt nhiều sự kiện truyền thống.',
        'Đội thuê huấn luyện viên, phân tích viên và nhà tâm lý để cạnh tranh.',
        'Nền tảng phát trực tiếp dân chủ hóa tiếp cận nhưng tập trung doanh thu ở top.',
        'Kiệt sức do lịch thi đấu dày đặc gây lo ngại về phúc lợi dài hạn.',
        'Cơ quan quản lý đang thiết lập quy định về doping và tính toàn vẹn trận đấu.',
      ],
    },
    {
      title: 'Gaming as a career',
      sentences: [
        'A career in professional gaming demands exceptional reflexes and strategic thinking.',
        'Income streams include tournament winnings, sponsorships, and content creation.',
        'The career lifespan of pro gamers is typically shorter than in physical sports.',
        'Parents and educators increasingly recognise viable pathways in the gaming industry.',
        'Ethical concerns around youth exposure to competitive pressure remain unresolved.',
      ],
      vi: [
        'Sự nghiệp game chuyên nghiệp đòi hỏi phản xạ và tư duy chiến thuật xuất sắc.',
        'Nguồn thu gồm tiền thưởng giải, tài trợ và sáng tạo nội dung.',
        'Tuổi nghề game thủ chuyên nghiệp thường ngắn hơn thể thao vật lý.',
        'Phụ huynh và nhà giáo dục ngày càng công nhận con đường khả thi trong ngành game.',
        'Lo ngại đạo đức về áp lực cạnh tranh lên thanh thiếu niên vẫn chưa giải quyết.',
      ],
    },
    {
      title: 'PE in schools',
      sentences: [
        'Physical education policy varies dramatically between education systems worldwide.',
        'Curriculum reforms increasingly emphasise lifelong fitness over competitive sport alone.',
        'Budget cuts have reduced PE hours in schools facing academic performance pressures.',
        'Inclusive PE programmes must accommodate students with disabilities and varying abilities.',
        'Evidence links regular physical activity to improved academic outcomes and mental health.',
      ],
      vi: [
        'Chính sách giáo dục thể chất chênh lệch lớn giữa các hệ thống giáo dục toàn cầu.',
        'Cải cách chương trình ngày càng nhấn mạnh thể lực suốt đời hơn chỉ thể thao thi đấu.',
        'Cắt giảm ngân sách đã giảm giờ PE ở trường chịu áp lực thành tích học thuật.',
        'Chương trình PE hòa nhập phải phù hợp học sinh khuyết tật và năng lực khác nhau.',
        'Bằng chứng liên kết hoạt động thể chất thường xuyên với kết quả học tập và sức khỏe tinh thần.',
      ],
    },
    {
      title: 'National fitness policy',
      sentences: [
        'Governments implement national fitness policies to combat rising obesity rates.',
        'Public health campaigns promote active commuting and accessible recreational facilities.',
        'Cross-sector collaboration between health, education, and sport ministries is essential.',
        'Policy effectiveness depends on sustained funding rather than short electoral cycles.',
        'Measuring population-level fitness outcomes remains methodologically challenging.',
      ],
      vi: [
        'Chính phủ triển khai chính sách thể lực quốc gia để chống béo phì gia tăng.',
        'Chiến dịch y tế công khuyến khích đi lại tích cực và cơ sở giải trí dễ tiếp cận.',
        'Hợp tác đa ngành giữa y tế, giáo dục và thể thao là cần thiết.',
        'Hiệu quả chính sách phụ thuộc tài trợ bền vững hơn chu kỳ bầu cử ngắn.',
        'Đo lường kết quả thể lực cấp dân số vẫn là thách thức về phương pháp.',
      ],
    },
  ],
};
