#!/usr/bin/env node
/**
 * Generates 100+ events per life stage (800+ total) for Cognitive Mirror.
 */
const fs = require('fs');
const path = require('path');

const STAGES = [
  {
    id: 1,
  name: { en: 'Primary School', vi: 'Tiểu học' },
    age: '6-10',
    categories: [
      { key: 'sharing', en: 'Sharing', vi: 'Chia sẻ' },
      { key: 'friendship', en: 'Friendship', vi: 'Tình bạn' },
      { key: 'school', en: 'School challenges', vi: 'Thử thách ở trường' },
      { key: 'family', en: 'Family interactions', vi: 'Gia đình' },
    ],
    templates: [
      { en: 'Your classmate borrowed your favorite pencil and returned it broken.', vi: 'Bạn cùng lớp mượn bút chì yêu thích của bạn và trả lại khi nó đã bị gãy.' },
      { en: 'You studied hard for a test but got a lower score than you expected.', vi: 'Bạn học rất chăm cho bài kiểm tra nhưng điểm thấp hơn mong đợi.' },
      { en: 'A friend did not invite you to their birthday party.', vi: 'Một người bạn không mời bạn đến tiệc sinh nhật của họ.' },
      { en: 'You found money on the playground and no one was watching.', vi: 'Bạn tìm thấy tiền ở sân chơi và không ai nhìn thấy.' },
      { en: 'Your sibling blamed you for something you did not do.', vi: 'Anh/chị/em đổ lỗi cho bạn về việc bạn không làm.' },
      { en: 'The teacher praised another student for an idea you shared first.', vi: 'Giáo viên khen một bạn khác về ý tưởng mà bạn đã nói trước.' },
      { en: 'You were chosen last for a team in physical education class.', vi: 'Bạn bị chọn cuối cùng khi chia đội trong giờ thể dục.' },
      { en: 'A classmate spread a rumor about you.', vi: 'Một bạn cùng lớp đồn đại điều không đúng về bạn.' },
      { en: 'You forgot your homework and the teacher asked about it in class.', vi: 'Bạn quên bài tập về nhà và giáo viên hỏi trước lớp.' },
      { en: 'Your parents compared your grades to your cousin\'s.', vi: 'Bố mẹ so sánh điểm số của bạn với anh/chị/em họ.' },
      { en: 'You wanted to play but had to help with chores at home.', vi: 'Bạn muốn đi chơi nhưng phải giúp việc nhà.' },
      { en: 'A friend asked you to keep a secret that made you uncomfortable.', vi: 'Bạn được nhờ giữ bí mật khiến bạn cảm thấy không thoải mái.' },
      { en: 'You saw someone being teased and others were laughing.', vi: 'Bạn thấy ai đó bị trêu chọc và mọi người đang cười.' },
      { en: 'You received a gift you did not really like.', vi: 'Bạn nhận được món quà mà bạn không thực sự thích.' },
      { en: 'Your best friend started spending more time with someone else.', vi: 'Bạn thân bắt đầu dành nhiều thời gian với người khác.' },
      { en: 'You accidentally broke something valuable at a friend\'s house.', vi: 'Bạn vô tình làm hỏng đồ quý giá ở nhà bạn.' },
      { en: 'You were asked to present in front of the whole class.', vi: 'Bạn được yêu cầu thuyết trình trước cả lớp.' },
      { en: 'A substitute teacher changed the rules you were used to.', vi: 'Giáo viên dạy thay thay đổi những quy tắc bạn quen thuộc.' },
      { en: 'You felt left out during group work.', vi: 'Bạn cảm thấy bị bỏ rơi khi làm việc nhóm.' },
      { en: 'You told the truth but got in trouble anyway.', vi: 'Bạn nói sự thật nhưng vẫn bị mắng.' },
      { en: 'Your pet got sick and needed extra care.', vi: 'Thú cưng của bạn bị ốm và cần được chăm sóc thêm.' },
      { en: 'You had to move to a new school mid-year.', vi: 'Bạn phải chuyển sang trường mới giữa năm học.' },
      { en: 'Someone took credit for your artwork.', vi: 'Ai đó nhận công lao cho bức tranh của bạn.' },
      { en: 'You felt nervous about a school performance.', vi: 'Bạn lo lắng về buổi biểu diễn ở trường.' },
      { en: 'Your parents argued loudly and you could hear them.', vi: 'Bố mẹ cãi nhau to và bạn nghe thấy hết.' },
    ],
  },
  {
    id: 2,
    name: { en: 'Middle School', vi: 'Trung học cơ sở' },
    age: '11-14',
    categories: [
      { key: 'identity', en: 'Identity', vi: 'Bản sắc' },
      { key: 'peer', en: 'Peer pressure', vi: 'Áp lực bạn bè' },
      { key: 'bullying', en: 'Bullying', vi: 'Bắt nạt' },
      { key: 'social', en: 'Social media', vi: 'Mạng xã hội' },
    ],
    templates: [
      { en: 'Your friends want you to skip class to hang out.', vi: 'Bạn bè rủ bạn trốn tiết để đi chơi.' },
      { en: 'Someone posted an unflattering photo of you online.', vi: 'Ai đó đăng ảnh không đẹp của bạn lên mạng.' },
      { en: 'You did not make the team or club you tried out for.', vi: 'Bạn không được chọn vào đội hoặc câu lạc bộ mà bạn thử.' },
      { en: 'A classmate made fun of how you dress.', vi: 'Một bạn cùng lớp chê cách bạn ăn mặc.' },
      { en: 'You felt pressure to change your interests to fit in.', vi: 'Bạn cảm thấy áp lực phải thay đổi sở thích để hòa nhập.' },
      { en: 'Your crush liked someone else and everyone knew.', vi: 'Người bạn thích thích người khác và ai cũng biết.' },
      { en: 'You got a much lower grade than your close friend on the same test.', vi: 'Bạn được điểm thấp hơn nhiều so với bạn thân trong cùng bài kiểm tra.' },
      { en: 'Someone spread gossip about you in a group chat.', vi: 'Ai đó đồn đại về bạn trong nhóm chat.' },
      { en: 'You were excluded from a group project on purpose.', vi: 'Bạn bị cố tình loại khỏi dự án nhóm.' },
      { en: 'Your parents restricted your phone or social media use.', vi: 'Bố mẹ hạn chế việc dùng điện thoại hoặc mạng xã hội của bạn.' },
      { en: 'You witnessed bullying but were afraid to speak up.', vi: 'Bạn chứng kiến bắt nạt nhưng sợ lên tiếng.' },
      { en: 'A friend asked you to lie to cover for them.', vi: 'Bạn được nhờ nói dối để che giấu cho bạn.' },
      { en: 'You started comparing yourself to influencers online.', vi: 'Bạn bắt đầu so sánh bản thân với người nổi tiếng trên mạng.' },
      { en: 'Your body changed and you felt self-conscious.', vi: 'Cơ thể bạn thay đổi và bạn cảm thấy tự ti.' },
      { en: 'You failed to finish an assignment on time.', vi: 'Bạn không kịp hoàn thành bài tập đúng hạn.' },
      { en: 'A teacher seemed to favor certain students over others.', vi: 'Một giáo viên có vẻ thiên vị một số học sinh.' },
      { en: 'You felt torn between two friend groups.', vi: 'Bạn cảm thấy bị kéo giữa hai nhóm bạn.' },
      { en: 'Someone copied your homework and got a better comment.', vi: 'Ai đó chép bài của bạn và được giáo viên khen.' },
      { en: 'You received harsh criticism from a coach or mentor.', vi: 'Bạn nhận lời phê bình gay gắt từ huấn luyện viên hoặc người hướng dẫn.' },
      { en: 'Your family could not afford something your friends had.', vi: 'Gia đình bạn không đủ khả năng mua thứ mà bạn bè có.' },
      { en: 'You felt invisible in a large friend group.', vi: 'Bạn cảm thấy vô hình trong một nhóm bạn đông người.' },
      { en: 'A friend betrayed a confidence you shared.', vi: 'Bạn bị phản bội khi tiết lộ điều bạn tin tưởng chia sẻ.' },
      { en: 'You were pressured to share personal photos online.', vi: 'Bạn bị ép chia sẻ ảnh cá nhân lên mạng.' },
      { en: 'You questioned whether you belong in your current friend group.', vi: 'Bạn tự hỏi liệu mình có thuộc về nhóm bạn hiện tại không.' },
      { en: 'You had your first serious disagreement with a parent.', vi: 'Bạn có lần bất đồng nghiêm trọng đầu tiên với bố mẹ.' },
    ],
  },
  {
    id: 3,
    name: { en: 'High School', vi: 'Trung học phổ thông' },
    age: '15-18',
    categories: [
      { key: 'exams', en: 'Exams', vi: 'Kỳ thi' },
      { key: 'career', en: 'Career choices', vi: 'Lựa chọn nghề nghiệp' },
      { key: 'competition', en: 'Competition', vi: 'Cạnh tranh' },
      { key: 'relationships', en: 'Relationships', vi: 'Mối quan hệ' },
    ],
    templates: [
      { en: 'You studied for months but did not get into your dream university.', vi: 'Bạn ôn thi hàng tháng nhưng không đỗ trường mơ ước.' },
      { en: 'Your parents want you to study medicine but you prefer arts.', vi: 'Bố mẹ muốn bạn học y nhưng bạn thích nghệ thuật hơn.' },
      { en: 'A close friend started distancing themselves before exams.', vi: 'Bạn thân bắt đầu xa cách trước kỳ thi.' },
      { en: 'You were rejected from a leadership position you wanted.', vi: 'Bạn không được chọn vào vị trí lãnh đạo mà bạn mong muốn.' },
      { en: 'Your relationship ended during an important academic year.', vi: 'Mối quan hệ của bạn kết thúc trong năm học quan trọng.' },
      { en: 'You cheated on a small quiz and felt guilty afterward.', vi: 'Bạn quay cóp trong một bài kiểm tra nhỏ và cảm thấy tội lỗi sau đó.' },
      { en: 'A teacher told you your work was not good enough for advanced class.', vi: 'Giáo viên nói bài làm của bạn chưa đủ tốt để vào lớp nâng cao.' },
      { en: 'You had to choose between extracurricular passion and grades.', vi: 'Bạn phải chọn giữa đam mê ngoại khóa và điểm số.' },
      { en: 'Your family faced financial stress affecting your studies.', vi: 'Gia đình gặp khó khăn tài chính ảnh hưởng đến việc học của bạn.' },
      { en: 'You were compared publicly to a high-achieving sibling.', vi: 'Bạn bị so sánh công khai với anh/chị/em học giỏi.' },
      { en: 'A group member did not contribute but everyone got the same grade.', vi: 'Một thành viên nhóm không làm gì nhưng cả nhóm cùng điểm.' },
      { en: 'You felt burnout from constant competition.', vi: 'Bạn cảm thấy kiệt sức vì cạnh tranh liên tục.' },
      { en: 'You discovered a passion that does not align with your current path.', vi: 'Bạn khám phá đam mê không phù hợp với con đường hiện tại.' },
      { en: 'A mentor gave you harsh feedback on your future plans.', vi: 'Người cố vấn phê bình gay gắt kế hoạch tương lai của bạn.' },
      { en: 'You missed an important deadline due to personal issues.', vi: 'Bạn trễ hạn quan trọng vì vấn đề cá nhân.' },
      { en: 'Your best friend got into a program you also applied to, but you did not.', vi: 'Bạn thân đỗ chương trình mà bạn cũng nộp đơn, còn bạn thì không.' },
      { en: 'You were offered an internship far from your support network.', vi: 'Bạn được mời thực tập xa khỏi mạng lưới hỗ trợ của mình.' },
      { en: 'Social events clashed with exam preparation schedule.', vi: 'Sự kiện xã hội trùng với lịch ôn thi.' },
      { en: 'You questioned whether your hard work was worth it.', vi: 'Bạn tự hỏi liệu sự nỗ lực có đáng không.' },
      { en: 'A family member became seriously ill during final exams.', vi: 'Người thân ốm nặng trong kỳ thi cuối.' },
      { en: 'You received unexpected praise that felt undeserved.', vi: 'Bạn được khen bất ngờ mà cảm thấy không xứng đáng.' },
      { en: 'You had to represent your school in a competition you felt unprepared for.', vi: 'Bạn phải đại diện trường thi đấu dù cảm thấy chưa sẵn sàng.' },
      { en: 'Friends made plans without you after graduation approaches.', vi: 'Bạn bè lên kế hoạch không có bạn khi sắp tốt nghiệp.' },
      { en: 'You considered taking a gap year against family expectations.', vi: 'Bạn cân nhắc nghỉ một năm trái với kỳ vọng gia đình.' },
      { en: 'A scholarship you counted on fell through at the last minute.', vi: 'Học bổng bạn trông đợi hủy vào phút chót.' },
    ],
  },
  {
    id: 4,
    name: { en: 'University', vi: 'Đại học' },
    age: '18-22',
    categories: [
      { key: 'independence', en: 'Independence', vi: 'Độc lập' },
      { key: 'jobs', en: 'Part-time jobs', vi: 'Việc làm thêm' },
      { key: 'romance', en: 'Romantic relationships', vi: 'Tình cảm' },
      { key: 'uncertainty', en: 'Career uncertainty', vi: 'Bất định nghề nghiệp' },
    ],
    templates: [
      { en: 'Your part-time job schedule conflicts with important lectures.', vi: 'Lịch làm thêm trùng với những buổi học quan trọng.' },
      { en: 'You are running low on money before the semester ends.', vi: 'Bạn sắp hết tiền trước khi học kỳ kết thúc.' },
      { en: 'A roommate\'s habits are affecting your sleep and focus.', vi: 'Thói quen của bạn cùng phòng ảnh hưởng giấc ngủ và sự tập trung của bạn.' },
      { en: 'You chose a major you are no longer passionate about.', vi: 'Bạn chọn ngành mà giờ không còn đam mê.' },
      { en: 'A group project partner disappeared before the deadline.', vi: 'Đối tác nhóm biến mất trước hạn nộp bài.' },
      { en: 'You fell behind after a breakup.', vi: 'Bạn tụt hậu sau khi chia tay.' },
      { en: 'An internship rejection made you doubt your abilities.', vi: 'Bị từ chối thực tập khiến bạn nghi ngờ khả năng của mình.' },
      { en: 'You feel homesick but do not want to worry your family.', vi: 'Bạn nhớ nhà nhưng không muốn làm gia đình lo.' },
      { en: 'Friends seem to have clearer career paths than you.', vi: 'Bạn bè có vẻ rõ ràng hơn về con đường nghề nghiệp.' },
      { en: 'You were offered a job that requires leaving university early.', vi: 'Bạn được mời làm việc nhưng phải bỏ học sớm.' },
      { en: 'Academic pressure led to anxiety before presentations.', vi: 'Áp lực học tập gây lo âu trước khi thuyết trình.' },
      { en: 'You discovered a classmate plagiarized your work.', vi: 'Bạn phát hiện bạn cùng lớp đạo văn bài của bạn.' },
      { en: 'A professor\'s feedback felt personally dismissive.', vi: 'Phản hồi của giáo sư khiến bạn cảm thấy bị coi thường.' },
      { en: 'You must choose between studying abroad and staying near family.', vi: 'Bạn phải chọn giữa du học và ở gần gia đình.' },
      { en: 'Social life is thriving but grades are slipping.', vi: 'Đời sống xã hội sôi động nhưng điểm số đang giảm.' },
      { en: 'You took on too many commitments and missed deadlines.', vi: 'Bạn nhận quá nhiều việc và trễ hạn.' },
      { en: 'A close friendship ended over a political or value disagreement.', vi: 'Tình bạn thân tan vỡ vì bất đồng chính trị hoặc giá trị.' },
      { en: 'You failed a course required for your degree.', vi: 'Bạn trượt môn bắt buộc để tốt nghiệp.' },
      { en: 'Networking events feel uncomfortable and inauthentic to you.', vi: 'Sự kiện networking khiến bạn khó chịu và không tự nhiên.' },
      { en: 'Your parents question whether your degree is practical.', vi: 'Bố mẹ đặt câu hỏi về tính thực tiễn của bằng cấp bạn học.' },
      { en: 'You received an opportunity that requires relocating alone.', vi: 'Bạn nhận cơ hội phải chuyển đi một mình.' },
      { en: 'A romantic partner wants more time than you can give during finals.', vi: 'Người yêu muốn dành nhiều thời gian hơn bạn có thể trong kỳ thi.' },
      { en: 'You compare your progress to classmates on social media.', vi: 'Bạn so sánh tiến độ với bạn cùng lớp trên mạng xã hội.' },
      { en: 'Student debt is becoming a source of daily stress.', vi: 'Nợ học phí trở thành nguồn căng thẳng hàng ngày.' },
      { en: 'You are unsure whether to pursue graduate school or work.', vi: 'Bạn không chắc nên học sau đại học hay đi làm.' },
    ],
  },
  {
    id: 5,
    name: { en: 'Early Career', vi: 'Sự nghiệp đầu đời' },
    age: '22-30',
    categories: [
      { key: 'promotion', en: 'Promotion', vi: 'Thăng tiến' },
      { key: 'jobloss', en: 'Job loss', vi: 'Mất việc' },
      { key: 'startup', en: 'Entrepreneurship', vi: 'Khởi nghiệp' },
      { key: 'burnout', en: 'Burnout', vi: 'Kiệt sức' },
    ],
    templates: [
      { en: 'You worked very hard on a project but your manager gave credit to someone else.', vi: 'Bạn làm việc rất chăm cho dự án nhưng sếp ghi nhận công lao cho người khác.' },
      { en: 'You were passed over for promotion despite strong performance.', vi: 'Bạn bị bỏ qua khi xét thăng tiến dù làm tốt.' },
      { en: 'A startup idea excites you but stable income feels safer.', vi: 'Ý tưởng khởi nghiệp khiến bạn hào hứng nhưng thu nhập ổn định an toàn hơn.' },
      { en: 'You were laid off unexpectedly.', vi: 'Bạn bị sa thải bất ngờ.' },
      { en: 'Overtime is hurting your health and relationships.', vi: 'Làm thêm giờ đang ảnh hưởng sức khỏe và các mối quan hệ.' },
      { en: 'A colleague took your idea to leadership without mentioning you.', vi: 'Đồng nghiệp đưa ý tưởng của bạn lên lãnh đạo mà không nhắc đến bạn.' },
      { en: 'You received critical feedback in a public meeting.', vi: 'Bạn nhận phản hồi gay gắt trong cuộc họp công khai.' },
      { en: 'Your salary is lower than peers with similar experience.', vi: 'Lương của bạn thấp hơn đồng nghiệp cùng kinh nghiệm.' },
      { en: 'You are asked to relocate for a better role.', vi: 'Bạn được yêu cầu chuyển nơi làm việc cho vị trí tốt hơn.' },
      { en: 'A side project is growing but your employer has strict policies.', vi: 'Dự án phụ đang phát triển nhưng công ty có chính sách nghiêm ngặt.' },
      { en: 'You feel imposter syndrome in a new senior role.', vi: 'Bạn cảm thấy hội chứng kẻ mạo danh ở vị trí cao hơn.' },
      { en: 'Your team missed a deadline and blame is circulating.', vi: 'Nhóm trễ deadline và mọi người đổ lỗi lẫn nhau.' },
      { en: 'A mentor you trusted left the company.', vi: 'Người cố vấn bạn tin tưởng rời công ty.' },
      { en: 'You must choose between passion project and career stability.', vi: 'Bạn phải chọn giữa dự án đam mê và sự ổn định nghề nghiệp.' },
      { en: 'Remote work blurred boundaries between work and personal life.', vi: 'Làm từ xa làm ranh giới công việc và đời sống bị mờ đi.' },
      { en: 'You discovered unfair pay practices on your team.', vi: 'Bạn phát hiện chênh lệch lương không công bằng trong nhóm.' },
      { en: 'A client relationship turned toxic.', vi: 'Mối quan hệ với khách hàng trở nên độc hại.' },
      { en: 'You failed to meet a KPI for the first time.', vi: 'Bạn lần đầu không đạt KPI.' },
      { en: 'Networking feels necessary but draining.', vi: 'Networking cảm thấy cần thiết nhưng rất mệt mỏi.' },
      { en: 'Your industry is changing and your skills may become outdated.', vi: 'Ngành đang thay đổi và kỹ năng của bạn có thể lỗi thời.' },
      { en: 'A co-founder disagreement threatens your venture.', vi: 'Bất đồng với đồng sáng lập đe dọa dự án của bạn.' },
      { en: 'You are managing people for the first time and made a mistake.', vi: 'Bạn lần đầu quản lý người khác và mắc sai lầm.' },
      { en: 'Work travel is affecting your relationship.', vi: 'Công tác ảnh hưởng đến mối quan hệ của bạn.' },
      { en: 'You received an offer from a competitor.', vi: 'Bạn nhận lời mời từ đối thủ cạnh tranh.' },
      { en: 'Burnout made you consider leaving a field you once loved.', vi: 'Kiệt sức khiến bạn muốn rời ngành từng yêu thích.' },
    ],
  },
  {
    id: 6,
    name: { en: 'Family Life', vi: 'Gia đình trẻ' },
    age: '30-45',
    categories: [
      { key: 'marriage', en: 'Marriage', vi: 'Hôn nhân' },
      { key: 'parenting', en: 'Parenting', vi: 'Nuôi dạy con' },
      { key: 'mortgage', en: 'Mortgage', vi: 'Vay mua nhà' },
      { key: 'conflict', en: 'Family conflicts', vi: 'Xung đột gia đình' },
    ],
    templates: [
      { en: 'You and your partner disagree about how to raise your child.', vi: 'Bạn và người bạn đời bất đồng cách nuôi dạy con.' },
      { en: 'Mortgage payments are straining your monthly budget.', vi: 'Trả nợ nhà đang căng kết ngân sách hàng tháng.' },
      { en: 'Your child is struggling at school and blames you.', vi: 'Con bạn gặp khó khăn ở trường và đổ lỗi cho bạn.' },
      { en: 'In-laws offer advice that conflicts with your parenting style.', vi: 'Ông bà đưa lời khuyên trái với cách nuôi dạy của bạn.' },
      { en: 'Work demands reduce time you wanted to spend with family.', vi: 'Công việc chiếm thời gian bạn muốn dành cho gia đình.' },
      { en: 'A family vacation was cancelled due to unexpected expenses.', vi: 'Kỳ nghỉ gia đình bị hủy vì chi phí phát sinh.' },
      { en: 'You feel guilty for missing your child\'s important event.', vi: 'Bạn cảm thấy tội lỗi vì lỡ sự kiện quan trọng của con.' },
      { en: 'Your partner wants to move cities for their career.', vi: 'Người bạn đời muốn chuyển thành phố vì sự nghiệp của họ.' },
      { en: 'Elderly parents need more support than you can provide.', vi: 'Bố mẹ già cần hỗ trợ nhiều hơn khả năng của bạn.' },
      { en: 'A financial setback threatens your family\'s plans.', vi: 'Khó khăn tài chính đe dọa kế hoạch của gia đình.' },
      { en: 'You and your partner argue about money regularly.', vi: 'Bạn và người bạn đời thường xuyên cãi nhau về tiền bạc.' },
      { en: 'Your child prefers one parent over the other, and it hurts.', vi: 'Con thiên về một người bố/mẹ và điều đó làm bạn tổn thương.' },
      { en: 'Balancing career growth and being present at home feels impossible.', vi: 'Cân bằng thăng tiến sự nghiệp và có mặt ở nhà dường như không thể.' },
      { en: 'A close friend\'s family seems more harmonious than yours.', vi: 'Gia đình bạn thân có vẻ hòa thuận hơn gia đình bạn.' },
      { en: 'You discovered your teenager kept a serious secret.', vi: 'Bạn phát hiện con tuổi teen giấu bạn điều nghiêm trọng.' },
      { en: 'Renovation costs exceeded what you planned.', vi: 'Chi phí sửa nhà vượt kế hoạch.' },
      { en: 'You must choose between a promotion and less travel.', vi: 'Bạn phải chọn giữa thăng tiến và giảm đi công tác.' },
      { en: 'Family traditions you value are being questioned by your children.', vi: 'Truyền thống gia đình bạn trân trọng bị con cái đặt câu hỏi.' },
      { en: 'A health scare in the family changed everyone\'s priorities.', vi: 'Một cú sốc sức khỏe trong gia đình thay đổi ưu tiên của mọi người.' },
      { en: 'You feel you are repeating patterns from your own childhood.', vi: 'Bạn cảm thấy đang lặp lại khuôn mẫu từ thời thơ ấu của mình.' },
      { en: 'Your sibling asks for financial help you are unsure about giving.', vi: 'Anh/chị/em nhờ vay tiền mà bạn không chắc có nên giúp.' },
      { en: 'Date nights with your partner have become rare.', vi: 'Những buổi hẹn hò với người bạn đời trở nên hiếm hoi.' },
      { en: 'You disagree with your partner about saving versus spending.', vi: 'Bạn bất đồng với người bạn đời về tiết kiệm hay tiêu xài.' },
      { en: 'A neighbor\'s success makes you question your life choices.', vi: 'Thành công của hàng xóm khiến bạn tự hỏi về lựa chọn cuộc đời.' },
      { en: 'You are considering therapy but worry what others will think.', vi: 'Bạn cân nhắc trị liệu tâm lý nhưng lo người khác nghĩ gì.' },
    ],
  },
  {
    id: 7,
    name: { en: 'Midlife', vi: 'Trung niên' },
    age: '45-60',
    categories: [
      { key: 'transition', en: 'Career transition', vi: 'Chuyển nghề' },
      { key: 'health', en: 'Health concerns', vi: 'Lo ngại sức khỏe' },
      { key: 'emptynest', en: 'Empty nest', vi: 'Con trưởng thành rời nhà' },
      { key: 'leadership', en: 'Leadership', vi: 'Lãnh đạo' },
    ],
    templates: [
      { en: 'Your children left home and the house feels unusually quiet.', vi: 'Con cái rời nhà và ngôi nhà bỗng trở nên quá yên tĩnh.' },
      { en: 'A health diagnosis requires lifestyle changes.', vi: 'Chẩn đoán sức khỏe yêu cầu thay đổi lối sống.' },
      { en: 'You are offered early retirement but are not sure you are ready.', vi: 'Bạn được đề nghị nghỉ hưu sớm nhưng chưa chắc mình sẵn sàng.' },
      { en: 'A younger colleague was promoted to a role you wanted.', vi: 'Đồng nghiệp trẻ hơn được thăng tiến vào vị trí bạn mong muốn.' },
      { en: 'You question the meaning of decades spent in your career.', vi: 'Bạn tự hỏi ý nghĩa của hàng thập kỷ theo đuổi sự nghiệp.' },
      { en: 'Caring for aging parents conflicts with your work responsibilities.', vi: 'Chăm sóc bố mẹ già xung đột với trách nhiệm công việc.' },
      { en: 'A long-term friendship ended over unresolved differences.', vi: 'Tình bạn lâu năm kết thúc vì bất đồng chưa giải quyết.' },
      { en: 'You feel your expertise is overlooked in favor of new trends.', vi: 'Bạn cảm thấy chuyên môn bị bỏ qua vì xu hướng mới.' },
      { en: 'Your marriage entered a phase of emotional distance.', vi: 'Hôn nhân của bạn bước vào giai đoạn xa cách về cảm xúc.' },
      { en: 'A financial advisor suggests risky changes to your retirement plan.', vi: 'Cố vấn tài chính đề xuất thay đổi rủi ro cho kế hoạch nghỉ hưu.' },
      { en: 'You are asked to mentor others while feeling uncertain yourself.', vi: 'Bạn được nhờ cố vấn người khác trong khi bản thân cũng bất an.' },
      { en: 'A hobby you ignored for years suddenly feels important.', vi: 'Sở thích bị bỏ bê nhiều năm bỗng trở nên quan trọng.' },
      { en: 'You compare your life achievements to peers at a reunion.', vi: 'Bạn so sánh thành tựu với bạn bè trong buổi họp mặt.' },
      { en: 'A leadership decision you made had unintended consequences.', vi: 'Quyết định lãnh đạo của bạn có hậu quả không lường trước.' },
      { en: 'You want to change careers but worry about starting over.', vi: 'Bạn muốn đổi nghề nhưng lo phải bắt đầu lại.' },
      { en: 'Your physical limits are becoming more noticeable.', vi: 'Giới hạn thể chất ngày càng rõ ràng hơn.' },
      { en: 'A sibling rivalry resurfaced during a family crisis.', vi: 'Cạnh tranh anh chị em tái hiện trong khủng hoảng gia đình.' },
      { en: 'You inherited responsibilities you did not expect.', vi: 'Bạn thừa kế trách nhiệm không ngờ tới.' },
      { en: 'Volunteer work gives meaning but takes significant time.', vi: 'Tình nguyện mang lại ý nghĩa nhưng tốn nhiều thời gian.' },
      { en: 'A former dream feels unreachable now.', vi: 'Ước mơ xưa giờ có vẻ không thể chạm tới.' },
      { en: 'Technology changes at work feel overwhelming.', vi: 'Thay đổi công nghệ ở công việc khiến bạn choáng ngợp.' },
      { en: 'You notice you judge younger generations harshly sometimes.', vi: 'Bạn nhận ra đôi khi phán xét thế hệ trẻ quá gay gắt.' },
      { en: 'A trusted doctor retired and you must find someone new.', vi: 'Bác sĩ tin cậy nghỉ hưu và bạn phải tìm người mới.' },
      { en: 'You are torn between stability and one last ambitious project.', vi: 'Bạn bị kéo giữa ổn định và một dự án đầy tham vọng cuối cùng.' },
      { en: 'Friends your age are facing serious losses.', vi: 'Bạn bè cùng tuổi đang đối mặt những mất mát nghiêm trọng.' },
    ],
  },
  {
    id: 8,
    name: { en: 'Retirement', vi: 'Nghỉ hưu' },
    age: '60+',
    categories: [
      { key: 'retirement', en: 'Retirement', vi: 'Nghỉ hưu' },
      { key: 'loneliness', en: 'Loneliness', vi: 'Cô đơn' },
      { key: 'community', en: 'Community', vi: 'Cộng đồng' },
      { key: 'review', en: 'Life review', vi: 'Nhìn lại cuộc đời' },
    ],
    templates: [
      { en: 'You retired but miss the structure and purpose work gave you.', vi: 'Bạn đã nghỉ hưu nhưng nhớ cấu trúc và ý nghĩa mà công việc mang lại.' },
      { en: 'Old friends have moved away or passed away.', vi: 'Bạn cũ đã chuyển đi hoặc qua đời.' },
      { en: 'Your adult children are busy and call less often than you hoped.', vi: 'Con trưởng thành bận rộn và gọi ít hơn bạn mong đợi.' },
      { en: 'You have time but are unsure how to use it meaningfully.', vi: 'Bạn có thời gian nhưng không chắc dùng nó có ý nghĩa thế nào.' },
      { en: 'A health limitation changed activities you once enjoyed.', vi: 'Hạn chế sức khỏe thay đổi những hoạt động bạn từng thích.' },
      { en: 'You want to share wisdom but feel unheard by younger family.', vi: 'Bạn muốn chia sẻ kinh nghiệm nhưng cảm thấy thế hệ trẻ không lắng nghe.' },
      { en: 'Financial worries persist despite years of planning.', vi: 'Lo tài chính vẫn còn dù đã lên kế hoạch nhiều năm.' },
      { en: 'You volunteered but felt unappreciated.', vi: 'Bạn làm tình nguyện nhưng cảm thấy không được trân trọng.' },
      { en: 'Looking back, one decision still troubles you.', vi: 'Nhìn lại, một quyết định vẫn khiến bạn băn khoăn.' },
      { en: 'A new community activity feels intimidating to join.', vi: 'Hoạt động cộng đồng mới khiến bạn e ngại tham gia.' },
      { en: 'You and your partner have different visions for retirement.', vi: 'Bạn và người bạn đời có tầm nhìn khác nhau về nghỉ hưu.' },
      { en: 'Technology makes it harder to stay connected with grandchildren.', vi: 'Công nghệ khiến việc kết nối với cháu khó hơn.' },
      { en: 'You downsized your home and grieved what you left behind.', vi: 'Bạn chuyển về nhà nhỏ hơn và buồn vì những gì để lại.' },
      { en: 'A former colleague achieved recognition you once wanted.', vi: 'Đồng nghiệp cũ đạt được sự công nhận mà bạn từng mong muốn.' },
      { en: 'You wrote memoirs but hesitate to share them.', vi: 'Bạn viết hồi ký nhưng ngần ngại chia sẻ.' },
      { en: 'Medical appointments dominate your calendar.', vi: 'Lịch hẹn bác sĩ chiếm phần lớn thời gian của bạn.' },
      { en: 'You feel invisible in public spaces sometimes.', vi: 'Đôi khi bạn cảm thấy vô hình ở nơi công cộng.' },
      { en: 'A long-postponed dream is still possible but risky.', vi: 'Ước mơ hoãn lại nhiều năm vẫn khả thi nhưng rủi ro.' },
      { en: 'You reconciled with someone after many years.', vi: 'Bạn hòa giải với ai đó sau nhiều năm.' },
      { en: 'Giving away possessions stirred unexpected emotions.', vi: 'Cho đi đồ đạc gợi lên cảm xúc không ngờ.' },
      { en: 'You question what legacy you will leave.', vi: 'Bạn tự hỏi di sản mình để lại là gì.' },
      { en: 'A neighbor\'s kindness reminded you to reach out more.', vi: 'Lòng tốt của hàng xóm nhắc bạn nên chủ động kết nối hơn.' },
      { en: 'You fear becoming a burden to your family.', vi: 'Bạn sợ trở thành gánh nặng cho gia đình.' },
      { en: 'Travel plans were cancelled due to health or family needs.', vi: 'Kế hoạch du lịch bị hủy vì sức khỏe hoặc nhu cầu gia đình.' },
      { en: 'You found joy in a small daily ritual you once ignored.', vi: 'Bạn tìm thấy niềm vui trong thói quen nhỏ từng bỏ qua.' },
    ],
  },
];

const IMMEDIATE_OUTCOMES = {
  en: [
    'The situation escalated briefly but settled within a day.',
    'Someone noticed your reaction and reached out to talk.',
    'Nothing visible changed immediately, but you felt different inside.',
    'A small opportunity appeared that was not there before.',
    'Tension remained, and the atmosphere felt heavier.',
    'You gained a clearer sense of what matters to you.',
    'Others interpreted your response differently than you intended.',
    'The immediate outcome was neutral, with effects still unfolding.',
  ],
  vi: [
    'Tình huống căng thẳng trong chốc lát rồi lắng xuống trong ngày.',
    'Ai đó để ý phản ứng của bạn và chủ động trò chuyện.',
    'Bên ngoài chưa thay đổi gì, nhưng bên trong bạn cảm thấy khác.',
    'Một cơ hội nhỏ xuất hiện mà trước đó không có.',
    'Căng thẳng vẫn còn, không khí trở nên nặng nề hơn.',
    'Bạn hiểu rõ hơn điều gì quan trọng với mình.',
    'Người khác hiểu phản ứng của bạn khác với ý bạn.',
    'Kết quả trước mắt trung tính, hệ quả vẫn đang diễn ra.',
  ],
};

const LATER_OUTCOMES = {
  en: [
    'Weeks later, a similar situation triggered the same pattern.',
    'Your approach influenced how others trust you over time.',
    'A relationship deepened or cooled based on this moment.',
    'You noticed this choice affected your confidence in future decisions.',
    'The experience became a reference point you return to mentally.',
    'An unexpected connection formed from how you handled this.',
    'Stress from this event affected another area of your life.',
    'You adapted your strategy when a parallel challenge appeared.',
  ],
  vi: [
    'Vài tuần sau, tình huống tương tự kích hoạt lại cùng một khuôn mẫu.',
    'Cách bạn xử lý ảnh hưởng đến niềm tin người khác dành cho bạn theo thời gian.',
    'Mối quan hệ sâu sắc hơn hoặc nguội lạnh vì khoảnh khắc này.',
    'Bạn nhận ra lựa chọn này ảnh hưởng đến tự tin trong các quyết định sau.',
    'Trải nghiệm trở thành điểm tham chiếu bạn thường nghĩ lại.',
    'Một kết nối bất ngờ hình thành từ cách bạn xử lý việc này.',
    'Căng thẳng từ sự kiện này lan sang lĩnh vực khác trong đời bạn.',
    'Bạn điều chỉnh chiến lược khi thử thách tương tự xuất hiện.',
  ],
};

function pad(n, width = 3) {
  return String(n).padStart(width, '0');
}

const events = [];

for (const stage of STAGES) {
  let idx = 0;
  for (const template of stage.templates) {
    for (let v = 0; v < 4; v++) {
      idx++;
      const cat = stage.categories[idx % stage.categories.length];
      const suffix = v > 0 ? (v === 1 ? ' — again, under more pressure.' : v === 2 ? ' — this time with witnesses.' : ' — with higher stakes.') : '';
      const suffixVi = v > 0 ? (v === 1 ? ' — lần này áp lực lớn hơn.' : v === 2 ? ' — lần này có người chứng kiến.' : ' — với mức độ nghiêm trọng cao hơn.') : '';
      events.push({
        id: `stage${stage.id}-${pad(idx)}`,
        stage: stage.id,
        category: cat.key,
        categoryLabel: { en: cat.en, vi: cat.vi },
        description: {
          en: template.en + suffix,
          vi: template.vi + suffixVi,
        },
        immediateOutcomes: IMMEDIATE_OUTCOMES,
        laterOutcomes: LATER_OUTCOMES,
      });
    }
  }
}

const output = {
  version: 1,
  totalEvents: events.length,
  stages: STAGES.map((s) => ({
    id: s.id,
    name: s.name,
    age: s.age,
    categories: s.categories,
    eventCount: events.filter((e) => e.stage === s.id).length,
  })),
  events,
};

const outPath = path.join(__dirname, '..', 'data', 'events.json');
fs.writeFileSync(outPath, JSON.stringify(output, null, 2), 'utf8');
console.log(`Generated ${events.length} events -> ${outPath}`);
