import json
import re
from collections import Counter, defaultdict
from pathlib import Path


RAW = {
    1: [
        ("ball", "quả bóng"), ("bell", "cái chuông"), ("bike", "xe đạp"), ("book", "quyển sách"),
        ("cake", "bánh ngọt"), ("car", "xe ô tô"), ("cat", "con mèo"), ("cup", "cái cốc"),
        ("apple", "quả táo"), ("bag", "cặp sách"), ("can", "cái lon"), ("hat", "cái mũ"),
        ("desk", "bàn học"), ("dog", "con chó"), ("door", "cửa ra vào"), ("duck", "con vịt"),
        ("chicken", "thịt gà"), ("chips", "khoai tây chiên"), ("fish", "con cá"), ("milk", "sữa"),
        ("pen", "bút mực"), ("pencil", "bút chì"), ("red", "màu đỏ"), ("garden", "khu vườn"),
        ("gate", "cái cổng"), ("girl", "bé gái"), ("goat", "con dê"), ("hair", "tóc"),
        ("hand", "bàn tay"), ("head", "cái đầu"), ("horse", "con ngựa"), ("shop", "cửa hàng"),
        ("shoe", "giày"), ("shorts", "quần đùi"), ("shirt", "áo sơ mi"), ("zoo", "sở thú"),
        ("zebra", "ngựa vằn"), ("tiger", "con hổ"), ("monkey", "con khỉ"), ("banana", "quả chuối"),
        ("noodles", "mì"), ("nuts", "các loại hạt"), ("lake", "hồ nước"), ("leaf", "chiếc lá"),
        ("lemon", "quả chanh"), ("lion", "sư tử"), ("rice", "cơm"), ("sail", "cánh buồm"),
        ("sand", "cát"), ("sea", "biển"), ("teddy bear", "gấu bông"), ("toy", "đồ chơi"),
        ("train", "tàu hỏa"), ("tree", "cây"), ("football", "bóng đá"), ("goal", "khung thành"),
        ("mother", "mẹ"), ("father", "bố"), ("brother", "anh/em trai"), ("sister", "chị/em gái"),
        ("grandmother", "bà"), ("home", "nhà"), ("bed", "giường"), ("window", "cửa sổ"),
        ("table", "cái bàn"), ("chair", "cái ghế"), ("blue", "màu xanh dương"), ("green", "màu xanh lá"),
        ("yellow", "màu vàng"), ("black", "màu đen"), ("white", "màu trắng"), ("orange", "quả cam"),
        ("water", "nước"), ("juice", "nước ép"), ("pizza", "bánh pizza"), ("pasta", "mì Ý"),
        ("popcorn", "bỏng ngô"), ("kite", "con diều"), ("run", "chạy"), ("jump", "nhảy"),
        ("sit", "ngồi"), ("stand", "đứng"), ("read", "đọc"), ("write", "viết"),
    ],
    2: [
        ("pasta", "mì Ý"), ("popcorn", "bỏng ngô"), ("pizza", "bánh pizza"), ("cake", "bánh kem"),
        ("balloon", "bóng bay"), ("present", "quà tặng"), ("party", "bữa tiệc"), ("hat", "mũ"),
        ("gift", "quà"), ("kite", "diều"), ("bike", "xe đạp"), ("kitten", "mèo con"),
        ("tree", "cây"), ("grass", "cỏ"), ("flower", "hoa"), ("ball", "quả bóng"),
        ("bench", "ghế dài"), ("fence", "hàng rào"), ("swing", "xích đu"), ("sail", "cánh buồm"),
        ("sand", "cát"), ("sea", "biển"), ("beach", "bãi biển"), ("sun", "mặt trời"),
        ("shell", "vỏ sò"), ("fish", "cá"), ("wave", "sóng"), ("boat", "thuyền"),
        ("rainbow", "cầu vồng"), ("river", "sông"), ("road", "con đường"), ("field", "cánh đồng"),
        ("farm", "trang trại"), ("cow", "con bò"), ("horse", "con ngựa"), ("tractor", "máy kéo"),
        ("barn", "chuồng trại"), ("question", "câu hỏi"), ("square", "hình vuông"), ("quiz", "bài đố"),
        ("desk", "bàn học"), ("book", "sách"), ("chair", "ghế"), ("blackboard", "bảng đen"),
        ("pencil", "bút chì"), ("ruler", "thước kẻ"), ("teacher", "giáo viên"), ("box", "hộp"),
        ("fox", "con cáo"), ("ox", "bò đực"), ("chicken", "con gà"), ("pig", "con lợn"),
        ("sheep", "con cừu"), ("duck", "con vịt"), ("farmer", "nông dân"), ("hay", "cỏ khô"),
        ("juice", "nước ép"), ("jelly", "thạch"), ("jam", "mứt"), ("spoon", "cái thìa"),
        ("fork", "cái dĩa"), ("plate", "cái đĩa"), ("knife", "con dao"), ("pot", "cái nồi"),
        ("stove", "bếp lò"), ("fridge", "tủ lạnh"), ("village", "ngôi làng"), ("van", "xe tải nhỏ"),
        ("volleyball", "bóng chuyền"), ("shop", "cửa hàng"), ("market", "chợ"), ("car", "xe ô tô"),
        ("school", "trường học"), ("yogurt", "sữa chua"), ("yam", "khoai lang"), ("yo-yo", "đồ chơi yo-yo"),
        ("bread", "bánh mì"), ("milk", "sữa"), ("apple", "quả táo"), ("orange", "quả cam"),
        ("butter", "bơ"), ("egg", "trứng"), ("sugar", "đường"), ("zoo", "sở thú"),
        ("zebu", "bò u"), ("zebra", "ngựa vằn"), ("lion", "sư tử"), ("tiger", "hổ"),
        ("monkey", "khỉ"), ("elephant", "voi"), ("giraffe", "hươu cao cổ"), ("penguin", "chim cánh cụt"),
        ("eleven", "mười một"), ("thirteen", "mười ba"), ("fourteen", "mười bốn"), ("fifteen", "mười lăm"),
        ("slide", "cầu trượt"), ("seesaw", "bập bênh"), ("sandbox", "hộp cát"), ("climbing frame", "khung leo trèo"),
        ("merry-go-round", "vòng quay ngựa gỗ"), ("basketball", "bóng rổ"), ("grapes", "nho"), ("coffee", "cà phê"),
        ("tea", "trà"), ("sandwich", "bánh sandwich"), ("waiter", "bồi bàn"), ("menu", "thực đơn"),
        ("number", "số"), ("addition", "phép cộng"), ("subtraction", "phép trừ"), ("multiplication", "phép nhân"),
        ("division", "phép chia"), ("equation", "phương trình"), ("calculator", "máy tính"), ("living room", "phòng khách"),
        ("bedroom", "phòng ngủ"), ("kitchen", "nhà bếp"), ("bathroom", "phòng tắm"), ("garden", "khu vườn"),
        ("shirts", "áo sơ mi"), ("shoes", "giày"), ("pants", "quần dài"), ("dress", "váy"),
        ("coat", "áo khoác"), ("scarf", "khăn quàng"), ("tent", "lều"), ("teapot", "ấm trà"),
        ("blanket", "chăn"), ("campfire", "lửa trại"), ("sleeping bag", "túi ngủ"), ("flashlight", "đèn pin"),
        ("backpack", "ba lô"), ("hike", "đi bộ đường dài"), ("nature", "thiên nhiên"),
    ],
    3: [
        ("hello", "xin chào"), ("hi", "chào"), ("goodbye", "tạm biệt"), ("name", "tên"),
        ("friend", "bạn bè"), ("body", "cơ thể"), ("head", "đầu"), ("hair", "tóc"),
        ("face", "khuôn mặt"), ("eye", "mắt"), ("ear", "tai"), ("nose", "mũi"),
        ("mouth", "miệng"), ("hand", "bàn tay"), ("arm", "cánh tay"), ("leg", "chân"),
        ("foot", "bàn chân"), ("hobby", "sở thích"), ("sing", "hát"), ("dance", "nhảy múa"),
        ("draw", "vẽ"), ("swim", "bơi"), ("cook", "nấu ăn"), ("read", "đọc"),
        ("school", "trường học"), ("classroom", "lớp học"), ("library", "thư viện"), ("playground", "sân chơi"),
        ("computer room", "phòng máy tính"), ("open", "mở"), ("close", "đóng"), ("stand up", "đứng lên"),
        ("sit down", "ngồi xuống"), ("listen", "nghe"), ("repeat", "nhắc lại"), ("book", "sách"),
        ("notebook", "vở"), ("pen", "bút mực"), ("pencil", "bút chì"), ("rubber", "cục tẩy"),
        ("ruler", "thước kẻ"), ("school bag", "cặp sách"), ("red", "màu đỏ"), ("blue", "màu xanh dương"),
        ("green", "màu xanh lá"), ("yellow", "màu vàng"), ("black", "màu đen"), ("white", "màu trắng"),
        ("brown", "màu nâu"), ("orange", "màu cam"), ("break time", "giờ ra chơi"), ("football", "bóng đá"),
        ("badminton", "cầu lông"), ("chess", "cờ vua"), ("skipping", "nhảy dây"), ("family", "gia đình"),
        ("father", "bố"), ("mother", "mẹ"), ("brother", "anh/em trai"), ("sister", "chị/em gái"),
        ("grandfather", "ông"), ("grandmother", "bà"), ("job", "nghề nghiệp"), ("doctor", "bác sĩ"),
        ("nurse", "y tá"), ("teacher", "giáo viên"), ("driver", "tài xế"), ("farmer", "nông dân"),
        ("house", "ngôi nhà"), ("living room", "phòng khách"), ("bedroom", "phòng ngủ"), ("kitchen", "nhà bếp"),
        ("bathroom", "phòng tắm"), ("garden", "khu vườn"), ("bed", "giường"), ("desk", "bàn học"),
        ("chair", "ghế"), ("table", "bàn"), ("sofa", "ghế sô pha"), ("lamp", "đèn"),
        ("pet", "thú cưng"), ("cat", "mèo"), ("dog", "chó"), ("bird", "chim"),
        ("fish", "cá"), ("rabbit", "thỏ"), ("toy", "đồ chơi"), ("doll", "búp bê"),
        ("robot", "người máy"), ("kite", "diều"), ("truck", "xe tải"), ("plane", "máy bay"),
        ("run", "chạy"), ("jump", "nhảy"), ("skate", "trượt patin"), ("cycle", "đạp xe"),
        ("park", "công viên"), ("zoo", "sở thú"), ("monkey", "khỉ"), ("tiger", "hổ"),
        ("elephant", "voi"), ("horse", "ngựa"), ("peacock", "chim công"),
    ],
    4: [
        ("friend", "bạn bè"), ("country", "quốc gia"), ("Australia", "Úc"), ("Japan", "Nhật Bản"),
        ("Malaysia", "Ma-lai-xi-a"), ("Singapore", "Xin-ga-po"), ("Thailand", "Thái Lan"), ("Viet Nam", "Việt Nam"),
        ("morning", "buổi sáng"), ("afternoon", "buổi chiều"), ("evening", "buổi tối"), ("night", "ban đêm"),
        ("get up", "thức dậy"), ("go to school", "đi học"), ("have breakfast", "ăn sáng"), ("go home", "về nhà"),
        ("go to bed", "đi ngủ"), ("Monday", "thứ Hai"), ("Tuesday", "thứ Ba"), ("Wednesday", "thứ Tư"),
        ("Thursday", "thứ Năm"), ("Friday", "thứ Sáu"), ("Saturday", "thứ Bảy"), ("Sunday", "Chủ nhật"),
        ("birthday", "sinh nhật"), ("party", "bữa tiệc"), ("cake", "bánh kem"), ("candle", "nến"),
        ("present", "quà tặng"), ("sing", "hát"), ("dance", "nhảy múa"), ("draw", "vẽ"),
        ("swim", "bơi"), ("skate", "trượt patin"), ("cook", "nấu ăn"), ("ride a bike", "đạp xe"),
        ("library", "thư viện"), ("computer room", "phòng máy tính"), ("music room", "phòng âm nhạc"), ("art room", "phòng mỹ thuật"),
        ("gym", "phòng thể dục"), ("playground", "sân chơi"), ("timetable", "thời khóa biểu"), ("subject", "môn học"),
        ("Vietnamese", "môn Tiếng Việt"), ("English", "môn Tiếng Anh"), ("maths", "môn Toán"), ("science", "môn Khoa học"),
        ("history", "môn Lịch sử"), ("art", "môn Mỹ thuật"), ("music", "môn Âm nhạc"), ("PE", "môn Thể dục"),
        ("sports day", "ngày hội thể thao"), ("football", "bóng đá"), ("basketball", "bóng rổ"), ("badminton", "cầu lông"),
        ("table tennis", "bóng bàn"), ("holiday", "kỳ nghỉ"), ("beach", "bãi biển"), ("mountain", "núi"),
        ("countryside", "vùng quê"), ("city", "thành phố"), ("flat", "căn hộ"), ("house", "ngôi nhà"),
        ("address", "địa chỉ"), ("street", "đường phố"), ("village", "ngôi làng"), ("teacher", "giáo viên"),
        ("doctor", "bác sĩ"), ("nurse", "y tá"), ("driver", "tài xế"), ("worker", "công nhân"),
        ("farmer", "nông dân"), ("pilot", "phi công"), ("singer", "ca sĩ"), ("tall", "cao"),
        ("short", "thấp"), ("slim", "mảnh mai"), ("strong", "khỏe"), ("young", "trẻ"),
        ("old", "già"), ("beautiful", "đẹp"), ("handsome", "đẹp trai"), ("do homework", "làm bài tập"),
        ("watch TV", "xem ti vi"), ("listen to music", "nghe nhạc"), ("read books", "đọc sách"), ("visit grandparents", "thăm ông bà"),
        ("go shopping", "đi mua sắm"), ("weather", "thời tiết"), ("sunny", "có nắng"), ("rainy", "có mưa"),
        ("windy", "có gió"), ("cloudy", "nhiều mây"), ("hot", "nóng"), ("cold", "lạnh"),
        ("market", "chợ"), ("supermarket", "siêu thị"), ("post office", "bưu điện"), ("cinema", "rạp chiếu phim"),
        ("shopping centre", "trung tâm mua sắm"), ("animal", "động vật"), ("kangaroo", "chuột túi"), ("crocodile", "cá sấu"),
        ("snake", "rắn"), ("summer camp", "trại hè"), ("tent", "lều"), ("campfire", "lửa trại"),
    ],
    5: [
        ("city", "thành phố"), ("class", "lớp học"), ("countryside", "vùng quê"), ("dolphin", "cá heo"),
        ("pink", "màu hồng"), ("sandwich", "bánh sandwich"), ("table tennis", "bóng bàn"), ("favourite", "yêu thích"),
        ("building", "tòa nhà"), ("tower", "tòa tháp"), ("flat", "căn hộ"), ("house", "ngôi nhà"),
        ("address", "địa chỉ"), ("floor", "tầng nhà"), ("foreign", "nước ngoài"), ("nationality", "quốc tịch"),
        ("America", "Mỹ"), ("Australia", "Úc"), ("Britain", "Anh"), ("Japan", "Nhật Bản"),
        ("Korea", "Hàn Quốc"), ("China", "Trung Quốc"), ("free time", "thời gian rảnh"), ("cartoon", "phim hoạt hình"),
        ("comic book", "truyện tranh"), ("camping", "cắm trại"), ("fishing", "câu cá"), ("surfing", "lướt sóng"),
        ("future", "tương lai"), ("job", "nghề nghiệp"), ("architect", "kiến trúc sư"), ("engineer", "kỹ sư"),
        ("writer", "nhà văn"), ("actor", "diễn viên"), ("police officer", "cảnh sát"), ("school room", "phòng học"),
        ("science lab", "phòng thí nghiệm"), ("library", "thư viện"), ("computer room", "phòng máy tính"), ("activity", "hoạt động"),
        ("club", "câu lạc bộ"), ("project", "dự án"), ("presentation", "bài thuyết trình"), ("classroom", "lớp học"),
        ("map", "bản đồ"), ("board", "bảng"), ("globe", "quả địa cầu"), ("dictionary", "từ điển"),
        ("outdoor", "ngoài trời"), ("picnic", "dã ngoại"), ("hiking", "đi bộ đường dài"), ("cycling", "đạp xe"),
        ("school trip", "chuyến đi của trường"), ("museum", "bảo tàng"), ("theatre", "nhà hát"), ("stadium", "sân vận động"),
        ("family time", "thời gian gia đình"), ("cook dinner", "nấu bữa tối"), ("clean the house", "dọn nhà"), ("watch a film", "xem phim"),
        ("Tet holiday", "Tết"), ("fireworks", "pháo hoa"), ("lucky money", "tiền lì xì"), ("decorate", "trang trí"),
        ("special day", "ngày đặc biệt"), ("Children's Day", "Tết thiếu nhi"), ("Teacher's Day", "Ngày Nhà giáo"), ("Independence Day", "Ngày Quốc khánh"),
        ("healthy", "khỏe mạnh"), ("exercise", "tập thể dục"), ("vegetable", "rau củ"), ("fruit", "trái cây"),
        ("fever", "sốt"), ("cough", "ho"), ("toothache", "đau răng"), ("stomach ache", "đau bụng"),
        ("headache", "đau đầu"), ("medicine", "thuốc"), ("season", "mùa"), ("spring", "mùa xuân"),
        ("summer", "mùa hè"), ("autumn", "mùa thu"), ("winter", "mùa đông"), ("weather", "thời tiết"),
        ("story", "câu chuyện"), ("fairy tale", "truyện cổ tích"), ("character", "nhân vật"), ("dragon", "rồng"),
        ("transport", "phương tiện giao thông"), ("bus", "xe buýt"), ("train", "tàu hỏa"), ("plane", "máy bay"),
        ("motorbike", "xe máy"), ("underground", "tàu điện ngầm"), ("place of interest", "địa điểm tham quan"), ("pagoda", "chùa"),
        ("temple", "đền"), ("bridge", "cây cầu"), ("island", "hòn đảo"), ("summer holiday", "kỳ nghỉ hè"),
    ],
    6: [
        ("calculator", "máy tính cầm tay"), ("compass", "com-pa"), ("equipment", "thiết bị"), ("excited", "hào hứng"),
        ("folder", "bìa đựng tài liệu"), ("greenhouse", "nhà kính"), ("gym", "phòng thể dục"), ("healthy", "khỏe mạnh"),
        ("history", "môn Lịch sử"), ("ink", "mực"), ("international", "quốc tế"), ("interview", "phỏng vấn"),
        ("kindergarten", "trường mẫu giáo"), ("locker", "tủ đồ"), ("mechanical pencil", "bút chì kim"), ("notepad", "sổ ghi chép"),
        ("pencil sharpener", "gọt bút chì"), ("playground", "sân chơi"), ("pocket money", "tiền tiêu vặt"), ("school bag", "cặp sách"),
        ("between", "ở giữa"), ("chest of drawers", "tủ ngăn kéo"), ("cooker", "nồi cơm điện"), ("country house", "nhà ở nông thôn"),
        ("crazy", "kỳ lạ"), ("cupboard", "tủ đựng đồ"), ("department store", "cửa hàng bách hóa"), ("dishwasher", "máy rửa bát"),
        ("flat", "căn hộ"), ("furniture", "đồ nội thất"), ("hall", "hành lang"), ("in front of", "ở phía trước"),
        ("next to", "bên cạnh"), ("shelf", "cái kệ"), ("sink", "bồn rửa"), ("strange", "lạ"),
        ("town house", "nhà phố"), ("wardrobe", "tủ quần áo"), ("appearance", "ngoại hình"), ("careful", "cẩn thận"),
        ("cheek", "má"), ("clever", "thông minh"), ("confident", "tự tin"), ("creative", "sáng tạo"),
        ("curly", "xoăn"), ("friendly", "thân thiện"), ("funny", "vui tính"), ("glasses", "kính"),
        ("hard-working", "chăm chỉ"), ("kind", "tốt bụng"), ("personality", "tính cách"), ("straight", "thẳng"),
        ("neighbourhood", "khu phố"), ("bakery", "tiệm bánh"), ("barber", "thợ cắt tóc"), ("cathedral", "nhà thờ lớn"),
        ("chemist's", "hiệu thuốc"), ("convenient", "thuận tiện"), ("factory", "nhà máy"), ("historic", "mang tính lịch sử"),
        ("memorial", "đài tưởng niệm"), ("museum", "bảo tàng"), ("pagoda", "chùa"), ("railway station", "nhà ga"),
        ("square", "quảng trường"), ("statue", "tượng"), ("temple", "đền"), ("wonder", "kỳ quan"),
        ("cave", "hang động"), ("desert", "sa mạc"), ("forest", "rừng"), ("island", "hòn đảo"),
        ("landscape", "phong cảnh"), ("mountain", "núi"), ("natural", "tự nhiên"), ("river", "sông"),
        ("waterfall", "thác nước"), ("holiday", "kỳ nghỉ"), ("apricot blossom", "hoa mai"), ("calendar", "lịch"),
        ("celebrate", "tổ chức"), ("decorate", "trang trí"), ("fireworks", "pháo hoa"), ("lucky money", "tiền lì xì"),
        ("peach blossom", "hoa đào"), ("relative", "họ hàng"), ("wish", "lời chúc"), ("television", "truyền hình"),
        ("cartoon", "phim hoạt hình"), ("channel", "kênh truyền hình"), ("comedy", "hài kịch"), ("documentary", "phim tài liệu"),
        ("viewer", "người xem"), ("weather forecast", "dự báo thời tiết"), ("sport", "thể thao"), ("competition", "cuộc thi"),
        ("equipment", "dụng cụ"), ("karate", "võ karate"), ("marathon", "cuộc chạy marathon"), ("racket", "vợt"),
        ("volleyball", "bóng chuyền"), ("city", "thành phố"), ("capital", "thủ đô"), ("continent", "châu lục"),
        ("landmark", "địa danh"), ("postcard", "bưu thiếp"), ("robot", "người máy"), ("automatic", "tự động"),
        ("wireless", "không dây"), ("recycle", "tái chế"), ("environment", "môi trường"), ("pollution", "ô nhiễm"),
    ],
    7: [
        ("belong to", "thuộc về"), ("benefit", "lợi ích"), ("bug", "con bọ"), ("cardboard", "bìa các tông"),
        ("dollhouse", "nhà búp bê"), ("gardening", "làm vườn"), ("glue", "keo dán"), ("horse riding", "cưỡi ngựa"),
        ("insect", "côn trùng"), ("jogging", "chạy bộ thư giãn"), ("making models", "làm mô hình"), ("maturity", "sự trưởng thành"),
        ("patient", "kiên nhẫn"), ("popular", "phổ biến"), ("responsibility", "trách nhiệm"), ("stress", "sự căng thẳng"),
        ("unusual", "khác thường"), ("valuable", "quý giá"), ("yoga", "yoga"), ("acne", "mụn trứng cá"),
        ("chapped lips", "môi nứt nẻ"), ("coloured vegetables", "rau củ nhiều màu"), ("dim light", "ánh sáng yếu"), ("disease", "bệnh"),
        ("eye drops", "thuốc nhỏ mắt"), ("fatty food", "đồ ăn nhiều dầu mỡ"), ("flu", "cúm"), ("healthy living", "sống lành mạnh"),
        ("sunburn", "cháy nắng"), ("tofu", "đậu phụ"), ("vitamin", "vitamin"), ("volunteer", "tình nguyện viên"),
        ("charity", "từ thiện"), ("community service", "dịch vụ cộng đồng"), ("donate", "quyên góp"), ("homeless", "vô gia cư"),
        ("nursing home", "viện dưỡng lão"), ("pick up litter", "nhặt rác"), ("plant trees", "trồng cây"), ("recycle", "tái chế"),
        ("tutor", "dạy kèm"), ("artist", "nghệ sĩ"), ("composer", "nhà soạn nhạc"), ("concert", "buổi hòa nhạc"),
        ("exhibition", "triển lãm"), ("landscape", "phong cảnh"), ("musical instrument", "nhạc cụ"), ("opera", "nhạc kịch"),
        ("portrait", "tranh chân dung"), ("puppet", "con rối"), ("sculpture", "tác phẩm điêu khắc"), ("ingredient", "nguyên liệu"),
        ("omelette", "trứng ốp lết"), ("pancake", "bánh kếp"), ("pepper", "hạt tiêu"), ("pork", "thịt lợn"),
        ("shrimp", "tôm"), ("spring roll", "nem rán"), ("sweet soup", "chè"), ("turmeric", "nghệ"),
        ("boarding school", "trường nội trú"), ("classmate", "bạn cùng lớp"), ("facility", "cơ sở vật chất"), ("laboratory", "phòng thí nghiệm"),
        ("library", "thư viện"), ("playground", "sân chơi"), ("school garden", "vườn trường"), ("traffic jam", "tắc đường"),
        ("cycle lane", "làn đường xe đạp"), ("helmet", "mũ bảo hiểm"), ("pedestrian", "người đi bộ"), ("road sign", "biển báo giao thông"),
        ("rush hour", "giờ cao điểm"), ("traffic light", "đèn giao thông"), ("vehicle", "phương tiện"), ("documentary", "phim tài liệu"),
        ("comedy", "phim hài"), ("horror film", "phim kinh dị"), ("science fiction", "khoa học viễn tưởng"), ("animation", "phim hoạt hình"),
        ("plot", "cốt truyện"), ("review", "bài đánh giá"), ("festival", "lễ hội"), ("parade", "cuộc diễu hành"),
        ("celebrate", "tổ chức kỷ niệm"), ("costume", "trang phục"), ("firework", "pháo hoa"), ("renewable", "có thể tái tạo"),
        ("solar energy", "năng lượng mặt trời"), ("wind power", "điện gió"), ("hydropower", "thủy điện"), ("source", "nguồn"),
        ("consume", "tiêu thụ"), ("electricity", "điện"), ("eco-friendly", "thân thiện môi trường"), ("flying car", "ô tô bay"),
        ("driverless", "không người lái"), ("hyperloop", "tàu siêu tốc"), ("teleporter", "máy dịch chuyển"), ("English-speaking country", "quốc gia nói tiếng Anh"),
        ("native speaker", "người bản ngữ"), ("symbol", "biểu tượng"), ("castle", "lâu đài"), ("kangaroo", "chuột túi"),
    ],
    8: [
        ("balance", "sự cân bằng"), ("bracelet", "vòng đeo tay"), ("crazy", "rất thích"), ("cruel", "độc ác"),
        ("detest", "căm ghét"), ("DIY", "tự làm đồ"), ("fancy", "thích"), ("fold", "gấp"),
        ("fond", "yêu thích"), ("keen", "say mê"), ("keep in touch", "giữ liên lạc"), ("kit", "bộ đồ nghề"),
        ("leisure", "thời gian rảnh"), ("message", "gửi tin nhắn"), ("muscle", "cơ bắp"), ("origami", "nghệ thuật gấp giấy"),
        ("outdoors", "ngoài trời"), ("prefer", "thích hơn"), ("puzzle", "câu đố"), ("resort", "khu nghỉ dưỡng"),
        ("snowboarding", "trượt tuyết bằng ván"), ("stay in shape", "giữ dáng"), ("cattle", "gia súc"), ("crop", "cây trồng"),
        ("harvest", "vụ thu hoạch"), ("herd", "đàn gia súc"), ("load", "chất hàng"), ("orchard", "vườn cây ăn quả"),
        ("pasture", "đồng cỏ"), ("paddy field", "ruộng lúa"), ("rural", "thuộc nông thôn"), ("vast", "rộng lớn"),
        ("teenager", "thiếu niên"), ("forum", "diễn đàn"), ("notification", "thông báo"), ("pressure", "áp lực"),
        ("bully", "bắt nạt"), ("confidence", "sự tự tin"), ("account", "tài khoản"), ("user name", "tên người dùng"),
        ("ethnic group", "dân tộc"), ("communal house", "nhà rông"), ("costume", "trang phục"), ("folk dance", "điệu múa dân gian"),
        ("minority", "thiểu số"), ("stilt house", "nhà sàn"), ("terraced field", "ruộng bậc thang"), ("tradition", "truyền thống"),
        ("custom", "phong tục"), ("worship", "thờ cúng"), ("offering", "lễ vật"), ("ancestor", "tổ tiên"),
        ("ceremony", "nghi lễ"), ("lifestyle", "lối sống"), ("habit", "thói quen"), ("community", "cộng đồng"),
        ("facility", "cơ sở vật chất"), ("generation", "thế hệ"), ("environmental protection", "bảo vệ môi trường"), ("endangered species", "loài nguy cấp"),
        ("habitat", "môi trường sống"), ("pollutant", "chất gây ô nhiễm"), ("deforestation", "nạn phá rừng"), ("global warming", "sự nóng lên toàn cầu"),
        ("shopping", "mua sắm"), ("bargain", "mặc cả"), ("complaint", "lời phàn nàn"), ("convenience store", "cửa hàng tiện lợi"),
        ("customer", "khách hàng"), ("discount", "giảm giá"), ("goods", "hàng hóa"), ("item", "món hàng"),
        ("price tag", "nhãn giá"), ("voucher", "phiếu giảm giá"), ("natural disaster", "thiên tai"), ("earthquake", "động đất"),
        ("flood", "lũ lụt"), ("landslide", "sạt lở đất"), ("storm", "bão"), ("typhoon", "bão nhiệt đới"),
        ("victim", "nạn nhân"), ("warning", "cảnh báo"), ("communication", "giao tiếp"), ("emoji", "biểu tượng cảm xúc"),
        ("video conference", "họp trực tuyến"), ("social network", "mạng xã hội"), ("technology", "công nghệ"), ("invention", "phát minh"),
        ("experiment", "thí nghiệm"), ("laboratory", "phòng thí nghiệm"), ("inventor", "nhà phát minh"), ("science fiction", "khoa học viễn tưởng"),
        ("Earth", "Trái Đất"), ("spaceship", "tàu vũ trụ"), ("creature", "sinh vật"), ("planet", "hành tinh"),
        ("alien", "người ngoài hành tinh"), ("telescope", "kính thiên văn"), ("rocket", "tên lửa"), ("galaxy", "thiên hà"),
        ("gravity", "trọng lực"), ("atmosphere", "khí quyển"),
    ],
    9: [
        ("artisan", "nghệ nhân"), ("community", "cộng đồng"), ("electrician", "thợ điện"), ("facility", "cơ sở vật chất"),
        ("firefighter", "lính cứu hỏa"), ("fragrance", "hương thơm"), ("function", "chức năng"), ("handicraft", "đồ thủ công"),
        ("original", "nguyên bản"), ("preserve", "bảo tồn"), ("speciality", "đặc sản"), ("suburb", "ngoại ô"),
        ("tourist attraction", "điểm thu hút du khách"), ("bustling", "nhộn nhịp"), ("concrete jungle", "rừng bê tông"), ("congested", "tắc nghẽn"),
        ("construction site", "công trường"), ("downtown", "trung tâm thành phố"), ("hygiene", "vệ sinh"), ("liveable", "đáng sống"),
        ("metro", "tàu điện ngầm"), ("pricey", "đắt đỏ"), ("rush hour", "giờ cao điểm"), ("additional", "bổ sung"),
        ("anxiety", "sự lo âu"), ("assignment", "bài tập"), ("counsellor", "cố vấn"), ("deadline", "hạn chót"),
        ("delay", "trì hoãn"), ("distraction", "sự xao nhãng"), ("manage", "quản lý"), ("priority", "ưu tiên"),
        ("craft village", "làng nghề"), ("historical", "thuộc lịch sử"), ("memorial", "đài tưởng niệm"), ("experience", "trải nghiệm"),
        ("adventure", "cuộc phiêu lưu"), ("explore", "khám phá"), ("lifestyle", "lối sống"), ("vendor", "người bán hàng rong"),
        ("extended family", "gia đình nhiều thế hệ"), ("generation", "thế hệ"), ("traditional", "truyền thống"), ("modern", "hiện đại"),
        ("natural wonder", "kỳ quan thiên nhiên"), ("cave", "hang động"), ("valley", "thung lũng"), ("limestone", "đá vôi"),
        ("landscape", "phong cảnh"), ("tourism", "du lịch"), ("destination", "điểm đến"), ("itinerary", "lịch trình"),
        ("souvenir", "quà lưu niệm"), ("tour guide", "hướng dẫn viên"), ("package tour", "tour trọn gói"), ("world Englishes", "các biến thể tiếng Anh"),
        ("accent", "giọng nói"), ("dialect", "phương ngữ"), ("bilingual", "song ngữ"), ("fluent", "trôi chảy"),
        ("planet", "hành tinh"), ("ecosystem", "hệ sinh thái"), ("biodiversity", "đa dạng sinh học"), ("climate change", "biến đổi khí hậu"),
        ("greenhouse gas", "khí nhà kính"), ("electronic device", "thiết bị điện tử"), ("charger", "bộ sạc"), ("earphones", "tai nghe"),
        ("screen", "màn hình"), ("software", "phần mềm"), ("career", "nghề nghiệp"), ("choice", "lựa chọn"),
        ("application", "đơn xin việc"), ("qualification", "bằng cấp"), ("skill", "kỹ năng"), ("salary", "lương"),
        ("interview", "phỏng vấn"), ("strength", "điểm mạnh"), ("weakness", "điểm yếu"),
    ],
    10: [
        ("homemaker", "người nội trợ"), ("breadwinner", "trụ cột gia đình"), ("earn money", "kiếm tiền"), ("laundry", "việc giặt là"),
        ("life skill", "kỹ năng sống"), ("take responsibility", "chịu trách nhiệm"), ("take care of", "chăm sóc"), ("routine task", "việc hằng ngày"),
        ("washing-up", "việc rửa bát"), ("grocery", "hàng tạp hóa"), ("gratitude", "lòng biết ơn"), ("bond", "sự gắn bó"),
        ("character", "tính cách"), ("quality", "phẩm chất"), ("chore", "việc nhà"), ("environment", "môi trường"),
        ("chemical", "hóa chất"), ("issue", "vấn đề"), ("litter", "rác"), ("material", "vật liệu"),
        ("organic", "hữu cơ"), ("organise", "tổ chức"), ("reduce", "giảm"), ("protect", "bảo vệ"),
        ("destroy", "phá hủy"), ("recycle", "tái chế"), ("sort", "phân loại"), ("exhibition", "triển lãm"),
        ("attract", "thu hút"), ("traditional music", "nhạc truyền thống"), ("pop singer", "ca sĩ nhạc pop"), ("upload", "tải lên"),
        ("musician", "nhạc sĩ"), ("argument", "lập luận"), ("audience", "khán giả"), ("concert", "buổi hòa nhạc"),
        ("composer", "nhà soạn nhạc"), ("single", "đĩa đơn"), ("trumpet", "kèn trumpet"), ("volunteer", "tình nguyện viên"),
        ("community", "cộng đồng"), ("donate", "quyên góp"), ("remote", "xa xôi"), ("various", "đa dạng"),
        ("charity", "từ thiện"), ("orphanage", "trại trẻ mồ côi"), ("benefit", "lợi ích"), ("invention", "phát minh"),
        ("inventor", "nhà phát minh"), ("device", "thiết bị"), ("patent", "bằng sáng chế"), ("portable", "dễ mang theo"),
        ("smartphone", "điện thoại thông minh"), ("processor", "bộ xử lý"), ("gender equality", "bình đẳng giới"), ("equal", "bình đẳng"),
        ("opportunity", "cơ hội"), ("discrimination", "sự phân biệt đối xử"), ("leader", "lãnh đạo"), ("domestic violence", "bạo lực gia đình"),
        ("international organisation", "tổ chức quốc tế"), ("ASEAN", "Hiệp hội các quốc gia Đông Nam Á"), ("United Nations", "Liên Hợp Quốc"), ("member state", "quốc gia thành viên"),
        ("cooperate", "hợp tác"), ("promote", "thúc đẩy"), ("digital learning", "học tập số"), ("online course", "khóa học trực tuyến"),
        ("blended learning", "học kết hợp"), ("software", "phần mềm"), ("tablet", "máy tính bảng"), ("protecting the environment", "bảo vệ môi trường"),
        ("global warming", "sự nóng lên toàn cầu"), ("deforestation", "phá rừng"), ("endangered species", "loài nguy cấp"), ("wildlife", "động vật hoang dã"),
        ("ecotourism", "du lịch sinh thái"), ("tourist", "du khách"), ("destination", "điểm đến"), ("sustainable", "bền vững"),
        ("local people", "người dân địa phương"), ("natural habitat", "môi trường sống tự nhiên"),
    ],
    11: [
        ("antibiotic", "thuốc kháng sinh"), ("bacteria", "vi khuẩn"), ("balanced", "cân bằng"), ("cut down on", "cắt giảm"),
        ("diameter", "đường kính"), ("disease", "bệnh"), ("energy", "năng lượng"), ("examine", "khám bệnh"),
        ("fitness", "sự khỏe mạnh"), ("food poisoning", "ngộ độc thực phẩm"), ("germ", "vi trùng"), ("infection", "sự nhiễm trùng"),
        ("ingredient", "thành phần"), ("life expectancy", "tuổi thọ"), ("muscle", "cơ bắp"), ("nutrient", "chất dinh dưỡng"),
        ("organism", "sinh vật"), ("press-up", "động tác chống đẩy"), ("recipe", "công thức nấu ăn"), ("regular", "đều đặn"),
        ("strength", "sức mạnh"), ("treatment", "sự điều trị"), ("tuberculosis", "bệnh lao"), ("virus", "vi-rút"),
        ("work out", "tập thể dục"), ("adapt", "thích nghi"), ("argument", "tranh luận"), ("characteristic", "đặc điểm"),
        ("conflict", "xung đột"), ("curious", "tò mò"), ("digital native", "người sinh ra trong thời đại số"), ("extended family", "gia đình nhiều thế hệ"),
        ("freedom", "sự tự do"), ("generation gap", "khoảng cách thế hệ"), ("honesty", "sự trung thực"), ("individualism", "chủ nghĩa cá nhân"),
        ("nuclear family", "gia đình hạt nhân"), ("screen time", "thời gian dùng màn hình"), ("city dweller", "cư dân thành phố"), ("cycle path", "đường cho xe đạp"),
        ("efficiently", "hiệu quả"), ("high-rise", "cao tầng"), ("infrastructure", "cơ sở hạ tầng"), ("interact", "tương tác"),
        ("liveable", "đáng sống"), ("pedestrian", "người đi bộ"), ("privacy", "sự riêng tư"), ("roof garden", "vườn trên mái"),
        ("skyscraper", "nhà chọc trời"), ("ASEAN", "Hiệp hội các quốc gia Đông Nam Á"), ("charter", "hiến chương"), ("bloc", "khối liên minh"),
        ("association", "hiệp hội"), ("economy", "nền kinh tế"), ("identity", "bản sắc"), ("climate change", "biến đổi khí hậu"),
        ("global warming", "sự nóng lên toàn cầu"), ("carbon footprint", "dấu chân carbon"), ("greenhouse gas", "khí nhà kính"), ("emission", "khí thải"),
        ("renewable energy", "năng lượng tái tạo"), ("heritage", "di sản"), ("preserve", "bảo tồn"), ("restore", "phục hồi"),
        ("relic", "di tích"), ("intangible", "phi vật thể"), ("folk song", "dân ca"), ("school-leaver", "học sinh tốt nghiệp phổ thông"),
        ("vocational school", "trường nghề"), ("qualification", "bằng cấp"), ("apprenticeship", "học nghề"), ("undergraduate", "sinh viên đại học"),
        ("independent", "độc lập"), ("self-reliant", "tự lập"), ("time management", "quản lý thời gian"), ("decision-making", "ra quyết định"),
        ("social issue", "vấn đề xã hội"), ("poverty", "nghèo đói"), ("unemployment", "thất nghiệp"), ("bullying", "bắt nạt"),
        ("ecosystem", "hệ sinh thái"), ("biodiversity", "đa dạng sinh học"), ("habitat", "môi trường sống"), ("species", "loài"),
        ("conservation", "bảo tồn"), ("extinction", "sự tuyệt chủng"),
    ],
    12: [
        ("account", "câu chuyện"), ("achievement", "thành tựu"), ("admire", "ngưỡng mộ"), ("adopt", "nhận con nuôi"),
        ("animated", "hoạt hình"), ("attack", "tấn công"), ("attend school", "đi học"), ("battle", "trận chiến"),
        ("biography", "tiểu sử"), ("biological", "ruột thịt"), ("bond", "gắn bó"), ("cancer", "ung thư"),
        ("carry out", "tiến hành"), ("childhood", "tuổi thơ"), ("Communist Party of Viet Nam", "Đảng Cộng sản Việt Nam"), ("death", "cái chết"),
        ("defeat", "đánh bại"), ("devote to", "cống hiến cho"), ("drop out", "bỏ học"), ("enemy", "kẻ thù"),
        ("genius", "thiên tài"), ("hero", "anh hùng"), ("marriage", "hôn nhân"), ("military", "quân đội"),
        ("pass away", "qua đời"), ("poem", "bài thơ"), ("poetry", "thơ ca"), ("resign", "từ chức"),
        ("resistance war", "cuộc kháng chiến"), ("rule", "trị vì"), ("youth", "tuổi trẻ"), ("multicultural", "đa văn hóa"),
        ("custom", "phong tục"), ("diversity", "sự đa dạng"), ("identity", "bản sắc"), ("immigrant", "người nhập cư"),
        ("integrate", "hòa nhập"), ("cuisine", "ẩm thực"), ("festival", "lễ hội"), ("tradition", "truyền thống"),
        ("green living", "lối sống xanh"), ("eco-friendly", "thân thiện môi trường"), ("reusable", "có thể tái sử dụng"), ("biodegradable", "phân hủy sinh học"),
        ("carbon footprint", "dấu chân carbon"), ("household waste", "rác thải sinh hoạt"), ("urbanisation", "đô thị hóa"), ("migrate", "di cư"),
        ("overcrowding", "quá tải dân cư"), ("housing", "nhà ở"), ("unemployment", "thất nghiệp"), ("infrastructure", "cơ sở hạ tầng"),
        ("world of work", "thế giới việc làm"), ("qualification", "bằng cấp"), ("candidate", "ứng viên"), ("recruit", "tuyển dụng"),
        ("employer", "nhà tuyển dụng"), ("employee", "nhân viên"), ("salary", "lương"), ("workplace", "nơi làm việc"),
        ("artificial intelligence", "trí tuệ nhân tạo"), ("algorithm", "thuật toán"), ("automation", "tự động hóa"), ("chatbot", "trợ lý trò chuyện"),
        ("virtual reality", "thực tế ảo"), ("robotics", "ngành rô-bốt"), ("mass media", "truyền thông đại chúng"), ("broadcast", "phát sóng"),
        ("headline", "tiêu đề tin"), ("journalist", "nhà báo"), ("newsfeed", "bảng tin"), ("podcast", "tệp âm thanh trực tuyến"),
        ("social media", "mạng xã hội"), ("wildlife conservation", "bảo tồn động vật hoang dã"), ("endangered", "có nguy cơ tuyệt chủng"), ("poaching", "săn bắt trái phép"),
        ("habitat loss", "mất môi trường sống"), ("sanctuary", "khu bảo tồn"), ("species", "loài"), ("career path", "con đường sự nghiệp"),
        ("mentor", "người cố vấn"), ("internship", "kỳ thực tập"), ("promotion", "sự thăng chức"), ("lifelong learning", "học tập suốt đời"),
        ("adult education", "giáo dục người lớn"), ("distance learning", "học từ xa"), ("upskill", "nâng cao kỹ năng"), ("self-study", "tự học"),
    ],
}


TOPIC_RULES = [
    ("Động vật", ["dog", "cat", "kitten", "monkey", "tiger", "lion", "horse", "duck", "fish", "chicken", "pig", "sheep", "rabbit", "bird", "elephant", "zebra", "zebu", "giraffe", "penguin", "kangaroo", "crocodile", "snake", "dolphin", "goat", "cow", "ox", "fox", "peacock", "wildlife", "species", "animal", "pet", "creature", "cattle", "herd", "zoo", "bug", "insect", "con vật", "động vật", "loài", "sở thú"]),
    ("Trường học", ["book", "read", "school", "teacher", "class", "library", "pencil", "pen", "ruler", "desk", "notebook", "blackboard", "board", "homework", "exam", "education", "learning", "study", "tutor", "maths", "science", "history", "dictionary", "globe", "project", "presentation", "laboratory", "question", "quiz", "subject", "từ điển", "bài tập", "giáo viên", "học", "môn"]),
    ("Gia đình", ["family", "mother", "father", "brother", "sister", "grandmother", "grandfather", "relative", "grandparents", "children's day", "gia đình", "anh/em", "chị/em"]),
    ("Đồ ăn và đồ uống", ["food", "cake", "pizza", "pasta", "popcorn", "bread", "milk", "juice", "rice", "noodles", "sandwich", "egg", "sugar", "tea", "coffee", "fruit", "vegetable", "banana", "apple", "orange", "lemon", "grapes", "yogurt", "yam", "butter", "jelly", "jam", "pancake", "omelette", "pepper", "pork", "shrimp", "spring roll", "sweet soup", "turmeric", "tofu", "ingredient", "recipe", "cuisine", "grocery", "groceries", "nuts", "menu", "đồ ăn", "bánh", "cơm", "món", "thực phẩm"]),
    ("Giao thông", ["car", "bike", "bus", "train", "plane", "motorbike", "truck", "van", "boat", "transport", "traffic", "road", "metro", "vehicle", "railway", "cycle lane", "pedestrian", "helmet", "underground", "flying car", "driverless", "hyperloop", "teleporter", "spaceship", "rocket", "sail", "rush hour", "bridge", "phương tiện", "xe", "tàu", "đường"]),
    ("Thiên nhiên và môi trường", ["tree", "flower", "leaf", "garden", "forest", "river", "sea", "beach", "mountain", "lake", "field", "farm", "grass", "sand", "shell", "rainbow", "sun", "wave", "waterfall", "island", "desert", "landscape", "orchard", "pasture", "paddy field", "water", "hay", "barn", "park", "vast", "apricot blossom", "peach blossom", "environment", "nature", "climate", "planet", "earth", "habitat", "biodiversity", "ecosystem", "greenhouse", "natural", "crop", "harvest", "organic", "chemical", "emission", "energy", "nông", "rừng", "biển", "núi", "sông", "thiên nhiên", "môi trường"]),
    ("Thể thao và hoạt động", ["football", "basketball", "volleyball", "badminton", "table tennis", "sport", "swim", "run", "jump", "skate", "cycle", "hike", "hiking", "cycling", "surfing", "fishing", "camping", "yoga", "exercise", "fitness", "karate", "marathon", "racket", "snowboarding", "press-up", "star jump", "playground", "slide", "swing", "seesaw", "sandbox", "climbing frame", "merry-go-round", "goal", "ball", "stay in shape", "campfire", "club", "đạp xe", "bơi", "chạy", "thể thao"]),
    ("Âm nhạc và nghệ thuật", ["music", "song", "sing", "dance", "concert", "instrument", "trumpet", "opera", "musician", "composer", "singer", "music room", "art room", "folk dance", "folk song", "artist", "portrait", "puppet", "sculpture", "origami", "comedy", "animated", "animation", "nhạc", "hát", "múa", "nghệ thuật", "hài"]),
    ("Sức khỏe", ["doctor", "nurse", "medicine", "health", "healthy", "disease", "fever", "cough", "toothache", "stomach ache", "headache", "virus", "bacteria", "infection", "antibiotic", "fitness", "food poisoning", "germ", "nutrient", "organism", "treatment", "tuberculosis", "life expectancy", "sunburn", "acne", "eye drops", "flu", "vitamin", "chapped lips", "dim light", "muscle", "hygiene", "sức khỏe", "bệnh", "thuốc"]),
    ("Công nghệ", ["computer", "robot", "technology", "device", "software", "smartphone", "tablet", "artificial intelligence", "algorithm", "chatbot", "automation", "robotics", "virtual reality", "digital", "online", "blended learning", "video conference", "social network", "social media", "emoji", "screen", "charger", "earphones", "wireless", "automatic", "khoa học", "công nghệ", "máy tính"]),
    ("Nhà cửa và thành phố", ["city", "building", "tower", "house", "flat", "room", "street", "infrastructure", "suburb", "downtown", "neighbourhood", "skyscraper", "high-rise", "roof garden", "construction site", "concrete jungle", "urbanisation", "housing", "kitchen", "bathroom", "bedroom", "living room", "hall", "town house", "country house", "communal house", "stilt house", "village", "post office", "capital", "congested", "facility", "đô thị", "thành phố", "nhà", "phòng"]),
    ("Nghề nghiệp", ["job", "career", "work", "worker", "engineer", "pilot", "architect", "writer", "actor", "police officer", "driver", "farmer", "artisan", "electrician", "firefighter", "barber", "homemaker", "leader", "candidate", "recruit", "employer", "employee", "salary", "interview", "qualification", "workplace", "internship", "mentor", "promotion", "apprenticeship", "school-leaver", "vocational", "undergraduate", "nghề", "công việc", "lương"]),
    ("Lễ hội và ngày đặc biệt", ["holiday", "Tet", "festival", "party", "birthday", "firework", "fireworks", "celebrate", "special day", "candle", "present", "gift", "balloon", "lucky money", "decorate", "parade", "costume", "ceremony", "offering", "worship", "bữa tiệc", "lễ", "quà"]),
    ("Mua sắm", ["money", "shop", "market", "shopping", "price", "discount", "customer", "goods", "item", "voucher", "bargain", "convenience store", "department store", "supermarket", "speciality", "vendor", "souvenir", "mua", "chợ", "cửa hàng", "hàng hóa"]),
    ("Quốc gia và thế giới", ["country", "ASEAN", "Viet Nam", "Australia", "Japan", "Malaysia", "Singapore", "Thailand", "America", "Britain", "Korea", "China", "United Nations", "international", "nationality", "foreign", "native speaker", "English-speaking country", "continent", "world", "bloc", "economy", "quốc gia", "quốc tế"]),
    ("Màu sắc", ["red", "blue", "green", "yellow", "black", "white", "brown", "pink", "colour", "color", "màu"]),
    ("Thời gian và mùa", ["morning", "afternoon", "evening", "night", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "calendar", "season", "spring", "summer", "autumn", "winter", "time", "deadline", "schedule", "future", "tuần", "mùa", "thời gian"]),
    ("Thời tiết và thiên tai", ["sunny", "rainy", "windy", "cloudy", "hot", "cold", "weather", "storm", "stormy", "typhoon", "flood", "earthquake", "landslide", "natural disaster", "warning", "thời tiết", "bão", "lũ"]),
    ("Đồ vật hằng ngày", ["bed", "table", "chair", "sofa", "lamp", "window", "door", "gate", "cup", "can", "bag", "box", "bench", "fence", "spoon", "fork", "plate", "knife", "pot", "stove", "fridge", "teapot", "blanket", "tent", "sleeping bag", "flashlight", "backpack", "locker", "wardrobe", "cupboard", "shelf", "sink", "furniture", "chest of drawers", "dishwasher", "cooker", "equipment", "folder", "notepad", "ink", "compass", "calculator", "map", "rubber", "glue", "material", "source", "symbol", "bell", "laundry", "đồ", "bàn", "ghế", "tủ", "bếp"]),
    ("Trang phục", ["shirt", "shirts", "shoe", "shoes", "shorts", "pants", "dress", "coat", "scarf", "hat", "glasses", "bracelet", "clothes", "trang phục", "quần", "áo", "giày"]),
    ("Giao tiếp và truyền thông", ["hello", "hi", "goodbye", "name", "friend", "communication", "message", "keep in touch", "broadcast", "headline", "journalist", "newsfeed", "podcast", "media", "account", "forum", "notification", "user name", "accent", "dialect", "bilingual", "fluent", "channel", "television", "upload", "chào", "giao tiếp", "tin"]),
    ("Cơ thể và ngoại hình", ["eye", "ear", "nose", "mouth", "face", "head", "hair", "hand", "arm", "leg", "foot", "body", "cheek", "appearance", "tall", "short", "slim", "strong", "young", "old", "beautiful", "handsome", "curly", "straight", "girl", "cơ thể", "ngoại hình"]),
    ("Tính cách và cảm xúc", ["happy", "excited", "confident", "friendly", "funny", "kind", "careful", "clever", "creative", "hard-working", "patient", "popular", "valuable", "unusual", "strange", "crazy", "curious", "honesty", "maturity", "responsibility", "stress", "anxiety", "pressure", "confidence", "admire", "gratitude", "quality", "personality", "weakness", "strength", "balanced", "regular", "keen", "cruel", "detest", "victim", "bond", "wish", "complaint", "thích", "vui", "tự tin", "tốt bụng"]),
    ("Số đếm và toán học", ["eleven", "thirteen", "fourteen", "fifteen", "number", "addition", "subtraction", "multiplication", "division", "equation", "twenty", "thirty", "ninety", "hundred", "square", "số", "phép"]),
    ("Đồ chơi và giải trí", ["toy", "doll", "dollhouse", "teddy bear", "kite", "yo-yo", "puzzle", "chess", "skipping", "cartoon", "comic book", "fairy tale", "story", "character", "dragon", "animation", "plot", "review", "hobby", "leisure", "game", "making models", "audience", "đồ chơi", "truyện", "sở thích"]),
    ("Du lịch và địa điểm", ["tourism", "tourist", "destination", "itinerary", "tour guide", "package tour", "landmark", "postcard", "place of interest", "pagoda", "temple", "museum", "theatre", "stadium", "cinema", "castle", "cathedral", "memorial", "statue", "wonder", "cave", "resort", "summer camp", "school trip", "picnic", "du lịch", "địa điểm"]),
    ("Bảo vệ môi trường", ["protect", "destroy", "recycle", "reduce", "pollution", "pollutant", "deforestation", "global warming", "greenhouse gas", "carbon footprint", "renewable", "solar energy", "wind power", "hydropower", "eco-friendly", "sustainable", "endangered", "conservation", "extinction", "preserve", "restore", "sanctuary", "habitat loss", "poaching", "litter", "reusable", "bảo vệ", "tái chế", "bảo tồn"]),
    ("Khoa học và vũ trụ", ["invention", "inventor", "experiment", "patent", "portable", "processor", "telescope", "galaxy", "gravity", "atmosphere", "alien", "science fiction", "balance", "limestone", "phát minh", "thí nghiệm", "thiên hà"]),
    ("Cộng đồng và xã hội", ["community", "charity", "volunteer", "donate", "homeless", "nursing home", "pick up litter", "plant trees", "service", "orphanage", "benefit", "support", "develop", "appreciate", "encourage", "achieve", "nurture", "local people", "counsellor", "xã hội", "cộng đồng", "tình nguyện"]),
    ("Văn hóa - lịch sử", ["culture", "custom", "tradition", "heritage", "relic", "intangible", "identity", "ethnic group", "minority", "multicultural", "diversity", "immigrant", "integrate", "biography", "poetry", "poem", "hero", "genius", "battle", "military", "resistance war", "historical", "ancestor", "youth", "marriage", "biological", "death", "enemy", "truyền thống", "di sản", "văn hóa", "lịch sử"]),
    ("Kỹ năng sống và vấn đề xã hội", ["freedom", "conflict", "generation gap", "individualism", "screen time", "privacy", "social issue", "poverty", "unemployment", "bullying", "gender equality", "equal", "opportunity", "discrimination", "domestic violence", "problem", "issue", "choice", "priority", "decision-making", "time management", "independent", "self-reliant", "argument", "bully", "generation", "skill", "habit", "overcrowding", "xung đột", "vấn đề", "lựa chọn"]),
    ("Hành động thường ngày", ["open", "close", "stand", "sit", "listen", "repeat", "write", "draw", "cook", "watch", "visit", "go", "get up", "have breakfast", "take care", "manage", "adapt", "interact", "explore", "attend", "carry out", "devote", "drop out", "pass away", "resign", "rule", "attract", "organise", "promote", "sort", "adopt", "defeat", "migrate", "cut down on", "consume", "belong to", "delay", "load", "upskill", "attack", "function", "action", "hoạt động"]),
    ("Vị trí và mô tả", ["between", "in front of", "next to", "convenient", "remote", "various", "original", "fragrance", "đằng trước", "bên cạnh", "ở giữa"]),
]


EMOJI_RULES = [
    (["dog", "cat", "kitten", "monkey", "tiger", "lion", "horse", "duck", "fish", "chicken", "pig", "sheep", "rabbit", "bird", "elephant", "zebra", "zebu", "giraffe", "penguin", "kangaroo", "crocodile", "snake", "dolphin", "goat", "cow", "ox", "fox", "peacock", "wildlife", "species", "animal", "pet", "creature", "cattle", "herd", "con vật", "động vật", "loài"], "🐾"),
    (["book", "read", "school", "teacher", "class", "library", "pencil", "pen", "ruler", "desk", "notebook", "blackboard", "board", "homework", "exam", "education", "learning", "study", "tutor", "maths", "science", "history", "dictionary", "globe", "project", "presentation", "laboratory", "question", "quiz", "subject", "từ điển", "bài tập", "giáo viên", "học", "môn"], "📚"),
    (["family", "mother", "father", "brother", "sister", "grandmother", "grandfather", "relative", "grandparents", "children's day", "gia đình", "mẹ", "bố", "ông", "bà"], "👨‍👩‍👧‍👦"),
    (["food", "cake", "pizza", "pasta", "popcorn", "bread", "milk", "juice", "rice", "noodles", "sandwich", "egg", "sugar", "tea", "coffee", "fruit", "vegetable", "banana", "apple", "orange", "lemon", "grapes", "yogurt", "yam", "butter", "jelly", "jam", "pancake", "omelette", "pepper", "pork", "shrimp", "spring roll", "sweet soup", "turmeric", "tofu", "ingredient", "recipe", "cuisine", "grocery", "groceries", "đồ ăn", "bánh", "cơm", "món", "thực phẩm"], "🍽️"),
    (["car", "bike", "bus", "train", "plane", "motorbike", "truck", "van", "boat", "transport", "traffic", "road", "metro", "vehicle", "railway", "cycle lane", "pedestrian", "helmet", "underground", "flying car", "driverless", "hyperloop", "teleporter", "spaceship", "rocket", "phương tiện", "xe", "tàu", "đường"], "🚗"),
    (["tree", "flower", "leaf", "garden", "forest", "river", "sea", "beach", "mountain", "lake", "field", "farm", "grass", "sand", "shell", "rainbow", "sun", "wave", "waterfall", "island", "desert", "landscape", "orchard", "pasture", "paddy field", "environment", "nature", "climate", "planet", "earth", "habitat", "biodiversity", "ecosystem", "greenhouse", "natural", "crop", "harvest", "nông", "rừng", "biển", "núi", "sông", "thiên nhiên", "môi trường"], "🌿"),
    (["football", "basketball", "volleyball", "badminton", "table tennis", "sport", "swim", "run", "jump", "skate", "cycle", "hike", "hiking", "cycling", "surfing", "fishing", "camping", "yoga", "exercise", "fitness", "karate", "marathon", "racket", "snowboarding", "press-up", "star jump", "playground", "slide", "swing", "seesaw", "sandbox", "climbing frame", "merry-go-round", "goal", "đạp xe", "bơi", "chạy", "thể thao"], "🏃"),
    (["music", "song", "sing", "dance", "concert", "instrument", "trumpet", "opera", "musician", "composer", "singer", "music room", "folk dance", "folk song", "nhạc", "hát", "múa"], "🎵"),
    (["doctor", "nurse", "medicine", "health", "healthy", "disease", "fever", "cough", "toothache", "stomach ache", "headache", "virus", "bacteria", "infection", "antibiotic", "fitness", "food poisoning", "germ", "nutrient", "organism", "treatment", "tuberculosis", "life expectancy", "sunburn", "acne", "eye drops", "flu", "vitamin", "sức khỏe", "bệnh", "thuốc"], "🩺"),
    (["computer", "robot", "technology", "device", "software", "smartphone", "tablet", "artificial intelligence", "algorithm", "chatbot", "automation", "robotics", "virtual reality", "digital", "online", "blended learning", "video conference", "social network", "social media", "emoji", "screen", "charger", "earphones", "wireless", "automatic", "khoa học", "công nghệ", "máy tính"], "💻"),
    (["city", "building", "tower", "house", "flat", "room", "street", "infrastructure", "suburb", "downtown", "neighbourhood", "skyscraper", "high-rise", "roof garden", "construction site", "concrete jungle", "urbanisation", "housing", "kitchen", "bathroom", "bedroom", "living room", "hall", "town house", "country house", "communal house", "stilt house", "đô thị", "thành phố", "nhà", "phòng"], "🏙️"),
    (["job", "career", "work", "worker", "engineer", "pilot", "architect", "writer", "actor", "police officer", "driver", "farmer", "artist", "artisan", "electrician", "firefighter", "barber", "candidate", "recruit", "employer", "employee", "salary", "interview", "qualification", "workplace", "internship", "mentor", "promotion", "apprenticeship", "school-leaver", "vocational", "undergraduate", "nghề", "công việc", "lương"], "💼"),
    (["holiday", "Tet", "festival", "party", "birthday", "firework", "fireworks", "celebrate", "special day", "candle", "present", "gift", "balloon", "lucky money", "decorate", "parade", "costume", "ceremony", "offering", "worship", "bữa tiệc", "lễ", "quà"], "🎉"),
    (["money", "shop", "market", "shopping", "price", "discount", "customer", "goods", "item", "voucher", "bargain", "convenience store", "department store", "supermarket", "speciality", "vendor", "souvenir", "mua", "chợ", "cửa hàng", "hàng hóa"], "🛒"),
    (["country", "ASEAN", "Viet Nam", "Australia", "Japan", "Malaysia", "Singapore", "Thailand", "America", "Britain", "Korea", "China", "United Nations", "international", "nationality", "foreign", "native speaker", "English-speaking country", "continent", "world", "quốc gia", "quốc tế"], "🌏"),
    (["red", "blue", "green", "yellow", "black", "white", "brown", "pink", "colour", "color", "màu"], "🎨"),
    (["morning", "afternoon", "evening", "night", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "calendar", "season", "spring", "summer", "autumn", "winter", "time", "deadline", "schedule", "future", "tuần", "mùa", "thời gian"], "🗓️"),
    (["sunny", "rainy", "windy", "cloudy", "hot", "cold", "weather", "storm", "stormy", "typhoon", "flood", "earthquake", "landslide", "natural disaster", "warning", "thời tiết", "bão", "lũ"], "🌦️"),
    (["bed", "table", "chair", "sofa", "lamp", "window", "door", "gate", "cup", "can", "bag", "box", "bench", "fence", "spoon", "fork", "plate", "knife", "pot", "stove", "fridge", "teapot", "blanket", "tent", "sleeping bag", "flashlight", "backpack", "locker", "wardrobe", "cupboard", "shelf", "sink", "furniture", "chest of drawers", "dishwasher", "cooker", "equipment", "folder", "notepad", "ink", "compass", "calculator", "map", "đồ", "bàn", "ghế", "tủ", "bếp"], "🧰"),
    (["shirt", "shirts", "shoe", "shoes", "shorts", "pants", "dress", "coat", "scarf", "hat", "glasses", "bracelet", "clothes", "trang phục", "quần", "áo", "giày"], "👕"),
    (["hello", "hi", "goodbye", "name", "friend", "communication", "message", "keep in touch", "broadcast", "headline", "journalist", "newsfeed", "podcast", "media", "account", "forum", "notification", "user name", "accent", "dialect", "bilingual", "fluent", "chào", "giao tiếp", "tin"], "💬"),
    (["eye", "ear", "nose", "mouth", "face", "head", "hair", "hand", "arm", "leg", "foot", "body", "cheek", "appearance", "tall", "short", "slim", "strong", "young", "old", "beautiful", "handsome", "curly", "straight", "cơ thể", "ngoại hình"], "🙂"),
    (["happy", "excited", "confident", "friendly", "funny", "kind", "careful", "clever", "creative", "hard-working", "patient", "popular", "valuable", "unusual", "strange", "crazy", "curious", "honesty", "maturity", "responsibility", "stress", "anxiety", "pressure", "confidence", "thích", "vui", "tự tin", "tốt bụng"], "😊"),
    (["eleven", "thirteen", "fourteen", "fifteen", "number", "addition", "subtraction", "multiplication", "division", "equation", "twenty", "thirty", "ninety", "hundred", "số", "phép"], "🔢"),
    (["toy", "doll", "dollhouse", "teddy bear", "kite", "yo-yo", "puzzle", "chess", "skipping", "cartoon", "comic book", "fairy tale", "story", "character", "dragon", "puppet", "animation", "plot", "review", "hobby", "leisure", "game", "đồ chơi", "truyện", "sở thích"], "🧸"),
    (["tourism", "tourist", "destination", "itinerary", "tour guide", "package tour", "landmark", "postcard", "place of interest", "pagoda", "temple", "museum", "theatre", "stadium", "cinema", "castle", "cathedral", "memorial", "statue", "wonder", "cave", "resort", "summer camp", "school trip", "picnic", "du lịch", "địa điểm"], "🧭"),
    (["protect", "destroy", "recycle", "reduce", "pollution", "pollutant", "deforestation", "global warming", "greenhouse gas", "carbon footprint", "renewable", "solar energy", "wind power", "hydropower", "eco-friendly", "sustainable", "endangered", "conservation", "extinction", "preserve", "restore", "sanctuary", "habitat loss", "poaching", "bảo vệ", "tái chế", "bảo tồn"], "♻️"),
    (["invention", "inventor", "experiment", "patent", "portable", "processor", "telescope", "galaxy", "gravity", "atmosphere", "alien", "science fiction", "phát minh", "thí nghiệm", "thiên hà"], "🔬"),
    (["community", "charity", "volunteer", "donate", "homeless", "nursing home", "pick up litter", "plant trees", "service", "orphanage", "benefit", "support", "develop", "appreciate", "encourage", "achieve", "nurture", "xã hội", "cộng đồng", "tình nguyện"], "🤝"),
    (["culture", "custom", "tradition", "heritage", "relic", "intangible", "identity", "ethnic group", "minority", "multicultural", "diversity", "immigrant", "integrate", "biography", "poetry", "poem", "hero", "genius", "battle", "military", "resistance war", "history", "historical", "truyền thống", "di sản", "văn hóa", "lịch sử"], "🏛️"),
    (["freedom", "conflict", "generation gap", "individualism", "screen time", "privacy", "social issue", "poverty", "unemployment", "bullying", "gender equality", "equal", "opportunity", "discrimination", "domestic violence", "problem", "issue", "choice", "priority", "decision-making", "time management", "independent", "self-reliant", "xung đột", "vấn đề", "lựa chọn"], "⚖️"),
    (["open", "close", "stand", "sit", "listen", "repeat", "write", "draw", "cook", "watch", "visit", "go", "get up", "have breakfast", "take care", "manage", "adapt", "interact", "explore", "attend", "carry out", "devote", "drop out", "pass away", "resign", "rule", "action", "hoạt động"], "✅"),
]


EMOJI_OVERRIDES = {
    "acne": "🔴",
    "addition": "➕",
    "alien": "👽",
    "ambulance": "🚑",
    "antibiotic": "💊",
    "apple": "🍎",
    "apricot blossom": "🌼",
    "arm": "💪",
    "artist": "🧑‍🎨",
    "baby": "👶",
    "backpack": "🎒",
    "badminton": "🏸",
    "bag": "👜",
    "bakery": "🥐",
    "ball": "⚽",
    "balloon": "🎈",
    "banana": "🍌",
    "barber": "💈",
    "barn": "🏚️",
    "basketball": "🏀",
    "bathroom": "🛁",
    "beach": "🏖️",
    "bed": "🛏️",
    "bedroom": "🛏️",
    "bee": "🐝",
    "bell": "🔔",
    "bench": "🪑",
    "bicycle": "🚲",
    "bike": "🚲",
    "bird": "🐦",
    "black": "⚫",
    "blackboard": "⬛",
    "blanket": "🛌",
    "blue": "🔵",
    "boat": "⛵",
    "book": "📖",
    "box": "📦",
    "bread": "🍞",
    "bridge": "🌉",
    "brother": "👦",
    "brown": "🟤",
    "bug": "🐛",
    "bus": "🚌",
    "butter": "🧈",
    "cake": "🎂",
    "calculator": "🧮",
    "calendar": "📅",
    "campfire": "🔥",
    "can": "🥫",
    "candle": "🕯️",
    "car": "🚗",
    "castle": "🏰",
    "cat": "🐱",
    "cathedral": "⛪",
    "chair": "🪑",
    "charger": "🔌",
    "chemist's": "⚕️",
    "chess": "♟️",
    "chicken": "🐔",
    "chips": "🍟",
    "cinema": "🎦",
    "city": "🌆",
    "classroom": "🏫",
    "climbing frame": "🧗",
    "clock": "🕒",
    "cloudy": "☁️",
    "coat": "🧥",
    "coffee": "☕",
    "comic book": "📚",
    "compass": "🧭",
    "computer room": "🖥️",
    "cooker": "🍚",
    "cough": "🤧",
    "country": "🌐",
    "cow": "🐄",
    "crocodile": "🐊",
    "cup": "☕",
    "dance": "💃",
    "desk": "🪑",
    "dictionary": "📘",
    "dishwasher": "🍽️",
    "division": "➗",
    "doctor": "🧑‍⚕️",
    "dog": "🐶",
    "doll": "🎎",
    "dollhouse": "🏠",
    "dolphin": "🐬",
    "door": "🚪",
    "dragon": "🐉",
    "dress": "👗",
    "driver": "🚕",
    "duck": "🦆",
    "ear": "👂",
    "earphones": "🎧",
    "earth": "🌍",
    "earthquake": "🌋",
    "egg": "🥚",
    "elephant": "🐘",
    "eleven": "1️⃣",
    "eye": "👁️",
    "face": "🙂",
    "factory": "🏭",
    "fairy tale": "🧚",
    "farmer": "🧑‍🌾",
    "fever": "🌡️",
    "field": "🌾",
    "fifteen": "🔢",
    "firefighter": "🧑‍🚒",
    "firework": "🎆",
    "fireworks": "🎆",
    "fish": "🐟",
    "flashlight": "🔦",
    "flat": "🏢",
    "flood": "🌊",
    "flower": "🌸",
    "flu": "🤒",
    "folder": "📁",
    "football": "⚽",
    "fork": "🍴",
    "fourteen": "🔢",
    "fox": "🦊",
    "fridge": "🧊",
    "garden": "🌷",
    "gate": "🚪",
    "giraffe": "🦒",
    "girl": "👧",
    "glasses": "👓",
    "globe": "🌐",
    "goat": "🐐",
    "goal": "🥅",
    "grandfather": "👴",
    "grandmother": "👵",
    "grapes": "🍇",
    "grass": "🌱",
    "green": "🟢",
    "gym": "🏋️",
    "hair": "💇",
    "hand": "✋",
    "hat": "🎩",
    "head": "🙂",
    "headache": "🤕",
    "heart": "❤️",
    "helmet": "⛑️",
    "horse": "🐴",
    "hospital": "🏥",
    "house": "🏠",
    "island": "🏝️",
    "jam": "🍓",
    "jelly": "🍮",
    "juice": "🧃",
    "kangaroo": "🦘",
    "karate": "🥋",
    "kitchen": "🍳",
    "kite": "🪁",
    "kitten": "🐱",
    "knife": "🔪",
    "lake": "🏞️",
    "lamp": "💡",
    "landslide": "⛰️",
    "leaf": "🍃",
    "leg": "🦵",
    "lemon": "🍋",
    "library": "🏛️",
    "lion": "🦁",
    "living room": "🛋️",
    "locker": "🗄️",
    "lucky money": "🧧",
    "map": "🗺️",
    "market": "🏪",
    "marathon": "🏃",
    "medicine": "💊",
    "merry-go-round": "🎠",
    "metro": "🚇",
    "milk": "🥛",
    "monkey": "🐒",
    "moon": "🌙",
    "morning": "🌅",
    "mother": "👩",
    "motorbike": "🏍️",
    "mountain": "⛰️",
    "mouth": "👄",
    "museum": "🏛️",
    "music room": "🎼",
    "musical instrument": "🎸",
    "newspaper": "📰",
    "night": "🌙",
    "noodles": "🍜",
    "nose": "👃",
    "notebook": "📓",
    "nurse": "👩‍⚕️",
    "nuts": "🥜",
    "omelette": "🍳",
    "orange": "🍊",
    "ox": "🐂",
    "pagoda": "🛕",
    "pancake": "🥞",
    "pants": "👖",
    "park": "🏞️",
    "party": "🥳",
    "pasta": "🍝",
    "peach blossom": "🌸",
    "peacock": "🦚",
    "pen": "🖊️",
    "pencil": "✏️",
    "pencil sharpener": "✏️",
    "penguin": "🐧",
    "pepper": "🌶️",
    "pig": "🐷",
    "pilot": "🧑‍✈️",
    "pink": "🌸",
    "pizza": "🍕",
    "plane": "✈️",
    "plate": "🍽️",
    "playground": "🛝",
    "police officer": "👮",
    "popcorn": "🍿",
    "post office": "🏤",
    "postcard": "📮",
    "pot": "🍲",
    "present": "🎁",
    "rainbow": "🌈",
    "rainy": "🌧️",
    "racket": "🏸",
    "rabbit": "🐰",
    "red": "🔴",
    "rice": "🍚",
    "river": "🏞️",
    "road sign": "🚸",
    "robot": "🤖",
    "rocket": "🚀",
    "rubber": "🧽",
    "ruler": "📏",
    "sail": "⛵",
    "sand": "🏖️",
    "sandbox": "🏖️",
    "sandwich": "🥪",
    "scarf": "🧣",
    "school": "🏫",
    "school bag": "🎒",
    "screen": "🖥️",
    "sea": "🌊",
    "seesaw": "⚖️",
    "shell": "🐚",
    "sheep": "🐑",
    "shirt": "👕",
    "shirts": "👕",
    "shoe": "👟",
    "shoes": "👟",
    "shop": "🛍️",
    "shopping centre": "🏬",
    "shorts": "🩳",
    "singer": "🎤",
    "sister": "👧",
    "skate": "🛼",
    "slide": "🛝",
    "snake": "🐍",
    "snowboarding": "🏂",
    "sofa": "🛋️",
    "spoon": "🥄",
    "spring": "🌸",
    "spring roll": "🥢",
    "square": "◼️",
    "stadium": "🏟️",
    "star jump": "⭐",
    "stomach ache": "🤢",
    "stove": "🔥",
    "sugar": "🍬",
    "summer": "☀️",
    "sun": "☀️",
    "sunny": "☀️",
    "supermarket": "🛒",
    "surfing": "🏄",
    "swing": "🛝",
    "table": "🪑",
    "table tennis": "🏓",
    "tablet": "📱",
    "teacher": "🧑‍🏫",
    "Teacher's Day": "🧑‍🏫",
    "tea": "🍵",
    "teapot": "🫖",
    "teddy bear": "🧸",
    "television": "📺",
    "temple": "🏯",
    "tent": "⛺",
    "theatre": "🎭",
    "thirteen": "🔢",
    "tiger": "🐯",
    "tofu": "⬜",
    "toothache": "🦷",
    "tower": "🗼",
    "toy": "🧸",
    "tractor": "🚜",
    "train": "🚆",
    "tree": "🌳",
    "trumpet": "🎺",
    "typhoon": "🌀",
    "umbrella": "☂️",
    "underground": "🚇",
    "van": "🚐",
    "village": "🏘️",
    "volleyball": "🏐",
    "waiter": "🤵",
    "wardrobe": "🚪",
    "water": "💧",
    "waterfall": "💦",
    "wave": "🌊",
    "weather": "🌦️",
    "weather forecast": "🌦️",
    "white": "⚪",
    "windy": "💨",
    "window": "🪟",
    "winter": "❄️",
    "worker": "👷",
    "writer": "✍️",
    "yellow": "🟡",
    "yo-yo": "🪀",
    "yogurt": "🥛",
    "zebra": "🦓",
    "zebu": "🐂",
    "zoo": "🦁",
}


EMOJI_OVERRIDES.update({
    "achievement": "🏆",
    "additional": "➕",
    "address": "📍",
    "admire": "🤩",
    "adopt": "🤱",
    "adventure": "🗺️",
    "ancestor": "🧓",
    "animated": "🎞️",
    "application": "📄",
    "argument": "💬",
    "attract": "🧲",
    "audience": "👥",
    "balance": "⚖️",
    "balanced": "⚖️",
    "belong to": "🔗",
    "between": "↔️",
    "biological": "🧬",
    "bloc": "🤝",
    "bond": "🔗",
    "bully": "😠",
    "bustling": "🏙️",
    "cancer": "🎗️",
    "capital": "🏛️",
    "characteristic": "✨",
    "chemical": "🧪",
    "childhood": "🧒",
    "classmate": "👫",
    "club": "👥",
    "complaint": "🗣️",
    "congested": "🚦",
    "convenient": "👌",
    "cooperate": "🤝",
    "counsellor": "🧑‍💼",
    "countryside": "🏞️",
    "cruel": "😈",
    "cut down on": "⬇️",
    "death": "🕯️",
    "defeat": "🏳️",
    "delay": "⏳",
    "detest": "😖",
    "dim light": "💡",
    "distraction": "🌀",
    "documentary": "🎬",
    "economy": "💹",
    "electricity": "⚡",
    "emission": "💨",
    "enemy": "⚔️",
    "energy": "⚡",
    "exhibition": "🖼️",
    "experience": "🌟",
    "facility": "🏢",
    "fold": "📄",
    "fragrance": "🌺",
    "function": "⚙️",
    "gardening": "🪴",
    "generation": "👥",
    "gratitude": "🙏",
    "habit": "🔁",
    "hay": "🌾",
    "homemaker": "🏡",
    "horror film": "👻",
    "household waste": "🗑️",
    "Independence Day": "🇻🇳",
    "in front of": "⬆️",
    "laundry": "🧺",
    "leader": "🧑‍💼",
    "litter": "🗑️",
    "load": "📦",
    "local people": "🧑‍🤝‍🧑",
    "marriage": "💍",
    "material": "🧱",
    "migrate": "🚶",
    "next to": "↔️",
    "organic": "🌱",
    "organise": "🗂️",
    "outdoor": "🏕️",
    "outdoors": "🏕️",
    "overcrowding": "👥",
    "personality": "🙂",
    "portrait": "🖼️",
    "pricey": "💸",
    "promote": "📣",
    "quality": "⭐",
    "regular": "🔁",
    "remote": "📍",
    "reusable": "♻️",
    "routine task": "📝",
    "rush hour": "🚦",
    "sculpture": "🗿",
    "single": "🎵",
    "skill": "🛠️",
    "sort": "🗃️",
    "stay in shape": "💪",
    "strength": "💪",
    "teenager": "🧑",
    "timetable": "📅",
    "upskill": "📈",
    "various": "🔀",
    "vast": "🌄",
    "viewer": "👀",
    "washing-up": "🧽",
    "weakness": "📉",
    "wish": "🌠",
    "youth": "🧑",
    "art": "🎨",
    "biodegradable": "♻️",
    "biodiversity": "🧬",
    "career path": "💼",
    "diameter": "📏",
    "dishwasher": "🧼",
    "fruit": "🍎",
    "inventor": "🧑‍🔬",
    "item": "🛍️",
    "kit": "🧰",
    "life skill": "🛠️",
    "music": "🎵",
    "science fiction": "🚀",
    "skyscraper": "🏙️",
    "spaceship": "🚀",
    "traffic jam": "🚦",
    "vegetable": "🥦",
    "work out": "🏋️",
})


TOPIC_OVERRIDES = {
    "art": "Âm nhạc và nghệ thuật",
    "biodegradable": "Bảo vệ môi trường",
    "biodiversity": "Thiên nhiên và môi trường",
    "career path": "Nghề nghiệp",
    "diameter": "Số đếm và toán học",
    "dishwasher": "Đồ vật hằng ngày",
    "fruit": "Đồ ăn và đồ uống",
    "inventor": "Khoa học và vũ trụ",
    "music": "Âm nhạc và nghệ thuật",
    "science fiction": "Khoa học và vũ trụ",
    "skyscraper": "Nhà cửa và thành phố",
    "spaceship": "Khoa học và vũ trụ",
    "traffic jam": "Giao thông",
    "vegetable": "Đồ ăn và đồ uống",
    "work out": "Thể thao và hoạt động",
}


TOPIC_EMOJI_FALLBACK = {
    "Động vật": "🐾",
    "Trường học": "📚",
    "Gia đình": "👨‍👩‍👧‍👦",
    "Đồ ăn và đồ uống": "🍽️",
    "Giao thông": "🚗",
    "Thiên nhiên và môi trường": "🌿",
    "Thể thao và hoạt động": "🏃",
    "Âm nhạc và nghệ thuật": "🎵",
    "Sức khỏe": "🩺",
    "Công nghệ": "💻",
    "Nhà cửa và thành phố": "🏙️",
    "Nghề nghiệp": "💼",
    "Lễ hội và ngày đặc biệt": "🎉",
    "Mua sắm": "🛒",
    "Quốc gia và thế giới": "🌏",
    "Màu sắc": "🎨",
    "Thời gian và mùa": "🗓️",
    "Thời tiết và thiên tai": "🌦️",
    "Đồ vật hằng ngày": "🧰",
    "Trang phục": "👕",
    "Giao tiếp và truyền thông": "💬",
    "Cơ thể và ngoại hình": "🙂",
    "Tính cách và cảm xúc": "😊",
    "Số đếm và toán học": "🔢",
    "Đồ chơi và giải trí": "🧸",
    "Du lịch và địa điểm": "🧭",
    "Bảo vệ môi trường": "♻️",
    "Khoa học và vũ trụ": "🔬",
    "Cộng đồng và xã hội": "🤝",
    "Văn hóa - lịch sử": "🏛️",
    "Kỹ năng sống và vấn đề xã hội": "⚖️",
    "Hành động thường ngày": "✅",
    "Vị trí và mô tả": "↔️",
}


def clean_word(word: str) -> str:
    keep_case = {"Australia", "Japan", "Malaysia", "Singapore", "Thailand", "Viet Nam", "America", "Britain", "Korea", "China", "ASEAN", "United Nations", "English", "Vietnamese", "PE", "DIY", "Earth", "Communist Party of Viet Nam", "Children's Day", "Teacher's Day", "Independence Day", "Tet"}
    word = re.sub(r"\s*\([^)]*\)", "", word).strip()
    word = re.sub(r"\s+", " ", word)
    if word in keep_case:
        return word
    return word[:1].lower() + word[1:]


def emoji_for(word: str, meaning: str) -> str:
    haystack = f"{word} {meaning}".lower()
    override = EMOJI_OVERRIDES.get(word) or EMOJI_OVERRIDES.get(word.lower())
    if override:
        return override
    for keys, emoji in EMOJI_RULES:
        if any(matches_key(haystack, key) for key in keys):
            return emoji
    return TOPIC_EMOJI_FALLBACK.get(topic_for(word, meaning), "🔹")


def topic_for(word: str, meaning: str) -> str:
    override = TOPIC_OVERRIDES.get(word) or TOPIC_OVERRIDES.get(word.lower())
    if override:
        return override
    haystack = f"{word} {meaning}".lower()
    for topic, keys in TOPIC_RULES:
        if any(matches_key(haystack, key) for key in keys):
            return topic
    return "Từ vựng chung"


def matches_key(haystack: str, key: str) -> bool:
    key = key.lower()
    if re.fullmatch(r"[\w][\w '\-]*", key):
        return re.search(rf"(?<!\w){re.escape(key)}(?!\w)", haystack) is not None
    return key in haystack


def normalise(entries):
    dedup = {}
    for word, meaning in entries:
        word = clean_word(word)
        meaning = re.sub(r"\s+", " ", meaning.strip())
        if not word or "/" in word:
            continue
        dedup.setdefault(
            word.lower(),
            {
                "word": word,
                "meaning": meaning,
                "topic": topic_for(word, meaning),
                "emoji": emoji_for(word, meaning),
            },
        )
    return sorted(dedup.values(), key=lambda item: item["word"].casefold())


def main():
    out_dir = Path("global-success-vocabulary")
    out_dir.mkdir(exist_ok=True)

    all_items = []
    stats = {}
    for grade in range(1, 13):
        items = normalise(RAW[grade])
        stats[grade] = len(items)
        (out_dir / f"grade{grade}.json").write_text(
            json.dumps(items, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        all_items.extend({**item, "grade": grade} for item in items)

    # Remove exact duplicate objects in the merged file while preserving grade-specific rows.
    seen = set()
    merged = []
    for item in sorted(all_items, key=lambda x: (x["grade"], x["word"].casefold())):
        key = tuple(item.items())
        if key not in seen:
            seen.add(key)
            merged.append(item)

    (out_dir / "merged_all_grades.json").write_text(
        json.dumps(merged, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    word_grades = defaultdict(set)
    for item in merged:
        word_grades[item["word"].casefold()].add(item["grade"])
    overlaps = {
        word: sorted(grades)
        for word, grades in sorted(word_grades.items())
        if len(grades) > 1
    }
    report = {
        "counts_by_grade": stats,
        "total_merged_objects": len(merged),
        "overlap_words": overlaps,
        "overlap_word_count": len(overlaps),
    }
    (out_dir / "quality_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    for path in sorted(out_dir.glob("*.json")):
        json.loads(path.read_text(encoding="utf-8"))
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
