/** Lesson bank: { level: { topic: [{ title, sentences }] } } */
export const LESSON_BANK = {
  a1: {
    daily: [
      { title: 'Evening at home', sentences: ['I watch TV after dinner.', 'My sister reads a book.', 'Dad washes the dishes.', 'We talk about our day.', 'I go to bed at nine.'] },
      { title: 'My neighbourhood', sentences: ['There is a shop near my house.', 'The bakery smells very good.', 'Children play in the street.', 'Our neighbour is very kind.', 'I like living here.'] },
      { title: 'Birthday party', sentences: ['Today is my birthday.', 'My friends come to my house.', 'We eat cake and sing songs.', 'I get many nice presents.', 'I am very happy today.'] },
      { title: 'At the market', sentences: ['We go to the market on Sunday.', 'My mother buys vegetables.', 'The fruit is fresh and cheap.', 'I carry the heavy bag.', 'We walk home together.'] },
    ],
    travel: [
      { title: 'At the airport', sentences: ['We arrive at the airport early.', 'My passport is in my bag.', 'The plane is very big.', 'We wait at gate twelve.', 'I look out the window.'] },
      { title: 'On the train', sentences: ['The train leaves at ten.', 'I buy a ticket at the station.', 'I find a seat by the window.', 'The countryside is beautiful.', 'We arrive in two hours.'] },
      { title: 'At the beach', sentences: ['The sand is warm and soft.', 'I swim in the blue sea.', 'My brother builds a sandcastle.', 'We eat ice cream on the beach.', 'The sun goes down slowly.'] },
      { title: 'In a taxi', sentences: ['I call a taxi to the hotel.', 'The driver is very friendly.', 'Please take me to this address.', 'How much is the fare?', 'Thank you, keep the change.'] },
      { title: 'At the museum', sentences: ['We visit the city museum.', 'There are old paintings inside.', 'Please do not touch the art.', 'I learn about history today.', 'The museum closes at five.'] },
      { title: 'Buying a ticket', sentences: ['I want one ticket, please.', 'How much does it cost?', 'Here is my money.', 'Where is the platform?', 'The train is on time.'] },
      { title: 'At the restaurant', sentences: ['A table for two, please.', 'Can I see the menu?', 'I would like chicken and rice.', 'The soup is very hot.', 'The bill, please.'] },
      { title: 'Lost and found', sentences: ['I cannot find my bag.', 'It is blue and small.', 'Excuse me, is this your bag?', 'Yes, thank you very much.', 'I am so happy now.'] },
    ],
    work: [
      { title: 'At the shop', sentences: ['The shop opens at eight.', 'I help customers every day.', 'This shirt is on sale.', 'The cashier counts the money.', 'We close the shop at six.'] },
      { title: 'A busy kitchen', sentences: ['The chef cooks delicious food.', 'She cuts vegetables quickly.', 'The kitchen is very hot.', 'We wash the plates after lunch.', 'The customers are happy.'] },
      { title: 'On the farm', sentences: ['The farmer wakes up early.', 'Cows give fresh milk.', 'Chickens lay eggs every morning.', 'He feeds the animals.', 'The fields are green.'] },
      { title: 'At the hospital', sentences: ['The doctor helps sick people.', 'The nurse is very kind.', 'Please wait in this room.', 'Take this medicine twice a day.', 'I feel better now.'] },
      { title: 'The post office', sentences: ['I send a letter to my friend.', 'How much is the stamp?', 'The package is not heavy.', 'Please write the address clearly.', 'Thank you for your help.'] },
      { title: 'Building a house', sentences: ['The builder works very hard.', 'He uses bricks and cement.', 'The house has three rooms.', 'Workers wear safety helmets.', 'The new house looks nice.'] },
      { title: 'A police officer', sentences: ['The police officer keeps us safe.', 'He wears a blue uniform.', 'Please drive slowly here.', 'She helps lost children.', 'We respect the police.'] },
      { title: 'At the bakery', sentences: ['The baker makes fresh bread.', 'It smells wonderful in here.', 'I buy two loaves of bread.', 'The cakes look delicious.', 'We open early every morning.'] },
    ],
    study: [
      { title: 'In the library', sentences: ['The library is very quiet.', 'I borrow a book about animals.', 'Please return it in two weeks.', 'The librarian helps me find books.', 'I love reading stories.'] },
      { title: 'My classroom', sentences: ['There are twenty desks in the room.', 'The whiteboard is on the wall.', 'We raise our hand to speak.', 'The lesson is about animals.', 'Homework is on page ten.'] },
      { title: 'Learning to write', sentences: ['I write my name on the paper.', 'Use a pencil, not a pen.', 'Write on the line carefully.', 'My handwriting is getting better.', 'The teacher smiles at me.'] },
      { title: 'Science class', sentences: ['We learn about plants today.', 'Seeds grow into flowers.', 'Water helps plants grow.', 'We put seeds in the soil.', 'Our experiment is fun.'] },
      { title: 'Music lesson', sentences: ['We sing a song together.', 'The piano is in the corner.', 'Clap your hands to the beat.', 'Music makes me feel happy.', 'Our teacher plays the guitar.'] },
      { title: 'Art class', sentences: ['I draw a picture of a cat.', 'I use red, blue, and yellow paint.', 'Art class is my favourite.', 'We hang pictures on the wall.', 'My painting is very colourful.'] },
      { title: 'PE class', sentences: ['We run in the school yard.', 'PE class is on Wednesday.', 'We play football with friends.', 'Drink water after exercise.', 'I am tired but happy.'] },
    ],
    health: [
      { title: 'At the dentist', sentences: ['I go to the dentist twice a year.', 'Brush your teeth every day.', 'Open your mouth, please.', 'Do not eat too much candy.', 'My teeth are clean now.'] },
      { title: 'Healthy breakfast', sentences: ['I eat eggs and fruit for breakfast.', 'Milk is good for your bones.', 'Do not skip breakfast.', 'Oatmeal keeps you full.', 'A healthy meal gives you energy.'] },
      { title: 'Exercise every day', sentences: ['I walk to school every morning.', 'Exercise keeps your body strong.', 'I stretch before I run.', 'Playing outside is good exercise.', 'I feel great after a workout.'] },
      { title: 'When I am sick', sentences: ['I have a cold today.', 'My throat hurts a little.', 'I stay in bed and rest.', 'Mother gives me warm soup.', 'I will feel better soon.'] },
      { title: 'Washing hands', sentences: ['Wash your hands before eating.', 'Use soap and warm water.', 'Germs can make you sick.', 'Dry your hands with a towel.', 'Clean hands keep you healthy.'] },
      { title: 'Sleep well', sentences: ['I sleep eight hours every night.', 'A dark room helps you sleep.', 'Do not use your phone in bed.', 'Good sleep helps you learn.', 'I wake up feeling rested.'] },
      { title: 'Drinking water', sentences: ['I drink water all day long.', 'Water is better than soda.', 'Bring a bottle to school.', 'Your body needs water.', 'I feel thirsty after sport.'] },
      { title: 'Fruits and vegetables', sentences: ['Eat five fruits and vegetables a day.', 'Carrots are good for your eyes.', 'Bananas give you energy.', 'I like salad with lunch.', 'Healthy food tastes good too.'] },
    ],
    tech: [
      { title: 'Using the internet', sentences: ['I search for information online.', 'The website loads slowly today.', 'Click on the blue link.', 'Do not share your password.', 'The internet is very useful.'] },
      { title: 'Playing games', sentences: ['I play games on my tablet.', 'My favourite game is about racing.', 'Do not play for too long.', 'I play with my brother.', 'Games are fun but take breaks.'] },
      { title: 'Sending email', sentences: ['I write an email to my teacher.', 'Type the address carefully.', 'Click send when you finish.', 'Check your inbox every day.', 'Email is fast and easy.'] },
      { title: 'Taking photos', sentences: ['I take a photo of my dog.', 'The camera flash is bright.', 'Save the picture on your phone.', 'I share photos with my family.', 'This photo is very clear.'] },
      { title: 'Watching videos', sentences: ['I watch videos to learn English.', 'Pause the video if you need.', 'The speaker talks very clearly.', 'I watch for twenty minutes.', 'Videos help me study.'] },
      { title: 'Charging devices', sentences: ['My tablet battery is empty.', 'Plug the charger into the wall.', 'Wait until it is fully charged.', 'Do not use it while charging.', 'A full battery lasts all day.'] },
      { title: 'Using apps', sentences: ['I download a new app today.', 'This app teaches me words.', 'Tap the icon to open it.', 'Some apps are free to use.', 'I learn something new every day.'] },
      { title: 'Online safety', sentences: ['Do not talk to strangers online.', 'Ask a parent before downloading.', 'Keep your personal information private.', 'Tell an adult if something feels wrong.', 'Stay safe on the internet.'] },
    ],
    society: [
      { title: 'Helping others', sentences: ['I help my grandmother carry bags.', 'Kind people make the world better.', 'We donate old clothes to charity.', 'Helping others feels good.', 'Small acts of kindness matter.'] },
      { title: 'Rules at school', sentences: ['We follow rules at school.', 'Be quiet in the library.', 'Do not run in the hallway.', 'Respect your teachers and friends.', 'Rules keep everyone safe.'] },
      { title: 'Festivals in town', sentences: ['Our town has a spring festival.', 'People wear colourful clothes.', 'There is music and dancing.', 'Children eat sweet treats.', 'Festivals bring people together.'] },
      { title: 'Volunteering', sentences: ['We clean the beach on Saturday.', 'Many people join the event.', 'We collect plastic from the sand.', 'The beach looks much cleaner.', 'Volunteering helps our community.'] },
      { title: 'Being polite', sentences: ['Say please and thank you.', 'Wait your turn in line.', 'Hold the door for others.', 'Polite people are well liked.', 'Good manners show respect.'] },
      { title: 'Sharing with others', sentences: ['I share my lunch with a friend.', 'Sharing makes friendships stronger.', 'We take turns with the toys.', 'Generous people are happy people.', 'It feels good to share.'] },
      { title: 'Respecting elders', sentences: ['We respect our grandparents.', 'Elders have much wisdom to share.', 'Listen carefully when they speak.', 'Help them cross the street.', 'Respect is important in every culture.'] },
      { title: 'Community garden', sentences: ['Our neighbourhood has a garden.', 'Families plant flowers together.', 'Children water the plants.', 'The garden makes our street beautiful.', 'We meet new friends there.'] },
    ],
  },
};
