"""Generate ForgeConfig.mqh from export payload."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from config import DEFAULT_MAX_HOLD_BARS, DEFAULT_TRAIL_ACTIVATE_R, DEFAULT_TRAIL_DISTANCE_R


def _fmt_double(v: float) -> str:
  return f"{float(v):.10g}"


def _write_rules(name: str, rules: list[dict]) -> list[str]:
  n = len(rules)
  lines = [f"#define {name}_COUNT {n}"]
  if n == 0:
    lines.append(f"string {name}_FEAT[] = {{}};")
    lines.append(f"string {name}_OP[] = {{}};")
    lines.append(f"double {name}_THR[] = {{}};")
    lines.append(f"double {name}_W[] = {{}};")
    return lines

  feats = ", ".join(f'"{r["feat"]}"' for r in rules)
  ops = ", ".join(f'"{r["op"]}"' for r in rules)
  thrs = ", ".join(_fmt_double(r["thr"]) for r in rules)
  ws = ", ".join(_fmt_double(r["w"]) for r in rules)
  lines.extend([
    f"string {name}_FEAT[{name}_COUNT] = {{{feats}}};",
    f"string {name}_OP[{name}_COUNT] = {{{ops}}};",
    f"double {name}_THR[{name}_COUNT] = {{{thrs}}};",
    f"double {name}_W[{name}_COUNT] = {{{ws}}};",
  ])
  return lines


def _write_ml_array(name: str, values: list[float]) -> str:
  if not values:
    return f"double {name}[] = {{}};"
  body = ", ".join(_fmt_double(v) for v in values)
  return f"double {name}[{len(values)}] = {{{body}}};"


def _write_ml_model(prefix: str, model: dict | None) -> list[str]:
  if not model:
    return [
      f"#define FORGE_{prefix}_ENABLED 0",
      f"double FORGE_{prefix}_COEF[] = {{}};",
      f"double FORGE_{prefix}_INTERCEPT = 0.0;",
    ]
  coef = model.get("coef") or []
  lines = [
    f"#define FORGE_{prefix}_ENABLED 1",
    _write_ml_array(f"FORGE_{prefix}_COEF", coef),
    f"double FORGE_{prefix}_INTERCEPT = {_fmt_double(model['intercept'])};",
  ]
  return lines


def payload_to_mqh(payload: dict[str, Any]) -> str:
  meta = payload.get("meta") or {}
  strat = payload.get("strategy") or {}
  ml = payload.get("ml") or {}
  exported = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

  lines = [
    "// Auto-generated by ForexForge — do not edit manually.",
    f"// Model: {meta.get('trade_model_id', '?')}",
    f"// Week: {meta.get('week_start', '?')}",
    f"// Exported: {exported}",
    "",
    f'#define FORGE_MODEL_ID "{meta.get("trade_model_id", "")}"',
    f'#define FORGE_MODEL_LABEL "{str(meta.get("label", "")).replace(chr(34), "")}"',
    f'#define FORGE_WEEK_START "{meta.get("week_start", "")}"',
    f'#define FORGE_STRATEGY_NAME "{str(strat.get("name", "")).replace(chr(34), "")}"',
    "",
    f"#define FORGE_SCORE_THRESHOLD {_fmt_double(strat.get('score_threshold', 2.0))}",
    f"#define FORGE_ML_PROB_MIN {_fmt_double(strat.get('ml_prob_min', 0.4))}",
    f"#define FORGE_MIN_RULES_MATCH {int(strat.get('min_rules_match', 2))}",
    f"#define FORGE_MIN_BARS_BETWEEN {int(strat.get('min_bars_between', 4))}",
    f"#define FORGE_MAX_TRADES_WEEK {int(strat.get('max_trades_per_week', 2))}",
    f"#define FORGE_MAX_HOLD_BARS {int(strat.get('max_hold_bars', DEFAULT_MAX_HOLD_BARS))}",
    f"#define FORGE_RR {_fmt_double(strat.get('rr', 2.5))}",
    f"#define FORGE_ATR_MULT {_fmt_double(strat.get('atr_mult', 0.9))}",
    f'#define FORGE_EXIT_MODE "{strat.get("exit_mode", "full")}"',
    f"#define FORGE_SESSION_FILTER {1 if strat.get('session_filter', True) else 0}",
    f"#define FORGE_PARTIAL_PCT {_fmt_double(strat.get('partial_pct', 0.4))}",
    f"#define FORGE_PARTIAL_AT_R {_fmt_double(strat.get('partial_at_r', 1.2))}",
    f"#define FORGE_TRAIL_ACTIVATE_R {_fmt_double(strat.get('trail_activate_r', DEFAULT_TRAIL_ACTIVATE_R))}",
    f"#define FORGE_TRAIL_DISTANCE_R {_fmt_double(strat.get('trail_distance_r', DEFAULT_TRAIL_DISTANCE_R))}",
    f"#define FORGE_SPREAD_PIPS {_fmt_double(meta.get('spread_pips', 1.0))}",
    f"#define FORGE_SLIPPAGE_PIPS {_fmt_double(meta.get('slippage_pips', 0.3))}",
    "",
  ]

  lines.extend(_write_rules("FORGE_LONG_RULES", strat.get("long_rules") or []))
  lines.append("")
  lines.extend(_write_rules("FORGE_SHORT_RULES", strat.get("short_rules") or []))
  lines.append("")

  features = ml.get("features") or []
  lines.append(f"#define FORGE_ML_FEATURE_COUNT {len(features)}")
  if features:
    feat_str = ", ".join(f'"{f}"' for f in features)
    lines.append(f"string FORGE_ML_FEATURES[FORGE_ML_FEATURE_COUNT] = {{{feat_str}}};")
  else:
    lines.append("string FORGE_ML_FEATURES[] = {};")
  lines.append(f"#define FORGE_ML_ENABLED {1 if ml.get('enabled') else 0}")
  lines.append(_write_ml_array("FORGE_ML_MEAN", ml.get("mean") or []))
  lines.append(_write_ml_array("FORGE_ML_SCALE", ml.get("scale") or []))
  lines.extend(_write_ml_model("ML_LONG", ml.get("long")))
  lines.extend(_write_ml_model("ML_SHORT", ml.get("short")))
  lines.append("")
  return "\n".join(lines)


def write_mqh(payload: dict[str, Any], path: Path) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(payload_to_mqh(payload), encoding="utf-8")


def write_json(payload: dict[str, Any], path: Path) -> None:
  path.parent.mkdir(parents=True, exist_ok=True)
  with open(path, "w", encoding="utf-8") as f:
    json.dump(payload, f, indent=2, ensure_ascii=False)
